<?php
/**
 * Accessibility statement (BFSG) — English (courtesy translation).
 * Lists what has actually been implemented and the known gaps. Variables from legal/barrierefreiheit.php.
 */
?>
<h2>Our aim</h2>
<p>
  We want this shop to be usable by everyone — with a keyboard, with a screen reader, with enlarged
  text, with reduced motion. The basis is the requirements of the German Accessibility Strengthening
  Act (BFSG) and the standard EN 301 549, which refers to WCAG 2.1 Level AA.
</p>

<h2>Status of implementation</h2>
<p>
  In our assessment this website is <strong>largely compliant</strong> with WCAG 2.1 Level AA. The
  assessment is based on an internal review, not on an external audit.
</p>

<h3>What has been implemented</h3>
<ul>
  <li><strong>Usable without JavaScript:</strong> navigation, filters, bag, checkout and seller area
      work completely with plain HTML forms. JavaScript only adds convenience (countdown, quantity
      switch, gentle fade-ins).</li>
  <li><strong>Keyboard operation:</strong> all interactive elements are reachable, with a visible
      focus ring; a "Skip to content" link is at the top of each page.</li>
  <li><strong>Contrast:</strong> every text node on the main pages was measured automatically
      (actually rendered colour against actually rendered background, including transparency). All
      reach at least 4.5:1, large text at least 3:1. The dark Vault area uses its own grey values,
      and accent colours have a darker text variant on light backgrounds.</li>
  <li><strong>Structure:</strong> one H1 per page, logical heading levels, landmarks
      (<code>header</code>, <code>nav</code>, <code>main</code>, <code>footer</code>), labelled form
      fields, linked error messages.</li>
  <li><strong>Images:</strong> product images carry alternative text from brand and item name; purely
      decorative graphics are hidden from assistive technology.</li>
  <li><strong>Motion:</strong> with the system setting "reduce motion" enabled, the marquee,
      fade-ins and transitions are switched off.</li>
  <li><strong>Zoom and small screens:</strong> the layout remains usable up to 400 % zoom without
      horizontal scrolling of the page content.</li>
  <li><strong>Language:</strong> the page language is marked in the HTML and can be switched via the
      language selector (ten languages).</li>
  <li><strong>Image gallery:</strong> every product image is a normal link to the image file. Without
      JavaScript it opens directly; with JavaScript in a lightbox that closes with Esc and can be
      browsed with the arrow keys.</li>
  <li><strong>Search suggestions:</strong> operable with arrow keys and Enter, closable with Esc. The
      search field itself also works as an ordinary form without suggestions.</li>
  <li><strong>Wishlist:</strong> implemented as a form; the state is held in <code>aria-pressed</code>
      and is saved correctly without JavaScript too.</li>
</ul>

<h3>Known limitations</h3>
<ul>
  <li><strong>Product images from third-party sellers:</strong> alternative texts are generated
      automatically from brand and name. They do not describe the motif in detail — if you have
      questions about an item we are happy to describe it by e-mail.</li>
  <li><strong>Payment page:</strong> payment runs at Stripe. Stripe is responsible for the
      accessibility of those pages; we are not aware of any conformance deficits but have not
      tested them ourselves.</li>
  <li><strong>Vault countdown:</strong> the remaining time updates every second. The decisive price
      is shown as text next to it and only changes after a page load, so screen reader use is not
      disturbed by live changes.</li>
  <li><strong>PDF documents:</strong> invoices and return labels are partly generated by sellers and
      carriers and may not be tagged. On request we provide the contents in an accessible form.</li>
</ul>

<h2>Feedback and contact</h2>
<p>
  If you encounter a barrier, write to <?= $mail ?> with the subject "Accessibility" and, if
  possible, name the page and your assistive technology. We reply within one working day and name a
  date for the fix. If you need information in another form — larger text, plain text, read aloud by
  phone — just say so; we provide it free of charge.
</p>

<h2>Enforcement procedure</h2>
<p>
  If our reply does not help, you can contact the market surveillance authority of the German
  federal states for the accessibility of products and services (MDBD). It is the body responsible
  under the BFSG for complaints about the accessibility of services:
  <a href="https://www.marktueberwachungsstelle.de" rel="noopener">marktueberwachungsstelle.de</a>.
</p>

<h2>Preparation of this statement</h2>
<p>
  This statement was prepared on <?= h(vr_date(strtotime('2026-08-01'))) ?> on the basis of an
  internal self-assessment: keyboard navigation, automated contrast measurement of all text nodes
  in a real browser, testing with JavaScript disabled, review of heading structure and form labels.
  No external audit has taken place. We update the statement when the shop changes substantially.
</p>
