<?php
/**
 * ChatHelp — apply-widecat-at-it (CH_WIDECAT_ATIT) — Genis katalog Batch 1
 *  AT: 39 -> 77 belge (+38) · 4 yeni kategori (Familie/Kfz/Gesundheit/Finanzen)
 *  IT: 39 -> 77 belge (+38) · 4 yeni kategori (Famiglia/Auto/Salute/Fisco)
 *  Tum belgeler ULKENIN KENDI hukukuna gore (AT: ABGB/MRG/FAGG/VStG/KFG/BAO/
 *  PatVG/VKrG/VZKG/BPGG/AngG... · IT: Codice Civile/L.431/1998/L.300/1970/
 *  Codice del Consumo/CdS/TUB/L.219/2017...), secenekli (opts) sorularla.
 *  Mevcut kategori/belge yapisina cerrahi eklenir; CAT_DOCS enjeksiyon
 *  donguleri yeni girisleri otomatik alir. Kategori sira kilidi (CH_CC_CATLOCK)
 *  yeni kategorileri sona deterministik ekler.
 * KULLANIM: pull-updates.php?files=apply-widecat-at-it.php
 */
header('Content-Type: text/plain; charset=UTF-8');
error_reporting(E_ERROR | E_PARSE);
echo "apply-widecat-at-it BASLADI OK (PHP ".PHP_VERSION.")\n\n";

$file = __DIR__.'/index.php';
$src = @file_get_contents($file);
if ($src===false) exit("index.php okunamadi\n");
if (strpos($src,'CH_WIDECAT_ATIT')!==false) exit("Zaten ekli (CH_WIDECAT_ATIT).\n");

$fail=[];

/* ═══ [1] AT: kategoriler + X_ORDER ═══ */
$o1 = "    at_aemter:{n:\"Ämter & Behörden\",ic:\"🏛️\"}\n  };\n  var X_ORDER=[\"at_kuendigungen\",\"at_wohnen\",\"at_arbeit\",\"at_konsum\",\"at_vertraege\",\"at_aemter\"];";
$n1 = "    at_aemter:{n:\"Ämter & Behörden\",ic:\"🏛️\"},\n"
    . "    at_familie:{n:\"Familie & Vorsorge\",ic:\"👪\"},\n"
    . "    at_kfz:{n:\"Auto & Verkehr\",ic:\"🚗\"},\n"
    . "    at_gesundheit:{n:\"Gesundheit & Soziales\",ic:\"🏥\"},\n"
    . "    at_finanzen:{n:\"Banken & Finanzen\",ic:\"💶\"}\n  };\n"
    . "  var X_ORDER=[\"at_kuendigungen\",\"at_wohnen\",\"at_arbeit\",\"at_konsum\",\"at_vertraege\",\"at_aemter\",\"at_familie\",\"at_kfz\",\"at_gesundheit\",\"at_finanzen\"]; /*CH_WIDECAT_ATIT*/";
$c=0; $src=str_replace($o1,$n1,$src,$c);
echo ($c===1?"  ✓ [1] AT +4 kategori\n":"  ✗ [1] AT XC anchor ($c)\n"); if($c!==1)$fail[]=1;

/* ═══ [2] AT: +38 belge ═══ */
$atDocs = <<<'JS'
    /* CH_WIDECAT_ATIT — genis katalog */
    at_strom_kuendigung:{ic:"⚡",n:"Strom/Gas kündigen (Anbieterwechsel)",cat:"at_kuendigungen",tier:"einfach",q:[Pq("anbieter","Energieanbieter: Name und Adresse",true),Pq("kunde","Kunden-/Vertragsnummer",true),Pq("zaehlpunkt","Zählpunktnummer (33-stellig, auf der Rechnung)",false),Pq("termin","Kündigungstermin",false,["Zum nächstmöglichen Termin","Zu einem Datum"]),Pq("daten","Ihre Daten: Name und Adresse",true)]},
    at_zeitung_kuendigung:{ic:"📰",n:"Zeitungs-/Zeitschriftenabo kündigen",cat:"at_kuendigungen",tier:"einfach",q:[Pq("verlag","Verlag: Name und Adresse",true),Pq("abonr","Abonummer",true),Pq("termin","Kündigungstermin",true),Pq("daten","Ihre Daten: Name und Adresse",true)]},
    at_verein_austritt:{ic:"🤝",n:"Vereinsaustritt erklären",cat:"at_kuendigungen",tier:"einfach",q:[Pq("verein","Verein: Name und Adresse",true),Pq("mitglied","Mitgliedsnummer (falls vorhanden)",false),Pq("termin","Austrittstermin (laut Statuten, oft Jahresende)",true),Pq("daten","Ihre Daten: Name und Adresse",true)]},
    at_sepa_widerruf:{ic:"🏦",n:"SEPA-Einzugsermächtigung widerrufen",cat:"at_kuendigungen",tier:"einfach",q:[Pq("firma","Zahlungsempfänger: Name und Adresse",true),Pq("mandat","Mandatsreferenz / Kundennummer",true),Pq("grund","Grund (optional)",false),Pq("daten","Ihre Daten: Name und Adresse",true)]},
    at_mietzinsminderung:{ic:"📉",n:"Mietzinsminderung wegen Mängel (§ 1096 ABGB)",cat:"at_wohnen",tier:"standard",q:[Pq("vermieter","Vermieter/Hausverwaltung: Name und Adresse",true),Pq("adresse","Adresse der Wohnung",true),Pq("mangel","Mangel genau beschreiben (seit wann, Ausmaß)",true),Pq("gemeldet","Wurde der Mangel bereits gemeldet?",true,["Ja, schriftlich","Ja, mündlich","Nein"]),Pq("minderung","Gewünschte Minderung (% oder €)",false),Pq("daten","Ihre Daten: Name",true)]},
    at_maengelanzeige:{ic:"🔧",n:"Mängelanzeige an Vermieter",cat:"at_wohnen",tier:"einfach",q:[Pq("vermieter","Vermieter/Hausverwaltung: Name und Adresse",true),Pq("adresse","Adresse der Wohnung",true),Pq("mangel","Mangel und Auswirkung",true),Pq("frist","Frist zur Behebung (z. B. 14 Tage)",true),Pq("daten","Ihre Daten: Name",true)]},
    at_kaution_rueck:{ic:"💰",n:"Kaution zurückfordern",cat:"at_wohnen",tier:"einfach",q:[Pq("vermieter","Vermieter: Name und Adresse",true),Pq("adresse","Adresse der (ehemaligen) Wohnung",true),Pq("auszug","Auszugs-/Übergabedatum",true),Pq("kaution","Kautionshöhe (€)",true),Pq("iban","Ihre IBAN für die Rücküberweisung",true),Pq("daten","Ihre Daten: Name und neue Adresse",true)]},
    at_untermiete_anfrage:{ic:"👥",n:"Zustimmung zur Untervermietung anfragen",cat:"at_wohnen",tier:"einfach",q:[Pq("vermieter","Vermieter: Name und Adresse",true),Pq("adresse","Adresse der Wohnung",true),Pq("umfang","Ganz oder teilweise? Zeitraum?",true),Pq("person","Untermieter (falls schon bekannt)",false),Pq("daten","Ihre Daten: Name",true)]},
    at_aufkuendigung_einwendung:{ic:"⚖️",n:"Einwendungen gegen Aufkündigung (MRG)",cat:"at_wohnen",tier:"komplex",q:[Pq("gericht","Bezirksgericht (laut Aufkündigung)",true),Pq("az","Aktenzeichen der Aufkündigung",true),Pq("zugestellt","Zustelldatum (Frist: 4 Wochen!)",true),Pq("grund","Angeführter Kündigungsgrund",true),Pq("einwand","Ihre Einwendungen in eigenen Worten",true),Pq("daten","Ihre Daten: Name und Adresse",true)]},
    at_uebergabeprotokoll:{ic:"📋",n:"Wohnungsübergabeprotokoll",cat:"at_wohnen",tier:"einfach",q:[Pq("art","Anlass",true,["Einzug","Auszug"]),Pq("adresse","Adresse der Wohnung (inkl. Top)",true),Pq("zustand","Zustand je Raum / Mängel",true),Pq("zaehler","Zählerstände (Strom, Gas, Wasser)",false),Pq("schluessel","Übergebene Schlüssel (Anzahl)",false),Pq("parteien","Namen beider Parteien",true)]},
    at_dienstzeugnis:{ic:"📜",n:"Dienstzeugnis anfordern (§ 39 AngG)",cat:"at_arbeit",tier:"einfach",q:[Pq("firma","Arbeitgeber: Name und Adresse",true),Pq("zeitraum","Beschäftigt von – bis",true),Pq("taetigkeit","Position / Tätigkeit",true),Pq("art","Gewünschte Art",true,["Einfaches Dienstzeugnis","Qualifiziertes Dienstzeugnis"]),Pq("daten","Ihre Daten: Name und Adresse",true)]},
    at_karenz:{ic:"👶",n:"Karenz anmelden (MSchG/VKG)",cat:"at_arbeit",tier:"standard",q:[Pq("firma","Arbeitgeber: Name und Adresse",true),Pq("geburt","(Errechneter) Geburtstermin des Kindes",true),Pq("beginn","Karenzbeginn",true),Pq("dauer","Karenzdauer (bis max. 2. Geburtstag)",true),Pq("daten","Ihre Daten: Name und Adresse",true)]},
    at_elternteilzeit:{ic:"🕐",n:"Elternteilzeit beantragen",cat:"at_arbeit",tier:"standard",q:[Pq("firma","Arbeitgeber: Name und Adresse",true),Pq("kind","Geburtsdatum des Kindes",true),Pq("beginn","Gewünschter Beginn",true),Pq("stunden","Gewünschte Wochenstunden und Lage",true),Pq("dauer","Gewünschte Dauer",true),Pq("daten","Ihre Daten: Name",true)]},
    at_gehalt_mahnung:{ic:"💶",n:"Offenes Gehalt / Überstunden einfordern",cat:"at_arbeit",tier:"standard",q:[Pq("firma","Arbeitgeber: Name und Adresse",true),Pq("offen","Offene Beträge (Monat, Höhe, Art)",true),Pq("frist","Zahlungsfrist (z. B. 14 Tage)",true),Pq("hinweis","Bereits gemahnt?",false,["Nein","Ja, mündlich","Ja, schriftlich"]),Pq("daten","Ihre Daten: Name und Adresse",true)]},
    at_dienstnehmer_kuendigung:{ic:"📤",n:"Kündigung durch Arbeitnehmer",cat:"at_arbeit",tier:"einfach",q:[Pq("firma","Arbeitgeber: Name und Adresse",true),Pq("termin","Kündigungstermin (Frist laut Vertrag/KV)",true),Pq("zeugnis","Dienstzeugnis gleich mit anfordern?",false,["Ja","Nein"]),Pq("daten","Ihre Daten: Name und Adresse",true)]},
    at_bildungskarenz:{ic:"🎓",n:"Bildungskarenz vereinbaren",cat:"at_arbeit",tier:"standard",q:[Pq("firma","Arbeitgeber: Name und Adresse",true),Pq("zeitraum","Gewünschter Zeitraum (2 Monate – 1 Jahr)",true),Pq("bildung","Geplante Aus-/Weiterbildung",true),Pq("daten","Ihre Daten: Name und Adresse",true)]},
    at_gewaehrleistung:{ic:"📦",n:"Gewährleistung: mangelhafte Ware (ABGB/VGG)",cat:"at_konsum",tier:"standard",q:[Pq("haendler","Händler: Name und Adresse",true),Pq("kauf","Gekauft am / Rechnung Nr.",true),Pq("produkt","Produkt und Preis",true),Pq("mangel","Mangel beschreiben",true),Pq("wunsch","Ihr Begehren",true,["Reparatur","Austausch","Preisminderung","Vertragsauflösung (Wandlung)"]),Pq("daten","Ihre Daten: Name und Adresse",true)]},
    at_ruecktritt_fernabsatz:{ic:"🛒",n:"Rücktritt Online-Kauf (FAGG, 14 Tage)",cat:"at_konsum",tier:"einfach",q:[Pq("haendler","Händler: Name und Adresse/E-Mail",true),Pq("bestellung","Bestellnummer / Datum",true),Pq("erhalten","Ware erhalten am",true),Pq("ruecksendung","Ware wird retourniert per",false,["Post","Abholung gewünscht"]),Pq("daten","Ihre Daten: Name und Adresse",true)]},
    at_ruecktritt_haustuer:{ic:"🚪",n:"Rücktritt Haustürgeschäft / Werbefahrt",cat:"at_konsum",tier:"einfach",q:[Pq("firma","Unternehmen: Name und Adresse",true),Pq("vertrag","Vertrag/Bestellung vom",true),Pq("produkt","Worum geht es (Produkt/Dienstleistung, Preis)",true),Pq("daten","Ihre Daten: Name und Adresse",true)]},
    at_fluggast:{ic:"✈️",n:"Flugentschädigung (EU 261/2004)",cat:"at_konsum",tier:"standard",q:[Pq("airline","Airline: Name",true),Pq("flug","Flugnummer und Datum",true),Pq("strecke","Strecke (von – nach)",true),Pq("problem","Was ist passiert?",true,["Verspätung über 3 Stunden","Annullierung","Nichtbeförderung (Überbuchung)"]),Pq("buchung","Buchungsnummer",true),Pq("daten","Ihre Daten: Name und Adresse",true)]},
    at_inkasso_einspruch:{ic:"📮",n:"Einspruch gegen Inkassoforderung",cat:"at_konsum",tier:"standard",q:[Pq("inkasso","Inkassobüro: Name und Adresse",true),Pq("az","Aktenzeichen",true),Pq("forderung","Geforderter Betrag und angeblicher Grund",true),Pq("einwand","Ihr Einwand",true,["Forderung unberechtigt","Bereits bezahlt","Betrag zu hoch / überhöhte Spesen","Verjährt"]),Pq("daten","Ihre Daten: Name und Adresse",true)]},
    at_kaufvertrag_privat:{ic:"🛍️",n:"Kaufvertrag privat (bewegliche Sache)",cat:"at_vertraege",tier:"einfach",q:[Pq("rolle","Sie sind",true,["Verkäufer","Käufer"]),Pq("partei","Andere Partei: Name und Adresse",true),Pq("sache","Kaufgegenstand (genau)",true),Pq("preis","Kaufpreis (€) und Zahlungsart",true),Pq("uebergabe","Übergabedatum/-ort",true),Pq("gewaehr","Gewährleistungsausschluss (Privatverkauf)?",false,["Ja","Nein"])]},
    at_leihvertrag:{ic:"🤲",n:"Leihvertrag (unentgeltlich)",cat:"at_vertraege",tier:"einfach",q:[Pq("rolle","Sie sind",true,["Verleiher","Entleiher"]),Pq("partei","Andere Partei: Name und Adresse",true),Pq("sache","Verliehene Sache (Zustand)",true),Pq("dauer","Leihdauer (von – bis)",true),Pq("ersatz","Ersatz bei Beschädigung vereinbaren?",false,["Ja, Zeitwert","Nein"])]},
    at_darlehen_privat:{ic:"💸",n:"Privatdarlehen (Vertrag)",cat:"at_vertraege",tier:"standard",q:[Pq("rolle","Sie sind",true,["Darlehensgeber","Darlehensnehmer"]),Pq("partei","Andere Partei: Name und Adresse",true),Pq("betrag","Darlehensbetrag (€)",true),Pq("rueckzahlung","Rückzahlung (Raten/Termin)",true),Pq("zins","Verzinsung",false,["Zinslos","Mit Zinsen (% p.a.)"])]},
    at_werkvertrag_klein:{ic:"🔨",n:"Werkvertrag (Handwerker/Auftrag)",cat:"at_vertraege",tier:"standard",q:[Pq("rolle","Sie sind",true,["Auftraggeber","Auftragnehmer"]),Pq("partei","Andere Partei: Name und Adresse",true),Pq("werk","Beschreibung des Werks/der Arbeiten",true),Pq("entgelt","Entgelt (€, pauschal oder nach Aufwand)",true),Pq("frist","Fertigstellungstermin",true),Pq("material","Wer stellt das Material?",false,["Auftragnehmer","Auftraggeber"])]},
    at_akteneinsicht:{ic:"🗂️",n:"Akteneinsicht beantragen (§ 17 AVG)",cat:"at_aemter",tier:"einfach",q:[Pq("behoerde","Behörde: Name und Adresse",true),Pq("az","Aktenzeichen / Verfahren",true),Pq("interesse","Ihre Parteistellung / Ihr Interesse",true),Pq("daten","Ihre Daten: Name und Adresse",true)]},
    at_bescheidbeschwerde:{ic:"⚖️",n:"Beschwerde gegen Bescheid (VwGVG, 4 Wochen)",cat:"at_aemter",tier:"komplex",q:[Pq("behoerde","Belangte Behörde: Name und Adresse",true),Pq("bescheid","Bescheid vom / GZ",true),Pq("zugestellt","Zugestellt am (Frist: 4 Wochen!)",true),Pq("inhalt","Was wurde entschieden?",true),Pq("gruende","Warum ist der Bescheid falsch? (in eigenen Worten)",true),Pq("begehren","Ihr Begehren",true,["Aufhebung","Abänderung"]),Pq("daten","Ihre Daten: Name und Adresse",true)]},
    at_ratenzahlung_finanzamt:{ic:"🧾",n:"Ratenzahlung Finanzamt (§ 212 BAO)",cat:"at_aemter",tier:"standard",q:[Pq("finanzamt","Finanzamt Österreich (Dienststelle)",true),Pq("steuernr","Steuernummer / Abgabenkontonummer",true),Pq("betrag","Offener Betrag (€)",true),Pq("rate","Vorgeschlagene Monatsrate (€)",true),Pq("grund","Begründung (erhebliche Härte)",true),Pq("daten","Ihre Daten: Name und Adresse",true)]},
    at_familienbeihilfe:{ic:"🍼",n:"Familienbeihilfe: Antrag/Schreiben",cat:"at_aemter",tier:"einfach",q:[Pq("anliegen","Ihr Anliegen",true,["Erstantrag","Weitergewährung (Studium/Ausbildung)","Rückfrage zu Bescheid"]),Pq("kind","Kind: Name und Geburtsdatum",true),Pq("details","Details (Ausbildung, Zeitraum …)",true),Pq("daten","Ihre Daten: Name, Adresse, SV-Nummer",true)]},
    at_vollmacht:{ic:"📝",n:"Vollmacht (allgemein)",cat:"at_familie",tier:"einfach",q:[Pq("bevoll","Bevollmächtigte Person: Name, Geburtsdatum, Adresse",true),Pq("umfang","Wofür gilt die Vollmacht?",true,["Einzelne Angelegenheit","Behördenwege","Bankgeschäfte","Umfassend"]),Pq("details","Genauere Beschreibung",true),Pq("befristung","Befristung",false,["Unbefristet","Bis Datum"]),Pq("daten","Ihre Daten: Name, Geburtsdatum, Adresse",true)]},
    at_vorsorgevollmacht:{ic:"🛡️",n:"Vorsorgevollmacht (Entwurf)",cat:"at_familie",tier:"komplex",q:[Pq("bevoll","Vorsorgebevollmächtigte Person: Name, Geburtsdatum, Adresse",true),Pq("bereiche","Umfasste Bereiche",true,["Vermögen","Gesundheit","Wohnort/Pflege","Alle Bereiche"]),Pq("wuensche","Besondere Wünsche/Grenzen",false),Pq("daten","Ihre Daten: Name, Geburtsdatum, Adresse",true),Pq("hinweis","Hinweis: Errichtung nur vor Notar, Rechtsanwalt oder Erwachsenenschutzverein (Eintragung ÖZVV)",false)]},
    at_patientenverfuegung:{ic:"🏥",n:"Patientenverfügung (PatVG, Entwurf)",cat:"at_familie",tier:"komplex",q:[Pq("ablehnung","Welche Behandlungen lehnen Sie ab?",true),Pq("situation","Für welche Situationen (z. B. unumkehrbare Bewusstlosigkeit)?",true),Pq("werte","Ihre Wertvorstellungen (optional)",false),Pq("daten","Ihre Daten: Name, Geburtsdatum, Adresse",true),Pq("hinweis","Hinweis: Verbindlich nur mit ärztlicher Aufklärung + Notar/RA/Patientenvertretung; 8 Jahre gültig",false)]},
    at_unterhalt_mahnung:{ic:"👨‍👧",n:"Unterhalt einmahnen",cat:"at_familie",tier:"standard",q:[Pq("pflichtiger","Unterhaltspflichtige Person: Name und Adresse",true),Pq("titel","Unterhaltstitel (Beschluss/Vergleich vom)",true),Pq("rueckstand","Offener Rückstand (Monate, Betrag)",true),Pq("frist","Zahlungsfrist (z. B. 14 Tage)",true),Pq("daten","Ihre Daten: Name und Adresse",true)]},
    at_kfz_kauf:{ic:"🚗",n:"Kfz-Kaufvertrag (privat)",cat:"at_kfz",tier:"standard",q:[Pq("rolle","Sie sind",true,["Verkäufer","Käufer"]),Pq("partei","Andere Partei: Name und Adresse",true),Pq("fahrzeug","Marke, Modell, FIN (Fahrgestellnummer)",true),Pq("ez","Erstzulassung und Kilometerstand",true),Pq("preis","Kaufpreis (€) und Zahlungsart",true),Pq("pickerl","§-57a-Begutachtung (Pickerl) gültig bis",false),Pq("maengel","Bekannte Mängel",false)]},
    at_strafverfuegung_einspruch:{ic:"🚦",n:"Einspruch gegen Strafverfügung (§ 49 VStG, 2 Wochen)",cat:"at_kfz",tier:"standard",q:[Pq("behoerde","Behörde (laut Strafverfügung)",true),Pq("gz","Geschäftszahl",true),Pq("zugestellt","Zugestellt am (Frist: 2 Wochen!)",true),Pq("vorwurf","Vorgeworfene Übertretung",true),Pq("einwand","Ihr Einwand in eigenen Worten",true),Pq("daten","Ihre Daten: Name und Adresse",true)]},
    at_lenkerauskunft:{ic:"🪪",n:"Lenkerauskunft beantworten (§ 103 KFG)",cat:"at_kfz",tier:"einfach",q:[Pq("behoerde","Behörde: Name und Adresse",true),Pq("gz","Geschäftszahl",true),Pq("kennzeichen","Kennzeichen",true),Pq("lenker","Wer hat gelenkt? (Name, Geburtsdatum, Adresse)",true),Pq("daten","Ihre Daten (Zulassungsbesitzer): Name und Adresse",true)]},
    at_kfz_schadenmeldung:{ic:"💥",n:"Schadenmeldung an Kfz-Versicherung",cat:"at_kfz",tier:"einfach",q:[Pq("versicherung","Versicherung: Name und Adresse",true),Pq("polizze","Polizzennummer",true),Pq("unfall","Unfall: Datum, Ort, Hergang",true),Pq("schaden","Schaden am Fahrzeug",true),Pq("gegner","Unfallgegner (falls vorhanden: Name, Kennzeichen, Versicherung)",false),Pq("daten","Ihre Daten: Name und Adresse",true)]},
    at_sv_einspruch:{ic:"🏥",n:"Einspruch: Bescheid ÖGK/PVA (Sozialversicherung)",cat:"at_gesundheit",tier:"komplex",q:[Pq("traeger","Versicherungsträger",true,["ÖGK","PVA","AUVA","SVS"]),Pq("bescheid","Bescheid vom / GZ",true),Pq("zugestellt","Zugestellt am",true),Pq("inhalt","Was wurde entschieden?",true),Pq("gruende","Warum ist die Entscheidung falsch?",true),Pq("daten","Ihre Daten: Name, Adresse, SV-Nummer",true)]},
    at_pflegegeld:{ic:"🧓",n:"Pflegegeld beantragen/erhöhen (BPGG)",cat:"at_gesundheit",tier:"standard",q:[Pq("anliegen","Ihr Anliegen",true,["Erstantrag","Erhöhung (Verschlechterung)"]),Pq("person","Pflegebedürftige Person: Name, Geburtsdatum, SV-Nummer",true),Pq("bedarf","Pflegebedarf beschreiben (Hilfe wobei, wie oft)",true),Pq("daten","Antragsteller: Name und Adresse",true)]},
    at_wahlarzt_rueckerstattung:{ic:"🩺",n:"Wahlarzt-Kostenrückerstattung (ÖGK)",cat:"at_gesundheit",tier:"einfach",q:[Pq("behandlung","Behandlung: Arzt, Datum, Leistung",true),Pq("betrag","Bezahlter Betrag (€, Honorarnote beilegen)",true),Pq("iban","Ihre IBAN",true),Pq("daten","Ihre Daten: Name, Adresse, SV-Nummer",true)]},
    at_konto_kuendigung:{ic:"🏦",n:"Bankkonto kündigen / Kontowechsel (VZKG)",cat:"at_finanzen",tier:"einfach",q:[Pq("bank","Bank: Name und Adresse",true),Pq("iban","IBAN des zu kündigenden Kontos",true),Pq("termin","Kündigungstermin",false,["Sofort","Zum Datum"]),Pq("restsaldo","Restsaldo überweisen auf (IBAN)",true),Pq("wechselhilfe","Kontowechselhilfe (VZKG) gewünscht?",false,["Ja","Nein"]),Pq("daten","Ihre Daten: Name und Adresse",true)]},
    at_kredit_rueckzahlung:{ic:"💳",n:"Vorzeitige Kreditrückzahlung (§ 16 VKrG)",cat:"at_finanzen",tier:"standard",q:[Pq("bank","Kreditgeber: Name und Adresse",true),Pq("vertrag","Kreditvertrag Nr. vom",true),Pq("art","Rückzahlung",true,["Vollständig","Teilweise (Betrag)"]),Pq("termin","Gewünschter Termin",true),Pq("daten","Ihre Daten: Name und Adresse",true)]},
    at_spesen_rueckforderung:{ic:"🧾",n:"Unzulässige Bankspesen zurückfordern",cat:"at_finanzen",tier:"standard",q:[Pq("bank","Bank: Name und Adresse",true),Pq("konto","IBAN / Kontonummer",true),Pq("spesen","Beanstandete Spesen (Art, Zeitraum, Beträge)",true),Pq("frist","Frist zur Rückerstattung (z. B. 14 Tage)",true),Pq("daten","Ihre Daten: Name und Adresse",true)]},
JS;
$o2 = "var CCODE=\"AT\", DOCWORD=\"Dokumente\";\n\n  var D={";
$n2 = "var CCODE=\"AT\", DOCWORD=\"Dokumente\";\n\n  var D={\n".$atDocs;
$c=0; $src=str_replace($o2,$n2,$src,$c);
echo ($c===1?"  ✓ [2] AT +38 belge\n":"  ✗ [2] AT D anchor ($c)\n"); if($c!==1)$fail[]=2;

/* ═══ [3] IT: kategoriler + X_ORDER ═══ */
$o3 = "    it_pubblica:{n:\"Pubblica Amministrazione\",ic:\"🏛️\"}\n  };\n  var X_ORDER=[\"it_disdette\",\"it_casa\",\"it_lavoro\",\"it_consumo\",\"it_contratti\",\"it_pubblica\"];";
$n3 = "    it_pubblica:{n:\"Pubblica Amministrazione\",ic:\"🏛️\"},\n"
    . "    it_famiglia:{n:\"Famiglia e Tutele\",ic:\"👪\"},\n"
    . "    it_auto:{n:\"Auto e Trasporti\",ic:\"🚗\"},\n"
    . "    it_salute:{n:\"Salute e Previdenza\",ic:\"🏥\"},\n"
    . "    it_fisco:{n:\"Banche e Finanze\",ic:\"💶\"}\n  };\n"
    . "  var X_ORDER=[\"it_disdette\",\"it_casa\",\"it_lavoro\",\"it_consumo\",\"it_contratti\",\"it_pubblica\",\"it_famiglia\",\"it_auto\",\"it_salute\",\"it_fisco\"]; /*CH_WIDECAT_ATIT*/";
$c=0; $src=str_replace($o3,$n3,$src,$c);
echo ($c===1?"  ✓ [3] IT +4 kategori\n":"  ✗ [3] IT XC anchor ($c)\n"); if($c!==1)$fail[]=3;

/* ═══ [4] IT: +38 belge ═══ */
$itDocs = <<<'JS'
    /* CH_WIDECAT_ATIT — catalogo ampio */
    it_disdetta_luce_gas:{ic:"⚡",n:"Disdetta / cambio fornitore luce e gas",cat:"it_disdette",tier:"einfach",q:[Pq("fornitore","Fornitore: nome e indirizzo",true),Pq("codice","Codice cliente / POD (luce) o PDR (gas)",true),Pq("decorrenza","Decorrenza richiesta",false,["Prima data utile","Data specifica"]),Pq("dati","I suoi dati: nome e indirizzo",true)]},
    it_disdetta_abbonamento:{ic:"📰",n:"Disdetta abbonamento (rivista/servizio)",cat:"it_disdette",tier:"einfach",q:[Pq("azienda","Azienda: nome e indirizzo",true),Pq("numero","Numero abbonamento/cliente",true),Pq("decorrenza","Decorrenza della disdetta",true),Pq("dati","I suoi dati: nome e indirizzo",true)]},
    it_recesso_associazione:{ic:"🤝",n:"Recesso da associazione (art. 24 c.c.)",cat:"it_disdette",tier:"einfach",q:[Pq("associazione","Associazione: nome e indirizzo",true),Pq("tessera","Numero tessera (se presente)",false),Pq("decorrenza","Decorrenza (secondo statuto, spesso fine anno)",true),Pq("dati","I suoi dati: nome e indirizzo",true)]},
    it_revoca_sepa:{ic:"🏦",n:"Revoca addebito diretto SEPA",cat:"it_disdette",tier:"einfach",q:[Pq("beneficiario","Beneficiario: nome e indirizzo",true),Pq("mandato","Riferimento mandato / numero cliente",true),Pq("banca","Comunicare anche alla banca?",false,["Sì","No"]),Pq("dati","I suoi dati: nome e indirizzo",true)]},
    it_riduzione_canone:{ic:"📉",n:"Riduzione canone per vizi (art. 1578 c.c.)",cat:"it_casa",tier:"standard",q:[Pq("locatore","Locatore: nome e indirizzo",true),Pq("immobile","Indirizzo dell'immobile",true),Pq("vizio","Vizio/difetto (da quando, entità)",true),Pq("segnalato","Già segnalato?",true,["Sì, per iscritto","Sì, a voce","No"]),Pq("richiesta","Riduzione richiesta (% o €)",false),Pq("dati","I suoi dati: nome",true)]},
    it_segnalazione_vizi:{ic:"🔧",n:"Segnalazione vizi/danni al locatore",cat:"it_casa",tier:"einfach",q:[Pq("locatore","Locatore: nome e indirizzo",true),Pq("immobile","Indirizzo dell'immobile",true),Pq("vizio","Descrizione del problema e conseguenze",true),Pq("termine","Termine per l'intervento (es. 15 giorni)",true),Pq("dati","I suoi dati: nome",true)]},
    it_restituzione_deposito:{ic:"💰",n:"Restituzione deposito cauzionale (L.392/1978)",cat:"it_casa",tier:"einfach",q:[Pq("locatore","Locatore: nome e indirizzo",true),Pq("immobile","Indirizzo dell'immobile (ex) locato",true),Pq("rilascio","Data di rilascio/consegna chiavi",true),Pq("deposito","Importo del deposito (€) — con interessi legali",true),Pq("iban","Il suo IBAN per il bonifico",true),Pq("dati","I suoi dati: nome e nuovo indirizzo",true)]},
    it_disdetta_locazione:{ic:"🏠",n:"Disdetta contratto di locazione (L.431/1998)",cat:"it_casa",tier:"einfach",q:[Pq("locatore","Locatore: nome e indirizzo",true),Pq("immobile","Indirizzo dell'immobile",true),Pq("decorrenza","Data di rilascio (preavviso di regola 6 mesi)",true),Pq("motivo","Gravi motivi (se recesso anticipato)",false),Pq("dati","I suoi dati: nome",true)]},
    it_verbale_consegna:{ic:"📋",n:"Verbale di consegna immobile",cat:"it_casa",tier:"einfach",q:[Pq("tipo","Occasione",true,["Ingresso","Rilascio"]),Pq("immobile","Indirizzo dell'immobile",true),Pq("stato","Stato dei locali / difetti riscontrati",true),Pq("contatori","Letture contatori (luce, gas, acqua)",false),Pq("chiavi","Chiavi consegnate (numero)",false),Pq("parti","Nomi delle due parti",true)]},
    it_reclamo_condominio:{ic:"🏢",n:"Reclamo all'amministratore di condominio",cat:"it_casa",tier:"einfach",q:[Pq("amministratore","Amministratore: nome e indirizzo",true),Pq("condominio","Condominio (indirizzo)",true),Pq("problema","Problema (rumori, parti comuni, spese …)",true),Pq("richiesta","Cosa chiede",true),Pq("dati","I suoi dati: nome e unità",true)]},
    it_dimissioni:{ic:"📤",n:"Lettera di dimissioni",cat:"it_lavoro",tier:"einfach",q:[Pq("datore","Datore di lavoro: nome e indirizzo",true),Pq("decorrenza","Ultimo giorno di lavoro (rispettare il preavviso CCNL)",true),Pq("motivo","Motivo (facoltativo)",false),Pq("dati","I suoi dati: nome e indirizzo",true),Pq("nota","Nota: le dimissioni vanno confermate anche in via telematica (portale ministeriale/patronato)",false)]},
    it_congedo_parentale:{ic:"👶",n:"Congedo parentale (D.Lgs 151/2001)",cat:"it_lavoro",tier:"standard",q:[Pq("datore","Datore di lavoro: nome e indirizzo",true),Pq("figlio","Figlio: data di nascita",true),Pq("periodo","Periodo richiesto (dal – al)",true),Pq("preavviso","Data della comunicazione (preavviso di regola 5 giorni)",false),Pq("dati","I suoi dati: nome",true)]},
    it_risposta_disciplinare:{ic:"⚖️",n:"Risposta a contestazione disciplinare (art. 7 St. Lav.)",cat:"it_lavoro",tier:"komplex",q:[Pq("datore","Datore di lavoro: nome e indirizzo",true),Pq("contestazione","Contestazione del (data) — termine 5 giorni!",true),Pq("addebito","Fatto contestato",true),Pq("difesa","La sua difesa con parole sue",true),Pq("audizione","Chiedere audizione orale?",false,["Sì","No"]),Pq("dati","I suoi dati: nome",true)]},
    it_sollecito_stipendio:{ic:"💶",n:"Sollecito retribuzioni arretrate",cat:"it_lavoro",tier:"standard",q:[Pq("datore","Datore di lavoro: nome e indirizzo",true),Pq("arretrati","Somme dovute (mensilità, importi)",true),Pq("termine","Termine di pagamento (es. 15 giorni)",true),Pq("dati","I suoi dati: nome e indirizzo",true)]},
    it_attestato_servizio:{ic:"📜",n:"Richiesta attestato di servizio",cat:"it_lavoro",tier:"einfach",q:[Pq("datore","Datore di lavoro: nome e indirizzo",true),Pq("periodo","Periodo di lavoro (dal – al)",true),Pq("mansione","Mansione / inquadramento",true),Pq("dati","I suoi dati: nome e indirizzo",true)]},
    it_impugnazione_licenziamento:{ic:"🚫",n:"Impugnazione licenziamento (60 giorni)",cat:"it_lavoro",tier:"komplex",q:[Pq("datore","Datore di lavoro: nome e indirizzo",true),Pq("licenziamento","Licenziamento comunicato il (termine 60 giorni!)",true),Pq("motivo","Motivo indicato dal datore",true),Pq("contestazione","Perché lo ritiene illegittimo (parole sue)",true),Pq("dati","I suoi dati: nome e indirizzo",true)]},
    it_garanzia_legale:{ic:"📦",n:"Garanzia legale di conformità (Cod. Consumo)",cat:"it_consumo",tier:"standard",q:[Pq("venditore","Venditore: nome e indirizzo",true),Pq("acquisto","Acquistato il / scontrino n.",true),Pq("prodotto","Prodotto e prezzo",true),Pq("difetto","Difetto riscontrato",true),Pq("rimedio","Rimedio richiesto",true,["Riparazione","Sostituzione","Riduzione del prezzo","Risoluzione del contratto"]),Pq("dati","I suoi dati: nome e indirizzo",true)]},
    it_recesso_14giorni:{ic:"🛒",n:"Diritto di recesso 14 giorni (acquisto online)",cat:"it_consumo",tier:"einfach",q:[Pq("venditore","Venditore: nome e indirizzo/e-mail",true),Pq("ordine","Numero ordine / data",true),Pq("ricevuto","Merce ricevuta il",true),Pq("reso","Restituzione tramite",false,["Spedizione","Ritiro richiesto"]),Pq("dati","I suoi dati: nome e indirizzo",true)]},
    it_reclamo_telefonia:{ic:"📱",n:"Reclamo operatore telefonico (+ conciliazione AGCOM)",cat:"it_consumo",tier:"standard",q:[Pq("operatore","Operatore: nome e indirizzo",true),Pq("utenza","Numero utenza / codice cliente",true),Pq("problema","Problema (fatturazione, servizi non richiesti, guasti …)",true),Pq("richiesta","Cosa chiede (rimborso, storno, attivazione …)",true),Pq("dati","I suoi dati: nome e indirizzo",true)]},
    it_rimborso_volo:{ic:"✈️",n:"Compensazione volo (Reg. CE 261/2004)",cat:"it_consumo",tier:"standard",q:[Pq("compagnia","Compagnia aerea: nome",true),Pq("volo","Numero volo e data",true),Pq("tratta","Tratta (da – a)",true),Pq("problema","Cosa è successo?",true,["Ritardo oltre 3 ore","Cancellazione","Negato imbarco (overbooking)"]),Pq("prenotazione","Codice prenotazione",true),Pq("dati","I suoi dati: nome e indirizzo",true)]},
    it_contestazione_recupero:{ic:"📮",n:"Contestazione società di recupero crediti",cat:"it_consumo",tier:"standard",q:[Pq("societa","Società: nome e indirizzo",true),Pq("pratica","Riferimento pratica",true),Pq("credito","Importo richiesto e presunta origine",true),Pq("eccezione","La sua eccezione",true,["Credito inesistente","Già pagato","Importo/spese eccessivi","Prescritto"]),Pq("dati","I suoi dati: nome e indirizzo",true)]},
    it_compravendita_privati:{ic:"🛍️",n:"Compravendita tra privati (bene mobile)",cat:"it_contratti",tier:"einfach",q:[Pq("ruolo","Lei è",true,["Venditore","Acquirente"]),Pq("controparte","Controparte: nome e indirizzo",true),Pq("bene","Bene venduto (descrizione precisa)",true),Pq("prezzo","Prezzo (€) e modalità di pagamento",true),Pq("consegna","Data/luogo di consegna",true),Pq("garanzia","Esclusione garanzia (vendita tra privati)?",false,["Sì","No"])]},
    it_comodato:{ic:"🤲",n:"Contratto di comodato d'uso (art. 1803 c.c.)",cat:"it_contratti",tier:"einfach",q:[Pq("ruolo","Lei è",true,["Comodante","Comodatario"]),Pq("controparte","Controparte: nome e indirizzo",true),Pq("bene","Bene concesso (stato)",true),Pq("durata","Durata (dal – al / precario)",true),Pq("spese","Spese ordinarie a carico del comodatario",false,["Sì","No"])]},
    it_prestito_privato:{ic:"💸",n:"Prestito tra privati (scrittura privata)",cat:"it_contratti",tier:"standard",q:[Pq("ruolo","Lei è",true,["Mutuante (chi presta)","Mutuatario (chi riceve)"]),Pq("controparte","Controparte: nome e indirizzo",true),Pq("importo","Importo (€)",true),Pq("restituzione","Restituzione (rate/scadenza)",true),Pq("interessi","Interessi",false,["Senza interessi","Con interessi (% annuo)"])]},
    it_contratto_opera:{ic:"🔨",n:"Contratto d'opera (artigiano, art. 2222 c.c.)",cat:"it_contratti",tier:"standard",q:[Pq("ruolo","Lei è",true,["Committente","Prestatore d'opera"]),Pq("controparte","Controparte: nome e indirizzo",true),Pq("opera","Descrizione dei lavori",true),Pq("compenso","Compenso (€, a corpo o a misura)",true),Pq("termine","Termine di consegna",true),Pq("materiali","Chi fornisce i materiali?",false,["Prestatore","Committente"])]},
    it_accesso_atti:{ic:"🗂️",n:"Accesso agli atti (L. 241/1990)",cat:"it_pubblica",tier:"einfach",q:[Pq("ente","Ente/Ufficio: nome e indirizzo",true),Pq("atti","Documenti richiesti (più precisi possibile)",true),Pq("interesse","Suo interesse diretto e concreto",true),Pq("modalita","Modalità",false,["Visione","Copia semplice","Copia conforme"]),Pq("dati","I suoi dati: nome e indirizzo",true)]},
    it_autocertificazione:{ic:"📄",n:"Autocertificazione (DPR 445/2000)",cat:"it_pubblica",tier:"einfach",q:[Pq("destinatario","Destinatario (ente/ufficio)",true),Pq("oggetto","Cosa deve autocertificare?",true,["Residenza","Stato di famiglia","Nascita","Titolo di studio","Stato civile","Altro (descrivere)"]),Pq("dettagli","Dettagli da dichiarare",true),Pq("dati","I suoi dati: nome, luogo/data di nascita, residenza",true)]},
    it_diffida_pa:{ic:"⚖️",n:"Diffida ad adempiere alla P.A.",cat:"it_pubblica",tier:"komplex",q:[Pq("ente","Ente: nome e indirizzo",true),Pq("pratica","Pratica/istanza del (riferimenti)",true),Pq("inadempimento","Cosa non è stato fatto (silenzio, ritardo …)",true),Pq("termine","Termine assegnato (es. 30 giorni)",true),Pq("dati","I suoi dati: nome e indirizzo",true)]},
    it_rateizzazione_riscossione:{ic:"🧾",n:"Rateizzazione Agenzia Entrate-Riscossione",cat:"it_pubblica",tier:"standard",q:[Pq("cartella","Cartella/avviso n. del",true),Pq("importo","Importo dovuto (€)",true),Pq("rate","Numero rate proposte (fino a 72/120)",true),Pq("difficolta","Situazione di difficoltà (breve descrizione)",true),Pq("dati","I suoi dati: nome, indirizzo, codice fiscale",true)]},
    it_delega:{ic:"📝",n:"Delega / procura semplice",cat:"it_famiglia",tier:"einfach",q:[Pq("delegato","Persona delegata: nome, data di nascita, indirizzo",true),Pq("oggetto","Per cosa vale la delega?",true,["Singola pratica","Uffici pubblici","Ritiro documenti","Ampia"]),Pq("dettagli","Descrizione più precisa",true),Pq("durata","Durata",false,["Illimitata","Fino a data"]),Pq("dati","I suoi dati: nome, data di nascita, indirizzo",true)]},
    it_testamento_olografo:{ic:"📜",n:"Testamento olografo (bozza, art. 602 c.c.)",cat:"it_famiglia",tier:"komplex",q:[Pq("beneficiari","Eredi/beneficiari e quote/beni",true),Pq("legati","Lasciti particolari (facoltativo)",false),Pq("esecutore","Esecutore testamentario (facoltativo)",false),Pq("dati","I suoi dati: nome, data di nascita",true),Pq("nota","Nota: valido SOLO se scritto interamente a mano, datato e firmato; rispettare le quote dei legittimari",false)]},
    it_sollecito_mantenimento:{ic:"👨‍👧",n:"Sollecito assegno di mantenimento",cat:"it_famiglia",tier:"standard",q:[Pq("obbligato","Persona obbligata: nome e indirizzo",true),Pq("titolo","Titolo (sentenza/accordo del)",true),Pq("arretrati","Arretrati (mesi, importo)",true),Pq("termine","Termine di pagamento (es. 15 giorni)",true),Pq("dati","I suoi dati: nome e indirizzo",true)]},
    it_dat:{ic:"🏥",n:"DAT — Disposizioni anticipate (L. 219/2017)",cat:"it_famiglia",tier:"komplex",q:[Pq("volonta","Trattamenti che rifiuta/accetta",true),Pq("situazioni","Per quali situazioni cliniche",true),Pq("fiduciario","Fiduciario: nome e contatti (consigliato)",false),Pq("dati","I suoi dati: nome, data di nascita, residenza",true),Pq("nota","Nota: consegna all'ufficiale di stato civile del Comune o tramite notaio",false)]},
    it_vendita_auto:{ic:"🚗",n:"Vendita auto tra privati",cat:"it_auto",tier:"standard",q:[Pq("ruolo","Lei è",true,["Venditore","Acquirente"]),Pq("controparte","Controparte: nome e indirizzo",true),Pq("veicolo","Marca, modello, telaio (VIN), targa",true),Pq("km","Immatricolazione e chilometraggio",true),Pq("prezzo","Prezzo (€) e pagamento",true),Pq("revisione","Revisione valida fino al",false),Pq("difetti","Difetti noti",false)]},
    it_ricorso_multa:{ic:"🚦",n:"Ricorso contro multa (Prefetto 60gg / GdP 30gg)",cat:"it_auto",tier:"komplex",q:[Pq("via","Ricorso al",true,["Prefetto (60 giorni, gratuito)","Giudice di Pace (30 giorni)"]),Pq("verbale","Verbale n. del (organo accertatore)",true),Pq("notificato","Notificato il",true),Pq("violazione","Violazione contestata",true),Pq("motivi","Motivi del ricorso con parole sue",true),Pq("dati","I suoi dati: nome e indirizzo",true)]},
    it_denuncia_sinistro:{ic:"💥",n:"Denuncia sinistro all'assicurazione",cat:"it_auto",tier:"einfach",q:[Pq("assicurazione","Assicurazione: nome e indirizzo",true),Pq("polizza","Numero polizza",true),Pq("sinistro","Sinistro: data, luogo, dinamica",true),Pq("danni","Danni riportati",true),Pq("controparte","Controparte (nome, targa, assicurazione)",false),Pq("dati","I suoi dati: nome e indirizzo",true)]},
    it_risarcimento_danni:{ic:"🧾",n:"Richiesta risarcimento danni (art. 2043 c.c.)",cat:"it_auto",tier:"standard",q:[Pq("responsabile","Responsabile/assicurazione: nome e indirizzo",true),Pq("evento","Evento dannoso: data, luogo, dinamica",true),Pq("danni","Danni subiti (documentati, importi)",true),Pq("termine","Termine per il riscontro (es. 30 giorni)",true),Pq("dati","I suoi dati: nome e indirizzo",true)]},
    it_ricorso_inps:{ic:"🏥",n:"Ricorso amministrativo INPS",cat:"it_salute",tier:"komplex",q:[Pq("provvedimento","Provvedimento INPS del (riferimenti)",true),Pq("materia","Materia",true,["Pensione","Invalidità","NASpI/disoccupazione","Assegno unico","Altro"]),Pq("motivi","Perché il provvedimento è errato",true),Pq("dati","I suoi dati: nome, indirizzo, codice fiscale",true)]},
    it_domanda_invalidita:{ic:"🧓",n:"Invalidità civile / L. 104: lettera di sollecito",cat:"it_salute",tier:"standard",q:[Pq("pratica","Domanda presentata il / numero pratica",true),Pq("stato","Cosa attende (visita, verbale, esito)",true),Pq("condizione","Condizione di salute (in breve)",true),Pq("dati","I suoi dati: nome, indirizzo, codice fiscale",true)]},
    it_rimborso_sanitario:{ic:"🩺",n:"Richiesta rimborso spese sanitarie",cat:"it_salute",tier:"einfach",q:[Pq("ente","Ente/assicurazione: nome e indirizzo",true),Pq("prestazione","Prestazione: medico, data, tipo",true),Pq("importo","Importo pagato (€, allegare fattura)",true),Pq("iban","Il suo IBAN",true),Pq("dati","I suoi dati: nome e indirizzo",true)]},
    it_chiusura_conto:{ic:"🏦",n:"Chiusura conto corrente",cat:"it_fisco",tier:"einfach",q:[Pq("banca","Banca: nome e indirizzo",true),Pq("iban","IBAN del conto da chiudere",true),Pq("saldo","Saldo residuo da bonificare su (IBAN)",true),Pq("decorrenza","Decorrenza",false,["Immediata","Alla data"]),Pq("dati","I suoi dati: nome e indirizzo",true)]},
    it_estinzione_anticipata:{ic:"💳",n:"Estinzione anticipata finanziamento (art. 125-sexies TUB)",cat:"it_fisco",tier:"standard",q:[Pq("finanziaria","Banca/finanziaria: nome e indirizzo",true),Pq("contratto","Contratto n. del",true),Pq("tipo","Estinzione",true,["Totale","Parziale (importo)"]),Pq("conteggio","Chiedere conteggio estintivo con riduzione dei costi",false,["Sì","No"]),Pq("dati","I suoi dati: nome e indirizzo",true)]},
    it_contestazione_addebito:{ic:"🧾",n:"Contestazione addebito non autorizzato (carta/conto)",cat:"it_fisco",tier:"standard",q:[Pq("banca","Banca/emittente: nome e indirizzo",true),Pq("operazione","Operazione contestata (data, importo, esercente)",true),Pq("motivo","Motivo",true,["Mai autorizzata","Importo errato","Doppio addebito","Frode/phishing"]),Pq("blocco","Carta già bloccata?",false,["Sì","No"]),Pq("dati","I suoi dati: nome e indirizzo",true)]},
JS;
$o4 = "var CCODE=\"IT\", DOCWORD=\"documenti\";\n\n  var D={";
$n4 = "var CCODE=\"IT\", DOCWORD=\"documenti\";\n\n  var D={\n".$itDocs;
$c=0; $src=str_replace($o4,$n4,$src,$c);
echo ($c===1?"  ✓ [4] IT +38 belge\n":"  ✗ [4] IT D anchor ($c)\n"); if($c!==1)$fail[]=4;

if ($fail) { echo "\nHATA: adimlar eslesmedi: ".implode(', ',$fail)." — index.php DEGISTIRILMEDI.\n"; exit; }

$tmp = tempnam(sys_get_temp_dir(),'wc').'.php';
file_put_contents($tmp,$src);
$lo=[];$rc=0; exec('php -l '.escapeshellarg($tmp).' 2>&1',$lo,$rc); @unlink($tmp);
if ($rc!==0) { echo "\nLINT HATASI — index.php degistirilmedi:\n  ".implode("\n  ",$lo)."\n"; exit; }
file_put_contents($file.'.bak-widecat1-'.date('Ymd-His'), @file_get_contents($file));
file_put_contents($file,$src);
$nAT = preg_match_all('/\bat_[a-z0-9_]+:\{ic:/', $src, $m);
$nIT = preg_match_all('/\bit_[a-z0-9_]+:\{ic:/', $src, $m);
echo "\n✓ CH_WIDECAT_ATIT uygulandi. Yeni toplam: AT=$nAT, IT=$nIT belge (+4'er kategori).\n";
