<?php
/** ChatHelp — apply-es-expand-more (CH_ES_EXPAND_MORE) — ES katalog genisletme
 *  Workflow ile uretildi: +18 belge, 4 kategori. Deferred injection.
 *  KULLANIM: pull-updates.php?files=apply-es-expand-more.php */
header('Content-Type: text/plain; charset=UTF-8');
error_reporting(E_ERROR | E_PARSE);
echo "apply-es-expand-more BASLADI OK (PHP ".PHP_VERSION.")\n\n";
$file = __DIR__.'/index.php';
$src = @file_get_contents($file);
if ($src===false) exit("index.php okunamadi\n");
if (strpos($src,'CH_ES_EXPAND_MORE')!==false) exit("Zaten ekli (CH_ES_EXPAND_MORE).\n");
$anchor="function getDocPrice(dk){ return DOC_TIER[dk]||'standard'; }";
if (strpos($src,$anchor)===false) exit("HATA: anchor (getDocPrice) yok.\n");
$js = <<<'CHJS'

/* CH_ES_EXPAND_MORE — ES katalog genisletme (workflow, deferred) */
try{(function(){
  function Pe(k,l,r,o){var x={k:k,l:l,r:!!r};if(o)x.opts=o;return x;}
  var NEWCATS={
    "esx_herencias":{n:"Herencias y Sucesiones",ic:"📜"},
    "esx_comunidad":{n:"Comunidad de Propietarios y Vivienda",ic:"🏢"},
    "esx_autonomos":{n:"Autónomos y Actividad Económica",ic:"💼"},
    "esx_derechos_especiales":{n:"Derechos y Protecciones Especiales",ic:"⚖️"}
  };
  var E={
    "esx_herencias_aceptacion_beneficio_inventario":{ic:"🧾",n:"Aceptación de herencia a beneficio de inventario",cat:"esx_herencias",tier:"komplex",q:[Pe("causante_nombre","Nombre completo del causante (fallecido)",true),Pe("fecha_fallecimiento","Fecha de fallecimiento",true),Pe("heredero_nombre","Nombre completo del heredero solicitante",true),Pe("parentesco","Relación de parentesco con el causante",true,["Cónyuge","Hijo/a","Nieto/a","Hermano/a","Otro pariente","Sin parentesco (heredero testamentario)"]),Pe("motivo_deudas","¿Existen indicios de deudas del causante superiores al activo conocido?",true,["Sí","No","No lo sé con certeza"]),Pe("notaria","Notaría donde se tramitará la aceptación",false)]},
    "esx_herencias_renuncia":{ic:"✋",n:"Escrito de renuncia a la herencia",cat:"esx_herencias",tier:"standard",q:[Pe("causante_nombre","Nombre completo del causante (fallecido)",true),Pe("fecha_fallecimiento","Fecha de fallecimiento",true),Pe("renunciante_nombre","Nombre completo de quien renuncia",true),Pe("motivo_renuncia","Motivo principal de la renuncia",true,["Herencia con más deudas que bienes","Conflicto familiar","Renuncia a favor de otro heredero","Otro motivo"]),Pe("beneficiario_renuncia","¿Se renuncia a favor de una persona concreta?",false,["Sí, a favor de un heredero determinado","No, renuncia pura y simple"]),Pe("notaria_prevista","Notaría prevista para formalizar la renuncia",false)]},
    "esx_herencias_reclamacion_legitima":{ic:"⚖️",n:"Reclamación de legítima a coherederos",cat:"esx_herencias",tier:"standard",q:[Pe("causante_nombre","Nombre completo del causante",true),Pe("fecha_fallecimiento","Fecha de fallecimiento del causante",true),Pe("reclamante_nombre","Nombre completo de quien reclama",true),Pe("parentesco_reclamante","Parentesco con el causante",true,["Hijo/a","Nieto/a (por representación)","Padre/Madre","Cónyuge viudo/a"]),Pe("motivo_reclamacion","Motivo de la reclamación",true,["No se ha incluido en la partición","Legítima reducida o no respetada","Bienes ocultados por otro heredero","Otro motivo"]),Pe("bienes_afectados","Descripción de los bienes de la herencia afectados",true),Pe("destinatario","Nombre del coheredero o albacea destinatario",true)]},
    "esx_herencias_particion_amistosa":{ic:"🤝",n:"Acuerdo de partición amistosa de herencia",cat:"esx_herencias",tier:"komplex",q:[Pe("causante_nombre","Nombre completo del causante",true),Pe("fecha_fallecimiento","Fecha de fallecimiento",true),Pe("numero_herederos","Número total de herederos",true),Pe("existe_testamento","¿Existe testamento?",true,["Sí","No, sucesión intestada"]),Pe("bienes_a_repartir","Relación de bienes y deudas a repartir",true),Pe("criterio_reparto","Criterio de reparto acordado entre los herederos",true,["A partes iguales","Según lo dispuesto en el testamento","Con compensaciones económicas (excesos de adjudicación)","Otro criterio"])]},
    "esx_herencias_declaracion_herederos_abintestato":{ic:"📋",n:"Solicitud de declaración de herederos abintestato",cat:"esx_herencias",tier:"standard",q:[Pe("causante_nombre","Nombre completo del causante",true),Pe("fecha_fallecimiento","Fecha y lugar de fallecimiento",true),Pe("solicitante_nombre","Nombre completo del solicitante",true),Pe("parentesco_solicitante","Parentesco del solicitante con el causante",true,["Cónyuge","Hijo/a","Padre/Madre","Hermano/a","Otro pariente"]),Pe("otros_posibles_herederos","¿Hay otros posibles herederos conocidos?",false),Pe("notaria_competente","Notaría del último domicilio del causante",false)]},
    "esx_comunidad_impugnacion_acuerdo_junta":{ic:"📑",n:"Impugnación de acuerdo de junta de propietarios",cat:"esx_comunidad",tier:"komplex",q:[Pe("comunidad_direccion","Dirección de la comunidad de propietarios",true),Pe("propietario_nombre","Nombre completo del propietario impugnante",true),Pe("fecha_junta","Fecha de la junta en que se adoptó el acuerdo",true),Pe("acuerdo_impugnado","Descripción del acuerdo que se impugna",true),Pe("motivo_impugnacion","Motivo de la impugnación",true,["Contrario a la Ley de Propiedad Horizontal","Gravemente lesivo para algún propietario","Abuso de derecho","Vicio de forma en la convocatoria o votación","Otro motivo"]),Pe("voto_en_junta","Postura del propietario en la votación",true,["Votó en contra","Se abstuvo","No asistió a la junta"])]},
    "esx_comunidad_reclamacion_gastos_comunidad":{ic:"💶",n:"Reclamación de cuotas impagadas de comunidad",cat:"esx_comunidad",tier:"standard",q:[Pe("comunidad_direccion","Dirección de la comunidad de propietarios",true),Pe("remitente_nombre","Nombre del presidente o administrador de la comunidad que reclama",true),Pe("propietario_deudor","Nombre del propietario deudor",true),Pe("importe_adeudado","Importe total adeudado",true),Pe("periodo_adeudado","Periodo al que corresponde la deuda",true),Pe("numero_recibos","Número de recibos o mensualidades impagadas",false),Pe("via_previa","¿Se ha requerido el pago previamente?",true,["Sí, verbalmente","Sí, por escrito","No, es el primer requerimiento"])]},
    "esx_comunidad_denuncia_okupacion":{ic:"🚨",n:"Denuncia por okupación ilegal de vivienda",cat:"esx_comunidad",tier:"komplex",q:[Pe("propietario_nombre","Nombre completo del propietario o representante legal",true),Pe("direccion_vivienda","Dirección completa de la vivienda ocupada",true),Pe("fecha_deteccion","Fecha en que se detectó la ocupación",true),Pe("tipo_inmueble","Tipo de inmueble ocupado",true,["Vivienda habitual","Segunda residencia","Local o trastero","Vivienda vacía en alquiler"]),Pe("identificacion_ocupantes","¿Se conoce la identidad de los ocupantes?",false,["Sí, total o parcialmente","No, se desconoce"]),Pe("hubo_fuerza_o_dano","¿Hubo fuerza en las cosas o daños al acceder?",false,["Sí","No","No lo sé"])]},
    "esx_comunidad_requerimiento_desalojo_okupa":{ic:"🔑",n:"Requerimiento previo de desalojo a ocupantes ilegales",cat:"esx_comunidad",tier:"standard",q:[Pe("propietario_nombre","Nombre completo del propietario",true),Pe("direccion_vivienda","Dirección de la vivienda ocupada",true),Pe("fecha_inicio_ocupacion","Fecha aproximada de inicio de la ocupación",true),Pe("plazo_desalojo","Plazo concedido para el desalojo voluntario",true,["24 horas","48 horas","72 horas","5 días","Otro plazo"]),Pe("existe_titulo_habilitante","¿Los ocupantes alegan algún título habilitante (contrato, permiso)?",false,["Sí","No","No lo sé"])]},
    "esx_autonomos_reclamacion_tarifa_plana":{ic:"📉",n:"Reclamación por pérdida indebida de la tarifa plana de autónomos",cat:"esx_autonomos",tier:"standard",q:[Pe("autonomo_nombre","Nombre completo del autónomo",true),Pe("fecha_alta","Fecha de alta en el RETA",true),Pe("fecha_perdida_bonificacion","Fecha en que la Seguridad Social retiró la bonificación",true),Pe("motivo_alegado_ss","Motivo alegado por la Seguridad Social para retirarla",true),Pe("motivo_reclamacion","Motivo por el que considera indebida la retirada",true,["No ha habido cambios que justifiquen la pérdida","Error administrativo","Cambio de epígrafe no relevante","Otro motivo"])]},
    "esx_autonomos_reclamacion_impago_factura":{ic:"🧾",n:"Reclamación de factura impagada a un cliente",cat:"esx_autonomos",tier:"standard",q:[Pe("autonomo_nombre","Nombre o razón social del autónomo",true),Pe("cliente_nombre","Nombre o razón social del cliente deudor",true),Pe("numero_factura","Número de factura impagada",true),Pe("importe_adeudado","Importe total adeudado",true),Pe("fecha_vencimiento","Fecha de vencimiento del pago",true),Pe("gestiones_previas","¿Se han realizado gestiones de cobro previas?",false,["Sí, por teléfono o email","Sí, por escrito","No, es la primera reclamación"])]},
    "esx_autonomos_cese_actividad":{ic:"🛑",n:"Comunicación de cese de actividad y baja censal",cat:"esx_autonomos",tier:"einfach",q:[Pe("autonomo_nombre","Nombre completo del autónomo",true),Pe("nif_autonomo","NIF del autónomo",true),Pe("actividad_epigrafe","Actividad económica o epígrafe del IAE",true),Pe("fecha_cese","Fecha efectiva del cese de la actividad",true),Pe("motivo_cese","Motivo del cese",true,["Falta de rentabilidad","Jubilación","Cambio a trabajo por cuenta ajena","Enfermedad o incapacidad","Otro motivo"])]},
    "esx_autonomos_contrato_trade":{ic:"📝",n:"Contrato de Trabajador Autónomo Económicamente Dependiente (TRADE)",cat:"esx_autonomos",tier:"komplex",q:[Pe("autonomo_nombre","Nombre completo o razón social del autónomo TRADE",true),Pe("cliente_principal_nombre","Nombre o razón social del cliente principal (empresa o autónomo contratante)",true),Pe("porcentaje_ingresos_cliente","Porcentaje de los ingresos anuales que representa este cliente (mínimo 75% para la condición de TRADE)",true),Pe("actividad_a_realizar","Descripción de la actividad o servicios a prestar",true),Pe("duracion_contrato","Duración del contrato",true,["Duración determinada","Duración indefinida"]),Pe("preaviso_resolucion","Plazo de preaviso pactado para la resolución del contrato",true,["15 días","30 días","Otro plazo"]),Pe("registro_sepe","¿Se registrará el contrato en el Servicio Público de Empleo Estatal (SEPE)?",false,["Sí","No","Pendiente de decidir"])]},
    "esx_derechos_denuncia_discriminacion_laboral":{ic:"🚫",n:"Denuncia interna por discriminación laboral",cat:"esx_derechos_especiales",tier:"standard",q:[Pe("trabajador_nombre","Nombre completo del trabajador",true),Pe("empresa_nombre","Nombre de la empresa",true),Pe("puesto_trabajo","Puesto de trabajo",true),Pe("motivo_discriminacion","Motivo de la discriminación sufrida",true,["Sexo o género","Edad","Discapacidad","Origen étnico o nacionalidad","Orientación sexual","Religión o creencias","Afiliación sindical","Otro motivo"]),Pe("hechos_descripcion","Descripción de los hechos discriminatorios",true),Pe("fecha_hechos","Fecha o periodo en que ocurrieron los hechos",true)]},
    "esx_derechos_acoso_laboral":{ic:"🆘",n:"Denuncia de acoso laboral (mobbing) ante la empresa",cat:"esx_derechos_especiales",tier:"komplex",q:[Pe("trabajador_nombre","Nombre completo del trabajador afectado",true),Pe("empresa_nombre","Nombre de la empresa",true),Pe("presunto_acosador","Nombre o cargo de la persona denunciada",true),Pe("tipo_acoso","Tipo de acoso sufrido",true,["Acoso psicológico (mobbing)","Acoso sexual","Acoso por razón de sexo","Otro tipo"]),Pe("descripcion_hechos","Descripción detallada de los hechos",true),Pe("existen_testigos","¿Existen testigos de los hechos?",false,["Sí","No","No lo sé"]),Pe("afeccion_salud","¿Ha afectado a su salud física o mental?",false,["Sí, con baja médica","Sí, sin baja médica","No"])]},
    "esx_derechos_igualdad_salarial":{ic:"⚖️",n:"Reclamación por desigualdad salarial por razón de sexo",cat:"esx_derechos_especiales",tier:"standard",q:[Pe("trabajador_nombre","Nombre completo del trabajador/a reclamante",true),Pe("empresa_nombre","Nombre de la empresa",true),Pe("puesto_trabajo","Puesto de trabajo desempeñado",true),Pe("diferencia_salarial","Diferencia salarial detectada respecto a un compañero/a",true),Pe("puesto_comparacion","Puesto o persona de comparación (mismo trabajo o de igual valor)",false),Pe("registro_retributivo","¿La empresa cuenta con registro retributivo?",false,["Sí","No","No lo sé"])]},
    "esx_derechos_revocacion_datos_menor":{ic:"🧒",n:"Revocación del consentimiento sobre datos personales de un menor",cat:"esx_derechos_especiales",tier:"einfach",q:[Pe("responsable_legal_nombre","Nombre completo del padre, madre o tutor legal",true),Pe("menor_nombre","Nombre del menor afectado",true),Pe("edad_menor","Edad del menor",true),Pe("entidad_destinataria","Entidad o plataforma que trata los datos",true),Pe("datos_tratados","Tipo de datos personales tratados",true,["Datos de identificación","Imágenes o vídeos","Datos escolares","Datos de geolocalización","Otros"]),Pe("fecha_consentimiento_inicial","Fecha en la que se otorgó el consentimiento inicial",false)]},
    "esx_derechos_denuncia_aepd_menores":{ic:"🛡️",n:"Denuncia ante la AEPD por tratamiento indebido de datos de menores",cat:"esx_derechos_especiales",tier:"komplex",q:[Pe("denunciante_nombre","Nombre completo del denunciante (padre, madre o tutor)",true),Pe("menor_afectado","Nombre o iniciales del menor afectado",true),Pe("entidad_denunciada","Entidad o empresa denunciada",true),Pe("tipo_infraccion","Tipo de infracción detectada",true,["Tratamiento sin consentimiento válido","Falta de edad mínima requerida (14 años)","Cesión de datos a terceros sin autorización","Uso de imágenes sin permiso","Otra infracción"]),Pe("gestion_previa_entidad","¿Se ha reclamado previamente ante la entidad?",true,["Sí, sin respuesta","Sí, con respuesta insatisfactoria","No, es la primera reclamación"]),Pe("descripcion_hechos","Descripción de los hechos denunciados",true)]}
  };
  function inject(){
    try{
      if(typeof DOCS==="undefined"||!DOCS) return false;
      if(typeof CATS==="undefined"||!CATS) return false;
      for(var k in E){ if(!DOCS[k]) DOCS[k]=E[k]; if(typeof DOC_TIER!=="undefined") DOC_TIER[k]=E[k].tier||"standard"; }
      for(var nc in NEWCATS){ if(!CATS[nc]) CATS[nc]={n:NEWCATS[nc].n,ic:NEWCATS[nc].ic,docs:[],country:"ES"}; if(!CATS[nc].docs) CATS[nc].docs=[]; }
      for(var k2 in E){ var c2=E[k2].cat; if(CATS[c2]&&CATS[c2].docs&&CATS[c2].docs.indexOf(k2)<0) CATS[c2].docs.push(k2); }
      if(typeof CAT_LABELS!=="undefined"){ for(var cl in NEWCATS) CAT_LABELS[cl]=NEWCATS[cl].n; }
      if(typeof CAT_DOCS!=="undefined"){
        for(var cd in NEWCATS){ if(!CAT_DOCS[cd]) CAT_DOCS[cd]=[]; }
        for(var k3 in E){ var c3=E[k3].cat; if(CAT_DOCS[c3]){ var ex=false; for(var i=0;i<CAT_DOCS[c3].length;i++){ if(CAT_DOCS[c3][i].k===k3){ex=true;break;} } if(!ex) CAT_DOCS[c3].push({k:k3,ic:E[k3].ic,t:E[k3].n,tier:E[k3].tier||"standard"}); } }
      }
      return !!(DOCS.esx_herencias_aceptacion_beneficio_inventario);
    }catch(e){ return false; }
  }
  var done=false, ticks=0;
  function run(){ if(!done){ if(inject()) done=true; } if(ticks++<40) setTimeout(run,500); }
  if(document.readyState==="loading") document.addEventListener("DOMContentLoaded",run); else run();
})();}catch(e){}

CHJS;
$src=str_replace($anchor,$anchor.$js,$src);
$tmp = tempnam(sys_get_temp_dir(),'es').'.php';
file_put_contents($tmp,$src);
$lo=[];$rc=0; exec('php -l '.escapeshellarg($tmp).' 2>&1',$lo,$rc); @unlink($tmp);
if ($rc!==0) { echo "\nLINT HATASI — index.php degistirilmedi:\n  ".implode("\n  ",$lo)."\n"; exit; }
file_put_contents($file.'.bak-esmore-'.date('Ymd-His'), @file_get_contents($file));
file_put_contents($file,$src);
echo "  ✓ ES: +18 belge, 4 kategori eklendi\n\n✓ CH_ES_EXPAND_MORE uygulandi.\n";
