<?php
/** ChatHelp — apply-vst-more2 (CH_VST_MORE_2) — Vertrag Studio'ya 6 yeni sozlesme
 *  Closure icine (boot anchor) enjekte: CT'ye ekler, buildPages'i sarmalayip
 *  yeni anahtarlari veri-gudumlu builder'a yonlendirir (zincirlenir).
 *  Her yeni sozlesmede "Eigene Klauseln" adimi da vardir (vst-custom ile uyumlu).
 *  KULLANIM: pull-updates.php?files=apply-vst-more2.php */
header('Content-Type: text/plain; charset=UTF-8');
error_reporting(E_ERROR | E_PARSE);
echo "apply-vst-more2 BASLADI OK (PHP ".PHP_VERSION.")\n\n";
$file = __DIR__.'/index.php';
$src = @file_get_contents($file);
if ($src===false) exit("index.php okunamadi\n");
if (strpos($src,'CH_VST_MORE_2')!==false) exit("Zaten ekli (CH_VST_MORE_2).\n");
$anchor='function boot(){ addCss(); addNav();';
if (strpos($src,$anchor)===false) exit("HATA: Vertrag Studio boot anchor yok.\n");
$inject = <<<'CHJS'

  /* CH_VST_MORE_2 — yeni sozlesmeler */
  try{
    var NCX2={
    "nc2_ebike":{n:"Fahrrad-/E-Bike-Kaufvertrag",sn:"privat",A:"Verkäufer",B:"Käufer",cl:[{no:"§ 1",t:"VERTRAGSPARTEIEN",b:function(d){return "Zwischen "+V(d.vk_name)+", "+V(d.vk_addr)+" — nachfolgend Verkäufer — und "+V(d.kf_name)+", "+V(d.kf_addr)+" — nachfolgend Käufer — wird folgender Kaufvertrag geschlossen.";}},{no:"§ 2",t:"KAUFGEGENSTAND",b:function(d){return "Verkauft wird das gebrauchte Fahrrad/E-Bike der Marke "+V(d.marke)+", Rahmennummer "+V(d.rahmennr,"—")+", Baujahr "+V(d.baujahr,"—")+". Zustand: "+V(d.zustand)+". Mitverkauftes Zubehör: "+V(d.zubehoer,"—")+".";}},{no:"§ 3",t:"KAUFPREIS & EIGENTUM",b:function(d){return "Der Kaufpreis beträgt "+V(d.preis)+" €. Die Zahlung erfolgt "+V(d.zahlart,"bar bei Übergabe")+". Das Fahrrad bleibt bis zur vollständigen Bezahlung Eigentum des Verkäufers (§ 449 BGB).";}},{no:"§ 4",t:"ÜBERGABE & GEFAHRÜBERGANG",b:function(d){return "Die Übergabe des Fahrrads erfolgt am "+V(d.uebergabe)+". Mit der Übergabe geht die Gefahr des zufälligen Untergangs und der zufälligen Verschlechterung auf den Käufer über (§ 446 BGB).";}},{no:"§ 5",t:"GEWÄHRLEISTUNG",b:function(d){return "Das Fahrrad wird als Privatverkauf unter Ausschluss jeglicher Sachmängelhaftung verkauft. Der Ausschluss gilt nicht für Vorsatz und Arglist sowie für Schäden aus der Verletzung von Leben, Körper oder Gesundheit. Dem Käufer bekannte Mängel: "+V(d.maengel,"keine besonderen Mängel bekannt")+".";}},{no:"§ 6",t:"SCHLUSSBESTIMMUNGEN",b:function(d){return "Mündliche Nebenabreden bestehen nicht. Änderungen bedürfen der Textform. Sollte eine Bestimmung unwirksam sein, bleibt der Vertrag im Übrigen wirksam. Beide Parteien erhalten je eine unterschriebene Ausfertigung.";}}]},
    "nc2_moebel":{n:"Kaufvertrag Möbel & Elektronik",sn:"gebraucht, privat",A:"Verkäufer",B:"Käufer",cl:[{no:"§ 1",t:"VERTRAGSPARTEIEN",b:function(d){return "Zwischen "+V(d.vk_name)+", "+V(d.vk_addr)+" — Verkäufer — und "+V(d.kf_name)+", "+V(d.kf_addr)+" — Käufer — kommt folgender Kaufvertrag zustande.";}},{no:"§ 2",t:"KAUFGEGENSTAND",b:function(d){return "Gegenstand des Kaufs ist: "+V(d.ware)+". Zustand/Alter: "+V(d.zustand)+". Geräte-/Seriennummer: "+V(d.seriennr,"—")+".";}},{no:"§ 3",t:"KAUFPREIS & ZAHLUNG",b:function(d){return "Der Kaufpreis beträgt "+V(d.preis)+" € und wird "+V(d.zahlart,"bar bei Übergabe")+" entrichtet. Die Ware bleibt bis zur vollständigen Zahlung Eigentum des Verkäufers (§ 449 BGB).";}},{no:"§ 4",t:"ÜBERGABE",b:function(d){return "Die Übergabe bzw. Abholung erfolgt am "+V(d.uebergabe)+". Transport und Abbau organisiert der Käufer auf eigene Kosten und Gefahr, sofern nichts anderes vereinbart ist. Mit der Übergabe geht die Gefahr auf den Käufer über (§ 446 BGB).";}},{no:"§ 5",t:"GEWÄHRLEISTUNG",b:function(d){return "Es handelt sich um einen Verkauf gebrauchter Sachen von privat unter Ausschluss der Sachmängelhaftung. Der Ausschluss gilt nicht bei Vorsatz, Arglist sowie bei Schäden aus der Verletzung von Leben, Körper oder Gesundheit. Bekannte Mängel: "+V(d.maengel,"keine besonderen Mängel bekannt")+".";}},{no:"§ 6",t:"SCHLUSSBESTIMMUNGEN",b:function(d){return "Nebenabreden bestehen nicht. Änderungen bedürfen der Textform. Die Unwirksamkeit einzelner Bestimmungen berührt den Vertrag im Übrigen nicht. Jede Partei erhält eine unterschriebene Ausfertigung.";}}]},
    "nc2_tier":{n:"Tierkaufvertrag (Hund/Katze)",sn:"privat",A:"Verkäufer",B:"Käufer",cl:[{no:"§ 1",t:"VERTRAGSPARTEIEN",b:function(d){return "Zwischen "+V(d.vk_name)+", "+V(d.vk_addr)+" — Verkäufer — und "+V(d.kf_name)+", "+V(d.kf_addr)+" — Käufer — wird folgender Tierkaufvertrag geschlossen.";}},{no:"§ 2",t:"KAUFGEGENSTAND",b:function(d){return "Verkauft wird ein Tier der Art/Rasse "+V(d.tierart)+", Geschlecht "+V(d.geschlecht,"—")+", geboren am "+V(d.wurf,"—")+", Chip-/Transpondernummer "+V(d.chip,"—")+". Tiere sind keine Sachen; auf sie sind die für Sachen geltenden Vorschriften entsprechend anzuwenden (§ 90a BGB).";}},{no:"§ 3",t:"KAUFPREIS",b:function(d){return "Der Kaufpreis beträgt "+V(d.preis)+" €, zahlbar bei Übergabe des Tieres. Das Eigentum geht mit vollständiger Zahlung und Übergabe auf den Käufer über.";}},{no:"§ 4",t:"GESUNDHEITSZUSTAND & UNTERLAGEN",b:function(d){return "Der Verkäufer versichert, dass das Tier zum Zeitpunkt der Übergabe nach seiner Kenntnis gesund ist. Durchgeführte Impfungen/Entwurmungen und übergebene Papiere: "+V(d.impf,"siehe Impfpass")+". Bekannte gesundheitliche Besonderheiten: "+V(d.gesund,"keine bekannt")+".";}},{no:"§ 5",t:"ÜBERGABE & HALTUNG",b:function(d){return "Die Übergabe erfolgt am "+V(d.uebergabe)+". Der Käufer verpflichtet sich zur artgerechten Haltung und Versorgung des Tieres entsprechend dem Tierschutzgesetz.";}},{no:"§ 6",t:"GEWÄHRLEISTUNG",b:function(d){return "Der Verkauf erfolgt von privat. Eine Haftung für nicht erkennbare Krankheiten oder verdeckte Mängel wird — soweit gesetzlich zulässig — ausgeschlossen; der Ausschluss gilt nicht bei Vorsatz oder Arglist. Dem Käufer wird empfohlen, das Tier zeitnah tierärztlich untersuchen zu lassen.";}},{no:"§ 7",t:"SCHLUSSBESTIMMUNGEN",b:function(d){return "Nebenabreden bedürfen der Textform. Sollte eine Bestimmung unwirksam sein, bleibt der Vertrag im Übrigen wirksam. Jede Partei erhält eine unterschriebene Ausfertigung.";}}]},
    "nc2_nachmieter":{n:"Nachmietervereinbarung",sn:"Wohnungsübernahme",A:"Vormieter",B:"Nachmieter",cl:[{no:"§ 1",t:"PARTEIEN",b:function(d){return "Zwischen "+V(d.vor_name)+", "+V(d.vor_addr)+" — Vormieter — und "+V(d.nach_name)+", "+V(d.nach_addr)+" — Nachmieter — wird folgende Vereinbarung über die Übernahme der Wohnung getroffen.";}},{no:"§ 2",t:"WOHNUNG & VERMIETERZUSTIMMUNG",b:function(d){return "Gegenstand ist die Wohnung "+V(d.wohnung)+", vermietet von "+V(d.vermieter)+". Diese Vereinbarung steht unter der Bedingung, dass der Vermieter dem Mieterwechsel bzw. dem Abschluss eines neuen Mietvertrages mit dem Nachmieter zustimmt. Ohne Zustimmung des Vermieters entfaltet sie keine Wirkung gegenüber dem Vermieter.";}},{no:"§ 3",t:"ÜBERNAHMEZEITPUNKT",b:function(d){return "Die Übergabe der Wohnung an den Nachmieter erfolgt am "+V(d.uebernahme)+". Zu diesem Zeitpunkt werden die Zählerstände gemeinsam abgelesen und protokolliert: "+V(d.zaehler,"werden bei Übergabe protokolliert")+".";}},{no:"§ 4",t:"ABLÖSE VON EINRICHTUNG",b:function(d){return "Der Nachmieter übernimmt vom Vormieter folgende Gegenstände gegen Zahlung einer Ablöse von "+V(d.ablose,"0")+" €: "+V(d.gegenstaende,"—")+". Die Ablöse ist bei Übergabe fällig. Übernommene Gegenstände gehen mit Zahlung in das Eigentum des Nachmieters über.";}},{no:"§ 5",t:"KAUTION",b:function(d){return "Für die Mietkaution gilt: "+V(d.kaution,"Die Kaution wird zwischen Vormieter und Vermieter abgerechnet; der Nachmieter hinterlegt eine eigene Kaution beim Vermieter.")+" Eine unmittelbare Übertragung der Kaution erfolgt nur mit Zustimmung des Vermieters.";}},{no:"§ 6",t:"SCHLUSSBESTIMMUNGEN",b:function(d){return "Diese Vereinbarung begründet keinen Mietvertrag mit dem Vermieter; ein solcher ist gesondert abzuschließen. Änderungen bedürfen der Textform. Jede Partei erhält eine unterschriebene Ausfertigung.";}}]},
    "nc2_pflege":{n:"Privater Betreuungs-/Pflegevertrag",sn:"haushaltsnahe Betreuung",A:"Auftraggeber",B:"Betreuungskraft",cl:[{no:"§ 1",t:"VERTRAGSPARTEIEN",b:function(d){return "Zwischen "+V(d.ag_name)+", "+V(d.ag_addr)+" — Auftraggeber — und "+V(d.pk_name)+", "+V(d.pk_addr)+" — Betreuungskraft — wird folgender Dienstvertrag über Betreuungsleistungen geschlossen (§§ 611 ff. BGB).";}},{no:"§ 2",t:"LEISTUNGSGEGENSTAND",b:function(d){return "Die Betreuungskraft erbringt haushaltsnahe Betreuungs- und Unterstützungsleistungen für "+V(d.betreute,"den Auftraggeber")+": "+V(d.leistungen)+". Medizinische Behandlungspflege im Sinne des SGB V ist nicht Gegenstand dieses Vertrages und bleibt examiniertem Pflegepersonal vorbehalten.";}},{no:"§ 3",t:"EINSATZORT",b:function(d){return "Die Leistungen werden erbracht an folgendem Ort: "+V(d.ort_leistung)+".";}},{no:"§ 4",t:"ARBEITSZEIT & UMFANG",b:function(d){return "Der Umfang der Tätigkeit beträgt "+V(d.umfang)+". Die konkrete Einteilung wird einvernehmlich abgestimmt.";}},{no:"§ 5",t:"VERGÜTUNG",b:function(d){return "Die Betreuungskraft erhält eine Vergütung von "+V(d.verguetung)+". Die Zahlung ist "+V(d.faellig,"zum Monatsende")+" fällig. Der gesetzliche Mindestlohn wird nicht unterschritten. Die Vertragsparteien klären eigenverantwortlich die sozialversicherungs- und steuerrechtliche Behandlung (ggf. Anmeldung als Minijob/Haushaltshilfe bei der Minijob-Zentrale).";}},{no:"§ 6",t:"PFLICHTEN & VERSCHWIEGENHEIT",b:function(d){return "Die Betreuungskraft führt die Leistungen sorgfältig, zuverlässig und mit Rücksicht auf die Würde der betreuten Person aus. Über persönliche Verhältnisse bewahrt sie Stillschweigen — auch nach Vertragsende.";}},{no:"§ 7",t:"BEGINN & KÜNDIGUNG",b:function(d){return "Der Vertrag beginnt am "+V(d.beginn)+" und läuft auf unbestimmte Zeit. Er kann von beiden Seiten mit einer Frist von "+V(d.kuend,"2 Wochen")+" gekündigt werden. Das Recht zur außerordentlichen Kündigung aus wichtigem Grund (§ 626 BGB) bleibt unberührt.";}},{no:"§ 8",t:"SCHLUSSBESTIMMUNGEN",b:function(d){return "Änderungen und Ergänzungen bedürfen der Textform. Sollte eine Bestimmung unwirksam sein, bleibt der Vertrag im Übrigen wirksam. Jede Partei erhält eine unterschriebene Ausfertigung.";}}]},
    "nc2_koop":{n:"Kooperations-/Werbevertrag",sn:"Influencer / Creator",A:"Unternehmen",B:"Creator",cl:[{no:"§ 1",t:"VERTRAGSPARTEIEN",b:function(d){return "Zwischen "+V(d.un_name)+", "+V(d.un_addr)+" — Unternehmen — und "+V(d.cr_name)+", "+V(d.cr_addr)+" — Creator — wird folgender Kooperationsvertrag geschlossen.";}},{no:"§ 2",t:"LEISTUNG DES CREATORS",b:function(d){return "Der Creator erstellt und veröffentlicht auf "+V(d.kanal)+" folgende Inhalte: "+V(d.leistung)+". Veröffentlichungszeitraum: "+V(d.zeitraum)+". Inhalte werden vor Veröffentlichung nur abgestimmt, soweit ausdrücklich vereinbart; die kreative Gestaltung liegt beim Creator.";}},{no:"§ 3",t:"KENNZEICHNUNG (WERBUNG)",b:function(d){return "Der Creator kennzeichnet die Inhalte als Werbung bzw. bezahlte Partnerschaft entsprechend den geltenden rechtlichen Vorgaben (u. a. UWG, Landesmedienrecht). Die ordnungsgemäße Werbekennzeichnung obliegt dem Creator.";}},{no:"§ 4",t:"VERGÜTUNG",b:function(d){return "Als Vergütung erhält der Creator "+V(d.verguetung)+". Die Zahlung ist "+V(d.faellig,"14 Tage nach Veröffentlichung und Rechnungsstellung")+" fällig. Etwaige Steuern trägt jede Partei selbst.";}},{no:"§ 5",t:"NUTZUNGSRECHTE",b:function(d){return "Der Creator räumt dem Unternehmen an den erstellten Inhalten folgende Nutzungsrechte ein: "+V(d.nutzung,"einfaches Nutzungsrecht zur Wiederveröffentlichung auf den eigenen Kanälen des Unternehmens für die Dauer der Kampagne")+". Die Urheberschaft des Creators bleibt unberührt.";}},{no:"§ 6",t:"EXKLUSIVITÄT",b:function(d){return "Exklusivität/Wettbewerbsbeschränkung: "+V(d.exkl,"keine Exklusivität vereinbart")+".";}},{no:"§ 7",t:"HAFTUNG & FREISTELLUNG",b:function(d){return "Jede Partei haftet für die von ihr zu verantwortenden Inhalte. Das Unternehmen stellt dem Creator zutreffende Produktangaben zur Verfügung und stellt ihn von Ansprüchen frei, die aus unrichtigen Angaben des Unternehmens resultieren.";}},{no:"§ 8",t:"SCHLUSSBESTIMMUNGEN",b:function(d){return "Änderungen bedürfen der Textform. Sollte eine Bestimmung unwirksam sein, bleibt der Vertrag im Übrigen wirksam. Es gilt deutsches Recht. Jede Partei erhält eine unterschriebene Ausfertigung.";}}]}
    };
  CT["nc2_ebike"]={ic:"🚲",n:"Fahrrad-/E-Bike-Kaufvertrag",sn:"privat",price:"4,99 €",pgs:3,steps:[{t:"§1–2 · Parteien & Rad",f:[["vk_name","Verkäufer — Name"],["vk_addr","Verkäufer — Anschrift"],["kf_name","Käufer — Name"],["kf_addr","Käufer — Anschrift"],["marke","Marke / Modell"],["rahmennr","Rahmennummer"],["baujahr","Baujahr"],["zustand","Zustand (z. B. gebraucht, guter Zustand)"]]},{t:"§3–6 · Preis, Übergabe & Unterschrift",f:[["preis","Kaufpreis (€)"],["zahlart","Zahlungsart","bar bei Übergabe"],["uebergabe","Übergabe am (Datum)"],["zubehoer","Mitverkauftes Zubehör (Schloss, Akku, Ladegerät …)"],["maengel","Bekannte Mängel","","ta"],["ort","Ort"],["datum","Datum"]]},{t:"Eigene Klauseln (optional) — Ihr eigener Wortlaut",f:[["uc_t1","Eigene Klausel 1 — Überschrift","z. B. Sondervereinbarung"],["uc_b1","Eigene Klausel 1 — Wortlaut","","ta"],["uc_t2","Eigene Klausel 2 — Überschrift (optional)",""],["uc_b2","Eigene Klausel 2 — Wortlaut (optional)","","ta"]]}]};
  CT["nc2_moebel"]={ic:"🛋️",n:"Kaufvertrag Möbel & Elektronik",sn:"gebraucht, privat",price:"4,99 €",pgs:3,steps:[{t:"§1–2 · Parteien & Ware",f:[["vk_name","Verkäufer — Name"],["vk_addr","Verkäufer — Anschrift"],["kf_name","Käufer — Name"],["kf_addr","Käufer — Anschrift"],["ware","Kaufgegenstand (Beschreibung)","","ta"],["zustand","Zustand / Alter"],["seriennr","Serien-/Gerätenummer (bei Elektronik)"]]},{t:"§3–6 · Preis & Übergabe",f:[["preis","Kaufpreis (€)"],["zahlart","Zahlungsart","bar bei Übergabe"],["uebergabe","Übergabe / Abholung am (Datum)"],["maengel","Bekannte Mängel","","ta"],["ort","Ort"],["datum","Datum"]]},{t:"Eigene Klauseln (optional) — Ihr eigener Wortlaut",f:[["uc_t1","Eigene Klausel 1 — Überschrift","z. B. Sondervereinbarung"],["uc_b1","Eigene Klausel 1 — Wortlaut","","ta"],["uc_t2","Eigene Klausel 2 — Überschrift (optional)",""],["uc_b2","Eigene Klausel 2 — Wortlaut (optional)","","ta"]]}]};
  CT["nc2_tier"]={ic:"🐕",n:"Tierkaufvertrag (Hund/Katze)",sn:"privat",price:"4,99 €",pgs:3,steps:[{t:"§1–2 · Parteien & Tier",f:[["vk_name","Verkäufer — Name"],["vk_addr","Verkäufer — Anschrift"],["kf_name","Käufer — Name"],["kf_addr","Käufer — Anschrift"],["tierart","Tierart / Rasse"],["wurf","Wurftag / Geburtsdatum"],["chip","Chip-/Transpondernummer"],["geschlecht","Geschlecht"]]},{t:"§3–7 · Preis, Gesundheit & Übergabe",f:[["preis","Kaufpreis (€)"],["impf","Impfungen / Entwurmung / Papiere","","ta"],["gesund","Bekannte gesundheitliche Besonderheiten","","ta"],["uebergabe","Übergabe am (Datum)"],["ort","Ort"],["datum","Datum"]]},{t:"Eigene Klauseln (optional) — Ihr eigener Wortlaut",f:[["uc_t1","Eigene Klausel 1 — Überschrift","z. B. Sondervereinbarung"],["uc_b1","Eigene Klausel 1 — Wortlaut","","ta"],["uc_t2","Eigene Klausel 2 — Überschrift (optional)",""],["uc_b2","Eigene Klausel 2 — Wortlaut (optional)","","ta"]]}]};
  CT["nc2_nachmieter"]={ic:"🔑",n:"Nachmietervereinbarung",sn:"Wohnungsübernahme",price:"4,99 €",pgs:3,steps:[{t:"§1–2 · Parteien & Wohnung",f:[["vor_name","Vormieter — Name"],["vor_addr","Vormieter — Anschrift"],["nach_name","Nachmieter — Name"],["nach_addr","Nachmieter — Anschrift"],["wohnung","Wohnung (Straße, Nr., PLZ, Ort, Etage)"],["vermieter","Vermieter (Name)"],["uebernahme","Übernahmedatum"]]},{t:"§3–6 · Ablöse & Unterschrift",f:[["ablose","Ablösesumme für Einrichtung/Küche (€)"],["gegenstaende","Abzulösende Gegenstände","","ta"],["kaution","Umgang mit Kaution (Regelung)"],["zaehler","Zählerstände (Strom, Gas, Wasser)","","ta"],["ort","Ort"],["datum","Datum"]]},{t:"Eigene Klauseln (optional) — Ihr eigener Wortlaut",f:[["uc_t1","Eigene Klausel 1 — Überschrift","z. B. Sondervereinbarung"],["uc_b1","Eigene Klausel 1 — Wortlaut","","ta"],["uc_t2","Eigene Klausel 2 — Überschrift (optional)",""],["uc_b2","Eigene Klausel 2 — Wortlaut (optional)","","ta"]]}]};
  CT["nc2_pflege"]={ic:"🧑‍⚕️",n:"Privater Betreuungs-/Pflegevertrag",sn:"haushaltsnahe Betreuung",price:"4,99 €",pgs:3,steps:[{t:"§1–3 · Parteien & Leistung",f:[["ag_name","Auftraggeber — Name"],["ag_addr","Auftraggeber — Anschrift"],["pk_name","Betreuungskraft — Name"],["pk_addr","Betreuungskraft — Anschrift"],["betreute","Zu betreuende Person (falls abweichend)"],["leistungen","Aufgaben (Haushalt, Begleitung, Grundbetreuung …)","","ta"],["ort_leistung","Einsatzort"]]},{t:"§4–8 · Zeit, Vergütung & Ende",f:[["umfang","Umfang (Stunden/Woche) & Zeiten"],["verguetung","Vergütung (€/Std. oder €/Monat, mind. Mindestlohn)"],["faellig","Fälligkeit der Zahlung","zum Monatsende"],["beginn","Beginn (Datum)"],["kuend","Kündigungsfrist","2 Wochen"],["ort","Ort"],["datum","Datum"]]},{t:"Eigene Klauseln (optional) — Ihr eigener Wortlaut",f:[["uc_t1","Eigene Klausel 1 — Überschrift","z. B. Sondervereinbarung"],["uc_b1","Eigene Klausel 1 — Wortlaut","","ta"],["uc_t2","Eigene Klausel 2 — Überschrift (optional)",""],["uc_b2","Eigene Klausel 2 — Wortlaut (optional)","","ta"]]}]};
  CT["nc2_koop"]={ic:"🤝",n:"Kooperations-/Werbevertrag",sn:"Influencer / Creator",price:"4,99 €",pgs:3,steps:[{t:"§1–3 · Parteien & Leistung",f:[["un_name","Unternehmen — Firma"],["un_addr","Unternehmen — Anschrift"],["cr_name","Creator — Name / Künstlername"],["cr_addr","Creator — Anschrift"],["kanal","Kanal/Plattform & Reichweite"],["leistung","Leistung (Anzahl Posts/Stories/Videos, Inhalte)","","ta"],["zeitraum","Veröffentlichungszeitraum"]]},{t:"§4–8 · Vergütung, Rechte & Ende",f:[["verguetung","Vergütung (€) und ggf. Produkte"],["faellig","Zahlung fällig","14 Tage nach Veröffentlichung & Rechnung"],["nutzung","Nutzungsrechte (Dauer, Kanäle des Unternehmens)","","ta"],["exkl","Exklusivität / Wettbewerbsverbot (falls vereinbart)"],["ort","Ort"],["datum","Datum"]]},{t:"Eigene Klauseln (optional) — Ihr eigener Wortlaut",f:[["uc_t1","Eigene Klausel 1 — Überschrift","z. B. Sondervereinbarung"],["uc_b1","Eigene Klausel 1 — Wortlaut","","ta"],["uc_t2","Eigene Klausel 2 — Überschrift (optional)",""],["uc_b2","Eigene Klausel 2 — Wortlaut (optional)","","ta"]]}]};
    function ncxBuild2(key,d){
      var s=NCX2[key], P=[], per=5, cl=s.cl;
      for(var i=0;i<cl.length;i+=per){
        var chunk=cl.slice(i,i+per);
        var inner=(i===0?head(s.n,s.sn):"");
        for(var j=0;j<chunk.length;j++){ inner+=par(chunk[j].no,chunk[j].t,chunk[j].b(d)); }
        P.push(inner);
      }
      if(!P.length) P.push(head(s.n,s.sn));
      P[P.length-1]+=sig2(d,s.A,s.B,d.ort,d.datum);
      var n=P.length, doc=s.n;
      return P.map(function(inner,i){ return '<div class="vsA4">'+inner+foot(doc,i+1,n)+'</div>'; });
    }
    (function(){ var _bp=buildPages; buildPages=function(key,d){ if(NCX2[key]){ var P=ncxBuild2(key,d); try{ P=P.concat(optPages(key,d)); }catch(e){} return P; } return _bp(key,d); }; })();
  }catch(e){}

CHJS;
$src=str_replace($anchor, $inject."\n  ".$anchor, $src);
$tmp = tempnam(sys_get_temp_dir(),'vm').'.php';
file_put_contents($tmp,$src);
$lo=[];$rc=0; exec('php -l '.escapeshellarg($tmp).' 2>&1',$lo,$rc); @unlink($tmp);
if ($rc!==0) { echo "\nLINT HATASI — index.php degistirilmedi:\n  ".implode("\n  ",$lo)."\n"; exit; }
file_put_contents($file.'.bak-vstmore2-'.date('Ymd-His'), @file_get_contents($file));
file_put_contents($file,$src);
echo "  ✓ Vertrag Studio: +6 yeni sozlesme eklendi\n\n✓ CH_VST_MORE_2 uygulandi.\n";
