<?php
/** ChatHelp — apply-fr-expand-more (CH_FR_EXPAND_MORE) — FR katalog genisletme
 *  Workflow ile uretildi: +18 belge, 4 kategori. Deferred injection.
 *  KULLANIM: pull-updates.php?files=apply-fr-expand-more.php */
header('Content-Type: text/plain; charset=UTF-8');
error_reporting(E_ERROR | E_PARSE);
echo "apply-fr-expand-more BASLADI OK (PHP ".PHP_VERSION.")\n\n";
$file = __DIR__.'/index.php';
$src = @file_get_contents($file);
if ($src===false) exit("index.php okunamadi\n");
if (strpos($src,'CH_FR_EXPAND_MORE')!==false) exit("Zaten ekli (CH_FR_EXPAND_MORE).\n");
$anchor="function getDocPrice(dk){ return DOC_TIER[dk]||'standard'; }";
if (strpos($src,$anchor)===false) exit("HATA: anchor (getDocPrice) yok.\n");
$js = <<<'CHJS'

/* CH_FR_EXPAND_MORE — FR katalog genisletme (workflow, deferred) */
try{(function(){
  function Pe(k,l,r,o){var x={k:k,l:l,r:!!r};if(o)x.opts=o;return x;}
  var NEWCATS={
    "frx_surendettement":{n:"Surendettement et difficultés financières",ic:"💳"},
    "frx_copropriete_voisinage":{n:"Copropriété et voisinage",ic:"🏘️"},
    "frx_donnees_personnelles":{n:"Données personnelles (RGPD/CNIL)",ic:"🔐"},
    "frx_succession_pro":{n:"Succession, patrimoine et activité indépendante",ic:"📜"}
  };
  var E={
    "frx_dossier_surendettement_bdf":{ic:"🏦",n:"Dossier de surendettement (saisine de la commission Banque de France)",cat:"frx_surendettement",tier:"komplex",q:[Pe("situation_familiale","Quelle est votre situation familiale ?",true,["Célibataire","Marié(e)","Pacsé(e)","Divorcé(e)","Veuf/Veuve"]),Pe("revenus_mensuels","Quel est le montant total de vos revenus mensuels nets (foyer) ?",true),Pe("charges_mensuelles","Quel est le montant total de vos charges mensuelles fixes (loyer ou crédit immobilier, autres crédits, factures courantes) ?",false),Pe("montant_dettes","Quel est le montant total estimé de vos dettes ?",true),Pe("nombre_creanciers","Combien de créanciers différents avez-vous (banques, organismes de crédit, etc.) ?",true),Pe("statut_logement","Quel est votre statut de logement ?",true,["Locataire","Propriétaire avec crédit en cours","Propriétaire sans crédit","Hébergé à titre gratuit"]),Pe("dossier_anterieur","Avez-vous déjà déposé un dossier de surendettement par le passé ?",false,["Oui","Non"])]},
    "frx_contestation_fichage_ficp":{ic:"📇",n:"Lettre de contestation d'une inscription au FICP",cat:"frx_surendettement",tier:"standard",q:[Pe("organisme","Quel est le nom de la banque ou de l'organisme ayant procédé à l'inscription ?",true),Pe("date_inscription","À quelle date l'inscription au FICP a-t-elle été effectuée (si connue) ?",false),Pe("motif_contestation","Quel est le motif de votre contestation ?",true,["Dette déjà remboursée","Erreur d'identité","Absence de mise en demeure préalable","Délai de conservation dépassé","Autre motif"]),Pe("reference_dossier","Quelle est la référence du dossier ou du contrat concerné ?",false),Pe("preuve_remboursement","Disposez-vous d'un justificatif de remboursement ou de régularisation ?",false,["Oui","Non"])]},
    "frx_demande_delai_paiement_dettes":{ic:"⏳",n:"Demande de délais de paiement pour une dette (article 1343-5 du Code civil)",cat:"frx_surendettement",tier:"standard",q:[Pe("creancier","Qui est le créancier concerné (nom de la personne ou de l'organisme) ?",true),Pe("montant_dette","Quel est le montant total de la dette concernée ?",true),Pe("motif_difficulte","Quelle est la raison de votre difficulté à payer ?",true,["Perte d'emploi","Baisse de revenus","Maladie ou accident","Charges familiales imprévues","Autre"]),Pe("delai_souhaite","Quel délai ou échelonnement souhaitez-vous demander ?",true),Pe("revenus_mensuels","Quel est le montant de vos revenus mensuels nets ?",false)]},
    "frx_contestation_commandement_payer_commissaire_justice":{ic:"⚖️",n:"Contestation d'un commandement de payer délivré par un commissaire de justice (huissier)",cat:"frx_surendettement",tier:"komplex",q:[Pe("type_dette","Quel type de dette est concerné par le commandement de payer ?",true,["Loyer impayé","Crédit à la consommation","Charges de copropriété","Autre dette"]),Pe("date_commandement","À quelle date le commandement de payer vous a-t-il été délivré ou signifié ?",true),Pe("montant_reclame","Quel est le montant réclamé dans le commandement de payer ?",true),Pe("motif_contestation","Sur quel motif portez-vous votre contestation ?",true,["Montant erroné","Dette déjà payée","Absence de titre exécutoire valable","Délai de prescription dépassé","Autre motif"]),Pe("delai_restant","Connaissez-vous le délai légal restant pour régulariser ou saisir le juge ?",false)]},
    "frx_mise_en_demeure_syndic":{ic:"🏢",n:"Mise en demeure du syndic de copropriété (défaut d'entretien ou de travaux)",cat:"frx_copropriete_voisinage",tier:"standard",q:[Pe("nom_syndic","Quel est le nom du syndic de copropriété ?",true),Pe("nature_probleme","Quelle est la nature du problème signalé (travaux, entretien, sécurité, etc.) ?",true),Pe("date_signalement","À quelle date avez-vous signalé ce problème pour la première fois ?",false),Pe("delai_souhaite","Quel délai souhaitez-vous accorder pour l'intervention ?",true),Pe("prejudice_subi","Avez-vous subi un préjudice lié à ce problème (dégâts, gêne, coût) ?",false)]},
    "frx_contestation_charges_copropriete":{ic:"🧾",n:"Contestation de charges de copropriété",cat:"frx_copropriete_voisinage",tier:"standard",q:[Pe("numero_lot","Quel est le numéro de votre lot de copropriété ?",true),Pe("montant_conteste","Quel est le montant des charges que vous contestez ?",true),Pe("motif_contestation","Quel est le motif de votre contestation ?",true,["Erreur de répartition entre lots","Charges non conformes au budget voté","Travaux non votés en assemblée générale","Double facturation","Autre motif"]),Pe("date_ag","À quelle assemblée générale ces charges se rapportent-elles (date) ?",false)]},
    "frx_plainte_nuisances_sonores_voisinage":{ic:"🔊",n:"Lettre pour nuisances sonores de voisinage",cat:"frx_copropriete_voisinage",tier:"einfach",q:[Pe("type_nuisance","Quel type de nuisance sonore constatez-vous ?",true,["Musique ou bruit de fête","Travaux","Aboiements","Bruits de pas ou d'impact","Autre"]),Pe("frequence","À quelle fréquence ces nuisances se produisent-elles ?",true,["Quotidienne","Plusieurs fois par semaine","Occasionnelle","Ponctuelle mais répétée"]),Pe("horaires","À quels horaires ces nuisances surviennent-elles généralement ?",false),Pe("demarches_anterieures","Avez-vous déjà entrepris une démarche amiable ou alerté la police/gendarmerie ?",false,["Oui","Non"]),Pe("adresse_voisin","Quelle est l'adresse du voisin concerné ?",true)]},
    "frx_mise_en_demeure_trouble_voisinage":{ic:"🌳",n:"Mise en demeure pour trouble anormal de voisinage (plantations, écoulement des eaux, odeurs)",cat:"frx_copropriete_voisinage",tier:"standard",q:[Pe("nature_trouble","Quelle est la nature du trouble de voisinage ?",true,["Plantations ou arbres débordants","Écoulement des eaux","Odeurs","Vue ou servitude non respectée","Autre"]),Pe("date_debut","Depuis quand ce trouble existe-t-il ?",true),Pe("prejudice","Quel préjudice ce trouble vous cause-t-il ?",false),Pe("demarches_amiables","Avez-vous déjà tenté une démarche amiable auprès du voisin ?",false,["Oui","Non"]),Pe("delai_conformite","Quel délai souhaitez-vous laisser pour la mise en conformité ?",true)]},
    "frx_demande_convocation_ag_copropriete":{ic:"📋",n:"Demande d'inscription d'une question à l'ordre du jour de l'assemblée générale de copropriété",cat:"frx_copropriete_voisinage",tier:"einfach",q:[Pe("nom_coproprietaire","Quel est votre nom en tant que copropriétaire ?",true),Pe("question_ordre_jour","Quelle question souhaitez-vous voir inscrite à l'ordre du jour ?",true),Pe("justification","Quelle est la justification de cette demande ?",false),Pe("date_ag_prevue","Connaissez-vous la date de la prochaine assemblée générale ?",false)]},
    "frx_demande_acces_donnees_rgpd":{ic:"📂",n:"Demande d'accès à ses données personnelles (article 15 du RGPD)",cat:"frx_donnees_personnelles",tier:"einfach",q:[Pe("organisme","Quel est l'organisme destinataire de la demande ?",true),Pe("type_donnees","Quel type de données personnelles souhaitez-vous consulter ?",false,["Toutes mes données","Données de facturation ou de contrat","Historique de navigation ou de connexion","Données de géolocalisation","Autre"]),Pe("compte_client","Avez-vous un compte client ou un numéro de dossier chez cet organisme ?",false,["Oui","Non"]),Pe("precision_demande","Souhaitez-vous préciser un point particulier de votre demande ?",false)]},
    "frx_demande_effacement_donnees_rgpd":{ic:"🗑️",n:"Demande d'effacement des données personnelles (droit à l'oubli, article 17 du RGPD)",cat:"frx_donnees_personnelles",tier:"standard",q:[Pe("organisme","Quel est l'organisme destinataire de la demande ?",true),Pe("donnees_a_effacer","Quelles données souhaitez-vous faire effacer ?",true),Pe("motif_demande","Quel est le motif de votre demande d'effacement ?",true,["Retrait du consentement","Données non nécessaires au traitement","Opposition au traitement","Traitement illicite","Autre motif"]),Pe("contact_prealable","Avez-vous déjà contacté cet organisme à ce sujet ?",false,["Oui","Non"])]},
    "frx_opposition_prospection_commerciale":{ic:"📵",n:"Opposition au démarchage et à la prospection commerciale (article 21 du RGPD)",cat:"frx_donnees_personnelles",tier:"einfach",q:[Pe("organisme","Quel est l'organisme dont vous souhaitez arrêter les sollicitations ?",true),Pe("type_sollicitation","Quel type de sollicitations recevez-vous ?",true,["Emails","Appels téléphoniques","Courriers postaux","SMS"]),Pe("inscrit_bloctel","Êtes-vous inscrit sur la liste Bloctel ?",false,["Oui","Non","Je ne sais pas"])]},
    "frx_plainte_cnil":{ic:"🚨",n:"Plainte auprès de la CNIL",cat:"frx_donnees_personnelles",tier:"komplex",q:[Pe("organisme_mis_en_cause","Quel est l'organisme mis en cause ?",true),Pe("nature_manquement","Quelle est la nature du manquement constaté ?",true,["Refus de répondre à une demande RGPD","Utilisation abusive des données","Absence de consentement","Fuite ou violation de données","Prospection non désirée persistante","Autre"]),Pe("contact_prealable","Avez-vous déjà contacté l'organisme concerné pour tenter de résoudre le problème ?",true,["Oui","Non"]),Pe("date_faits","À quelle date les faits se sont-ils produits ?",false),Pe("dommage_subi","Quel dommage ou préjudice cela vous a-t-il causé ?",false)]},
    "frx_acceptation_succession_actif_net":{ic:"📑",n:"Acceptation d'une succession à concurrence de l'actif net",cat:"frx_succession_pro",tier:"komplex",q:[Pe("nom_defunt","Quel est le nom du défunt ?",true),Pe("date_deces","Quelle est la date du décès ?",true),Pe("lien_parente","Quel est votre lien de parenté avec le défunt ?",true),Pe("valeur_actif","Quelle est la valeur estimée de l'actif successoral ?",false),Pe("dettes_connues","Avez-vous connaissance de dettes du défunt ?",true,["Oui","Non","Incertain"])]},
    "frx_renonciation_succession":{ic:"✋",n:"Renonciation à une succession",cat:"frx_succession_pro",tier:"standard",q:[Pe("nom_defunt","Quel est le nom du défunt ?",true),Pe("date_deces","Quelle est la date du décès ?",true),Pe("lien_parente","Quel est votre lien de parenté avec le défunt ?",true),Pe("motif_renonciation","Quel est le motif de votre renonciation ?",false,["Succession déficitaire (dettes supérieures à l'actif)","Conflit familial","Absence de lien avec le défunt","Autre motif"]),Pe("autres_heritiers","Y a-t-il d'autres héritiers connus ?",false)]},
    "frx_mise_en_demeure_indivision":{ic:"🏠",n:"Mise en demeure d'un indivisaire (bien indivis issu d'une succession ou autre)",cat:"frx_succession_pro",tier:"standard",q:[Pe("nature_bien","Quelle est la nature du bien indivis concerné ?",true),Pe("quote_part","Quelle est votre quote-part dans l'indivision ?",false),Pe("manquement","Quel manquement reprochez-vous à l'autre indivisaire ?",true,["Loyers ou revenus non partagés","Charges ou impôts impayés","Occupation privative sans compensation","Refus de vendre ou de partager","Autre"]),Pe("delai_souhaite","Quel délai souhaitez-vous accorder pour régulariser la situation ?",true)]},
    "frx_cessation_activite_auto_entrepreneur":{ic:"🧑‍💼",n:"Déclaration de cessation d'activité auto-entrepreneur",cat:"frx_succession_pro",tier:"einfach",q:[Pe("nom_activite","Quel est le nom ou l'objet de votre activité ?",true),Pe("numero_siret","Quel est votre numéro SIRET ?",true),Pe("date_cessation","À quelle date souhaitez-vous que la cessation d'activité prenne effet ?",true),Pe("motif_cessation","Quel est le motif de la cessation d'activité ?",false,["Cessation volontaire","Départ à la retraite","Reconversion professionnelle","Difficultés économiques","Autre motif"])]},
    "frx_mise_en_demeure_facture_impayee_independant":{ic:"💶",n:"Mise en demeure pour facture impayée (activité indépendante / freelance)",cat:"frx_succession_pro",tier:"standard",q:[Pe("nom_client","Quel est le nom du client débiteur (particulier ou entreprise) ?",true),Pe("numero_facture","Quel est le numéro de la facture impayée ?",true),Pe("montant_du","Quel est le montant total dû (TTC) ?",true),Pe("date_echeance","Quelle était la date d'échéance de paiement prévue ?",true),Pe("relances_anterieures","Avez-vous déjà envoyé une ou plusieurs relances amiables à ce client ?",false,["Oui","Non"]),Pe("penalites_prevues","Des pénalités de retard ou une indemnité de recouvrement étaient-elles prévues dans votre devis ou vos conditions générales de vente ?",false,["Oui","Non","Je ne sais pas"])]}
  };
  function inject(){
    try{
      if(typeof DOCS==="undefined"||!DOCS) return false;
      if(typeof CATS==="undefined"||!CATS) return false;
      for(var k in E){ if(!DOCS[k]) DOCS[k]=E[k]; if(typeof DOC_TIER!=="undefined") DOC_TIER[k]=E[k].tier||"standard"; }
      for(var nc in NEWCATS){ if(!CATS[nc]) CATS[nc]={n:NEWCATS[nc].n,ic:NEWCATS[nc].ic,docs:[],country:"FR"}; if(!CATS[nc].docs) CATS[nc].docs=[]; }
      for(var k2 in E){ var c2=E[k2].cat; if(CATS[c2]&&CATS[c2].docs&&CATS[c2].docs.indexOf(k2)<0) CATS[c2].docs.push(k2); }
      if(typeof CAT_LABELS!=="undefined"){ for(var cl in NEWCATS) CAT_LABELS[cl]=NEWCATS[cl].n; }
      if(typeof CAT_DOCS!=="undefined"){
        for(var cd in NEWCATS){ if(!CAT_DOCS[cd]) CAT_DOCS[cd]=[]; }
        for(var k3 in E){ var c3=E[k3].cat; if(CAT_DOCS[c3]){ var ex=false; for(var i=0;i<CAT_DOCS[c3].length;i++){ if(CAT_DOCS[c3][i].k===k3){ex=true;break;} } if(!ex) CAT_DOCS[c3].push({k:k3,ic:E[k3].ic,t:E[k3].n,tier:E[k3].tier||"standard"}); } }
      }
      return !!(DOCS.frx_dossier_surendettement_bdf);
    }catch(e){ return false; }
  }
  var done=false, ticks=0;
  function run(){ if(!done){ if(inject()) done=true; } if(ticks++<40) setTimeout(run,500); }
  if(document.readyState==="loading") document.addEventListener("DOMContentLoaded",run); else run();
})();}catch(e){}

CHJS;
$src=str_replace($anchor,$anchor.$js,$src);
$tmp = tempnam(sys_get_temp_dir(),'fr').'.php';
file_put_contents($tmp,$src);
$lo=[];$rc=0; exec('php -l '.escapeshellarg($tmp).' 2>&1',$lo,$rc); @unlink($tmp);
if ($rc!==0) { echo "\nLINT HATASI — index.php degistirilmedi:\n  ".implode("\n  ",$lo)."\n"; exit; }
file_put_contents($file.'.bak-frmore-'.date('Ymd-His'), @file_get_contents($file));
file_put_contents($file,$src);
echo "  ✓ FR: +18 belge, 4 kategori eklendi\n\n✓ CH_FR_EXPAND_MORE uygulandi.\n";
