<?php
/**
 * ChatHelp — apply-widecat-pl-se (CH_WIDECAT_PLSE) — Genis katalog Batch 3
 *  PL: 36 -> ~74 belge (+38) · 4 yeni kategori (Rodzina/Auto/Zdrowie/Finanse)
 *  SE: 36 -> ~74 belge (+38) · 4 yeni kategori (Familj/Bil/Halsa/Pengar)
 *  Hukuk: PL Kodeks cywilny/pracy, ustawa o prawach konsumenta, KPA,
 *  art. 949 KC testament, ustawa o ubezpieczeniach obowiazkowych ·
 *  SE Jordabalken 12 kap (hyreslagen), LAS, konsumentkoplagen (2022:260),
 *  distansavtalslagen, forvaltningslagen, framtidsfullmakt (2017:310).
 * KULLANIM: pull-updates.php?files=apply-widecat-pl-se.php
 */
header('Content-Type: text/plain; charset=UTF-8');
error_reporting(E_ERROR | E_PARSE);
echo "apply-widecat-pl-se BASLADI OK (PHP ".PHP_VERSION.")\n\n";

$file = __DIR__.'/index.php';
$src = @file_get_contents($file);
if ($src===false) exit("index.php okunamadi\n");
if (strpos($src,'CH_WIDECAT_PLSE')!==false) exit("Zaten ekli (CH_WIDECAT_PLSE).\n");

$fail=[];

/* ═══ [1] PL: kategoriler + X_ORDER ═══ */
$o1 = "    pl_urzedy:{n:\"Urzędy i instytucje\",ic:\"🏛️\"}\n  };\n  var X_ORDER=[\"pl_wypowiedzenia\",\"pl_mieszkanie\",\"pl_praca\",\"pl_konsument\",\"pl_umowy\",\"pl_urzedy\"];";
$n1 = "    pl_urzedy:{n:\"Urzędy i instytucje\",ic:\"🏛️\"},\n"
    . "    pl_rodzina:{n:\"Rodzina i opieka\",ic:\"👪\"},\n"
    . "    pl_auto:{n:\"Auto i transport\",ic:\"🚗\"},\n"
    . "    pl_zdrowie:{n:\"Zdrowie i świadczenia\",ic:\"🏥\"},\n"
    . "    pl_finanse:{n:\"Bank i finanse\",ic:\"💶\"}\n  };\n"
    . "  var X_ORDER=[\"pl_wypowiedzenia\",\"pl_mieszkanie\",\"pl_praca\",\"pl_konsument\",\"pl_umowy\",\"pl_urzedy\",\"pl_rodzina\",\"pl_auto\",\"pl_zdrowie\",\"pl_finanse\"]; /*CH_WIDECAT_PLSE*/";
$c=0; $src=str_replace($o1,$n1,$src,$c);
echo ($c===1?"  ✓ [1] PL +4 kategori\n":"  ✗ [1] PL XC anchor ($c)\n"); if($c!==1)$fail[]=1;

/* ═══ [2] PL: +38 belge ═══ */
$plDocs = <<<'JS'
    /* CH_WIDECAT_PLSE — szeroki katalog */
    pl_wypow_prad:{ic:"⚡",n:"Wypowiedzenie umowy — prąd/gaz (zmiana sprzedawcy)",cat:"pl_wypowiedzenia",tier:"einfach",q:[Pq("dostawca","Sprzedawca: nazwa i adres",true),Pq("nr_klienta","Numer klienta / PPE",true),Pq("termin","Termin rozwiązania",false,["Najbliższy możliwy","Konkretna data"]),Pq("dane","Pana/Pani dane: imię, nazwisko, adres",true)]},
    pl_wypow_prasa:{ic:"📰",n:"Rezygnacja z prenumeraty/usługi",cat:"pl_wypowiedzenia",tier:"einfach",q:[Pq("firma","Firma: nazwa i adres",true),Pq("nr","Numer klienta/prenumeraty",true),Pq("termin","Termin rezygnacji",true),Pq("dane","Pana/Pani dane: imię, nazwisko, adres",true)]},
    pl_wystapienie_stow:{ic:"🤝",n:"Wystąpienie ze stowarzyszenia/klubu",cat:"pl_wypowiedzenia",tier:"einfach",q:[Pq("stow","Stowarzyszenie: nazwa i adres",true),Pq("nr","Numer członkowski (jeśli jest)",false),Pq("termin","Data wystąpienia (wg statutu)",true),Pq("dane","Pana/Pani dane: imię, nazwisko, adres",true)]},
    pl_cofniecie_zgody_sepa:{ic:"🏦",n:"Cofnięcie zgody na polecenie zapłaty",cat:"pl_wypowiedzenia",tier:"einfach",q:[Pq("odbiorca","Odbiorca płatności: nazwa i adres",true),Pq("identyfikator","Identyfikator zgody / nr klienta",true),Pq("bank","Poinformować także bank?",false,["Tak","Nie"]),Pq("dane","Pana/Pani dane: imię, nazwisko, adres",true)]},
    pl_obnizka_czynszu:{ic:"📉",n:"Obniżenie czynszu z powodu wad lokalu",cat:"pl_mieszkanie",tier:"standard",q:[Pq("wynajmujacy","Wynajmujący: imię, nazwisko/nazwa i adres",true),Pq("lokal","Adres lokalu",true),Pq("wada","Wada (od kiedy, zakres)",true),Pq("zgloszona","Czy zgłaszana wcześniej?",true,["Tak, pisemnie","Tak, ustnie","Nie"]),Pq("kwota","Żądana obniżka (% lub zł)",false),Pq("dane","Pana/Pani dane: imię i nazwisko",true)]},
    pl_zgloszenie_usterki:{ic:"🔧",n:"Zgłoszenie usterki wynajmującemu",cat:"pl_mieszkanie",tier:"einfach",q:[Pq("wynajmujacy","Wynajmujący: imię, nazwisko/nazwa i adres",true),Pq("lokal","Adres lokalu",true),Pq("usterka","Usterka i skutki",true),Pq("termin","Termin naprawy (np. 14 dni)",true),Pq("dane","Pana/Pani dane: imię i nazwisko",true)]},
    pl_zwrot_kaucji:{ic:"💰",n:"Zwrot kaucji mieszkaniowej",cat:"pl_mieszkanie",tier:"einfach",q:[Pq("wynajmujacy","Wynajmujący: imię, nazwisko/nazwa i adres",true),Pq("lokal","Adres (byłego) lokalu",true),Pq("wydanie","Data zdania lokalu/kluczy",true),Pq("kaucja","Kwota kaucji (zł, zwrot w ciągu miesiąca)",true),Pq("konto","Numer rachunku do zwrotu",true),Pq("dane","Pana/Pani dane: imię, nazwisko, nowy adres",true)]},
    pl_wypow_najmu:{ic:"🏠",n:"Wypowiedzenie umowy najmu (najemca)",cat:"pl_mieszkanie",tier:"einfach",q:[Pq("wynajmujacy","Wynajmujący: imię, nazwisko/nazwa i adres",true),Pq("lokal","Adres lokalu",true),Pq("termin","Termin wypowiedzenia (wg umowy, najczęściej 1–3 mies.)",true),Pq("dane","Pana/Pani dane: imię i nazwisko",true)]},
    pl_protokol_zdawczy:{ic:"📋",n:"Protokół zdawczo-odbiorczy lokalu",cat:"pl_mieszkanie",tier:"einfach",q:[Pq("okazja","Okazja",true,["Wprowadzenie","Zdanie lokalu"]),Pq("lokal","Adres lokalu",true),Pq("stan","Stan pomieszczeń / usterki",true),Pq("liczniki","Stany liczników (prąd, gaz, woda)",false),Pq("klucze","Przekazane klucze (liczba)",false),Pq("strony","Imiona i nazwiska obu stron",true)]},
    pl_swiadectwo_pracy:{ic:"📜",n:"Wniosek o sprostowanie świadectwa pracy",cat:"pl_praca",tier:"standard",q:[Pq("pracodawca","Pracodawca: nazwa i adres",true),Pq("swiadectwo","Świadectwo z dnia (termin wniosku: 14 dni)",true),Pq("blad","Co jest błędne i jak powinno brzmieć",true),Pq("dane","Pana/Pani dane: imię, nazwisko, adres",true)]},
    pl_wypow_pracownika:{ic:"📤",n:"Wypowiedzenie umowy o pracę (pracownik)",cat:"pl_praca",tier:"einfach",q:[Pq("pracodawca","Pracodawca: nazwa i adres",true),Pq("termin","Okres wypowiedzenia (wg stażu: 2 tyg./1 mies./3 mies.)",true),Pq("dane","Pana/Pani dane: imię, nazwisko, stanowisko",true)]},
    pl_zaleglosc_wynagrodzenie:{ic:"💶",n:"Wezwanie do zapłaty zaległego wynagrodzenia",cat:"pl_praca",tier:"standard",q:[Pq("pracodawca","Pracodawca: nazwa i adres",true),Pq("kwoty","Zaległości (miesiące, kwoty)",true),Pq("termin","Termin zapłaty (np. 7 dni; potem PIP/sąd pracy)",true),Pq("dane","Pana/Pani dane: imię, nazwisko, adres",true)]},
    pl_urlop_rodzicielski:{ic:"👶",n:"Wniosek o urlop rodzicielski",cat:"pl_praca",tier:"standard",q:[Pq("pracodawca","Pracodawca: nazwa i adres",true),Pq("dziecko","Dziecko: data urodzenia",true),Pq("okres","Wnioskowany okres (do 41/43 tygodni łącznie)",true),Pq("dane","Pana/Pani dane: imię i nazwisko",true)]},
    pl_odwolanie_wypowiedzenia:{ic:"⚖️",n:"Odwołanie od wypowiedzenia (sąd pracy, 21 dni)",cat:"pl_praca",tier:"komplex",q:[Pq("pracodawca","Pracodawca: nazwa i adres",true),Pq("wypowiedzenie","Wypowiedzenie doręczone dnia (termin: 21 dni!)",true),Pq("przyczyna","Podana przyczyna",true),Pq("zarzuty","Dlaczego wypowiedzenie jest wadliwe (własnymi słowami)",true),Pq("zadanie","Żądanie",true,["Przywrócenie do pracy","Odszkodowanie"]),Pq("dane","Pana/Pani dane: imię, nazwisko, adres",true)]},
    pl_niezgodnosc_towaru:{ic:"📦",n:"Reklamacja: towar niezgodny z umową",cat:"pl_konsument",tier:"standard",q:[Pq("sprzedawca","Sprzedawca: nazwa i adres",true),Pq("zakup","Data zakupu / nr paragonu",true),Pq("towar","Towar i cena",true),Pq("wada","Opis niezgodności",true),Pq("zadanie","Żądanie",true,["Naprawa","Wymiana","Obniżenie ceny","Odstąpienie (zwrot pieniędzy)"]),Pq("dane","Pana/Pani dane: imię, nazwisko, adres",true)]},
    pl_odstapienie_14dni:{ic:"🛒",n:"Odstąpienie od umowy zawartej na odległość (14 dni)",cat:"pl_konsument",tier:"einfach",q:[Pq("sprzedawca","Sprzedawca: nazwa i adres/e-mail",true),Pq("zamowienie","Numer zamówienia / data",true),Pq("odbior","Towar odebrany dnia",true),Pq("zwrot","Zwrot towaru",false,["Wysyłka","Odbiór przez sprzedawcę"]),Pq("dane","Pana/Pani dane: imię, nazwisko, adres",true)]},
    pl_odszkodowanie_lot:{ic:"✈️",n:"Odszkodowanie za lot (WE 261/2004)",cat:"pl_konsument",tier:"standard",q:[Pq("linia","Linia lotnicza",true),Pq("lot","Numer lotu i data",true),Pq("trasa","Trasa (z – do)",true),Pq("problem","Co się stało?",true,["Opóźnienie 3+ godz.","Odwołanie","Odmowa przyjęcia na pokład"]),Pq("rezerwacja","Numer rezerwacji",true),Pq("dane","Pana/Pani dane: imię, nazwisko, adres",true)]},
    pl_windykacja_sprzeciw:{ic:"📮",n:"Sprzeciw wobec wezwania windykacyjnego",cat:"pl_konsument",tier:"standard",q:[Pq("firma","Firma windykacyjna: nazwa i adres",true),Pq("sygnatura","Sygnatura sprawy",true),Pq("roszczenie","Żądana kwota i rzekoma podstawa",true),Pq("zarzut","Pana/Pani zarzut",true,["Roszczenie nie istnieje","Już zapłacone","Zawyżone koszty","Przedawnione"]),Pq("dane","Pana/Pani dane: imię, nazwisko, adres",true)]},
    pl_umowa_sprzedazy:{ic:"🛍️",n:"Umowa sprzedaży między osobami prywatnymi",cat:"pl_umowy",tier:"einfach",q:[Pq("rola","Pan/Pani jest",true,["Sprzedającym","Kupującym"]),Pq("strona","Druga strona: imię, nazwisko, adres",true),Pq("rzecz","Przedmiot sprzedaży (dokładnie)",true),Pq("cena","Cena (zł) i sposób zapłaty",true),Pq("wydanie","Data/miejsce wydania",true)]},
    pl_umowa_pozyczki:{ic:"💸",n:"Umowa pożyczki prywatnej",cat:"pl_umowy",tier:"standard",q:[Pq("rola","Pan/Pani jest",true,["Pożyczkodawcą","Pożyczkobiorcą"]),Pq("strona","Druga strona: imię, nazwisko, adres",true),Pq("kwota","Kwota (zł; powyżej 1000 zł forma dokumentowa)",true),Pq("splata","Spłata (raty/termin)",true),Pq("odsetki","Odsetki",false,["Bez odsetek","Z odsetkami (% rocznie)"])]},
    pl_uzyczenie:{ic:"🤲",n:"Umowa użyczenia",cat:"pl_umowy",tier:"einfach",q:[Pq("rola","Pan/Pani jest",true,["Użyczającym","Biorącym w użyczenie"]),Pq("strona","Druga strona: imię, nazwisko, adres",true),Pq("rzecz","Użyczana rzecz (stan)",true),Pq("okres","Okres (od – do)",true)]},
    pl_umowa_dzielo:{ic:"🔨",n:"Umowa o dzieło (drobne prace)",cat:"pl_umowy",tier:"standard",q:[Pq("rola","Pan/Pani jest",true,["Zamawiającym","Wykonawcą"]),Pq("strona","Druga strona: imię, nazwisko, adres",true),Pq("dzielo","Opis dzieła/prac",true),Pq("wynagrodzenie","Wynagrodzenie (zł, ryczałt lub kosztorys)",true),Pq("termin","Termin wykonania",true),Pq("material","Kto dostarcza materiały?",false,["Wykonawca","Zamawiający"])]},
    pl_odwolanie_kpa:{ic:"⚖️",n:"Odwołanie od decyzji (KPA, 14 dni)",cat:"pl_urzedy",tier:"komplex",q:[Pq("organ","Organ, który wydał decyzję: nazwa i adres",true),Pq("decyzja","Decyzja z dnia (znak sprawy)",true),Pq("doreczona","Doręczona dnia (termin: 14 dni!)",true),Pq("tresc","Co rozstrzygnięto?",true),Pq("zarzuty","Dlaczego decyzja jest błędna (własnymi słowami)",true),Pq("dane","Pana/Pani dane: imię, nazwisko, adres",true)]},
    pl_dostep_informacji:{ic:"🗂️",n:"Wniosek o informację publiczną",cat:"pl_urzedy",tier:"einfach",q:[Pq("organ","Organ/urząd: nazwa i adres",true),Pq("zakres","Jakie informacje/dokumenty (jak najdokładniej)",true),Pq("forma","Forma udostępnienia",false,["E-mail","Kopia papierowa","Wgląd"]),Pq("dane","Pana/Pani dane: imię, nazwisko, adres",true)]},
    pl_raty_us:{ic:"🧾",n:"Wniosek o rozłożenie podatku na raty",cat:"pl_urzedy",tier:"standard",q:[Pq("urzad","Urząd skarbowy",true),Pq("naleznosc","Rodzaj i kwota zaległości (zł)",true),Pq("raty","Proponowana liczba i wysokość rat",true),Pq("uzasadnienie","Ważny interes podatnika (krótko)",true),Pq("dane","Pana/Pani dane: imię, nazwisko, adres, PESEL/NIP",true)]},
    pl_pelnomocnictwo:{ic:"📝",n:"Pełnomocnictwo (ogólne)",cat:"pl_rodzina",tier:"einfach",q:[Pq("pelnomocnik","Pełnomocnik: imię, nazwisko, data urodzenia, adres",true),Pq("zakres","Zakres umocowania",true,["Jedna sprawa","Sprawy urzędowe","Sprawy bankowe","Ogólne"]),Pq("szczegoly","Dokładniejszy opis",true),Pq("okres","Okres obowiązywania",false,["Bezterminowo","Do dnia"]),Pq("dane","Pana/Pani dane: imię, nazwisko, data urodzenia, adres",true)]},
    pl_testament:{ic:"📜",n:"Testament własnoręczny (projekt, art. 949 KC)",cat:"pl_rodzina",tier:"komplex",q:[Pq("spadkobiercy","Spadkobiercy i udziały/składniki",true),Pq("zapisy","Zapisy szczególne (opcjonalnie)",false),Pq("dane","Pana/Pani dane: imię, nazwisko, data urodzenia",true),Pq("uwaga","Uwaga: ważny TYLKO w całości pismem ręcznym, z datą i podpisem; pamiętać o zachowku",false)]},
    pl_alimenty_wezwanie:{ic:"👨‍👧",n:"Wezwanie do zapłaty alimentów",cat:"pl_rodzina",tier:"standard",q:[Pq("zobowiazany","Zobowiązany: imię, nazwisko, adres",true),Pq("tytul","Tytuł (wyrok/ugoda z dnia)",true),Pq("zaleglosc","Zaległość (miesiące, kwota)",true),Pq("termin","Termin zapłaty (np. 7 dni; potem komornik)",true),Pq("dane","Pana/Pani dane: imię, nazwisko, adres",true)]},
    pl_zgoda_wyjazd_dziecka:{ic:"🧳",n:"Zgoda na wyjazd dziecka za granicę",cat:"pl_rodzina",tier:"einfach",q:[Pq("dziecko","Dziecko: imię, nazwisko, data urodzenia, nr dokumentu",true),Pq("opiekun","Osoba towarzysząca: imię, nazwisko, nr dokumentu",true),Pq("wyjazd","Kraj i termin wyjazdu",true),Pq("dane","Rodzic/e wyrażający zgodę: imię, nazwisko, nr dokumentu",true),Pq("uwaga","Uwaga: zalecane poświadczenie notarialne podpisu",false)]},
    pl_umowa_auto:{ic:"🚗",n:"Umowa kupna-sprzedaży samochodu",cat:"pl_auto",tier:"standard",q:[Pq("rola","Pan/Pani jest",true,["Sprzedającym","Kupującym"]),Pq("strona","Druga strona: imię, nazwisko, adres, PESEL",true),Pq("pojazd","Marka, model, VIN, nr rejestracyjny",true),Pq("rok","Rok produkcji i przebieg",true),Pq("cena","Cena (zł; PCC-3 w 14 dni po stronie kupującego)",true),Pq("wady","Znane wady",false)]},
    pl_uchylenie_mandatu:{ic:"🚦",n:"Wniosek o uchylenie mandatu (7 dni, sąd)",cat:"pl_auto",tier:"komplex",q:[Pq("mandat","Seria i numer mandatu, z dnia",true),Pq("organ","Kto nałożył (policja/straż miejska)",true),Pq("wykroczenie","Zarzucane wykroczenie",true),Pq("powody","Dlaczego mandat jest niezasadny (własnymi słowami)",true),Pq("dane","Pana/Pani dane: imię, nazwisko, adres",true)]},
    pl_wypow_oc:{ic:"🛡️",n:"Wypowiedzenie OC (ubezpieczenie komunikacyjne)",cat:"pl_auto",tier:"einfach",q:[Pq("zaklad","Zakład ubezpieczeń: nazwa i adres",true),Pq("polisa","Numer polisy",true),Pq("powod","Podstawa",true,["Koniec okresu (najpóźniej 1 dzień przed)","Podwójne OC","Zakup pojazdu (OC zbywcy)"]),Pq("pojazd","Pojazd: marka, nr rejestracyjny",true),Pq("dane","Pana/Pani dane: imię, nazwisko, adres",true)]},
    pl_szkoda_ubezpieczyciel:{ic:"💥",n:"Zgłoszenie szkody ubezpieczycielowi",cat:"pl_auto",tier:"einfach",q:[Pq("zaklad","Ubezpieczyciel: nazwa i adres",true),Pq("polisa","Numer polisy",true),Pq("zdarzenie","Zdarzenie: data, miejsce, przebieg",true),Pq("szkoda","Zakres szkody",true),Pq("sprawca","Sprawca (imię, nazwisko, nr rej., ubezpieczyciel)",false),Pq("dane","Pana/Pani dane: imię, nazwisko, adres",true)]},
    pl_odwolanie_zus:{ic:"🏥",n:"Odwołanie od decyzji ZUS (miesiąc)",cat:"pl_zdrowie",tier:"komplex",q:[Pq("decyzja","Decyzja ZUS z dnia (znak)",true),Pq("doreczona","Doręczona dnia (termin: miesiąc!)",true),Pq("przedmiot","Przedmiot",true,["Renta","Emerytura","Zasiłek chorobowy","Świadczenie rehabilitacyjne","Inne"]),Pq("zarzuty","Dlaczego decyzja jest błędna",true),Pq("dane","Pana/Pani dane: imię, nazwisko, adres, PESEL",true)]},
    pl_wniosek_500:{ic:"🍼",n:"Świadczenie wychowawcze / rodzinne — pismo",cat:"pl_zdrowie",tier:"einfach",q:[Pq("sprawa","Sprawa",true,["Wniosek","Uzupełnienie dokumentów","Zapytanie o stan sprawy"]),Pq("dziecko","Dziecko: imię, nazwisko, data urodzenia",true),Pq("szczegoly","Szczegóły",true),Pq("dane","Pana/Pani dane: imię, nazwisko, adres, PESEL",true)]},
    pl_zwrot_kosztow_leczenia:{ic:"🩺",n:"Wniosek o zwrot kosztów leczenia",cat:"pl_zdrowie",tier:"einfach",q:[Pq("platnik","NFZ/ubezpieczyciel: nazwa i adres",true),Pq("swiadczenie","Świadczenie: placówka, data, rodzaj",true),Pq("kwota","Kwota (zł, faktura w załączeniu)",true),Pq("konto","Numer rachunku",true),Pq("dane","Pana/Pani dane: imię, nazwisko, adres, PESEL",true)]},
    pl_zamkniecie_konta:{ic:"🏦",n:"Wypowiedzenie umowy rachunku bankowego",cat:"pl_finanse",tier:"einfach",q:[Pq("bank","Bank: nazwa i adres",true),Pq("rachunek","Numer rachunku do zamknięcia",true),Pq("saldo","Saldo przelać na (numer rachunku)",true),Pq("termin","Termin",false,["Niezwłocznie","Z dniem"]),Pq("dane","Pana/Pani dane: imię, nazwisko, adres",true)]},
    pl_wczesniejsza_splata:{ic:"💳",n:"Wcześniejsza spłata kredytu (zwrot kosztów)",cat:"pl_finanse",tier:"standard",q:[Pq("bank","Kredytodawca: nazwa i adres",true),Pq("umowa","Umowa nr z dnia",true),Pq("zakres","Spłata",true,["Całkowita","Częściowa (kwota)"]),Pq("rozliczenie","Żądać proporcjonalnego zwrotu kosztów (prowizji)?",false,["Tak","Nie"]),Pq("dane","Pana/Pani dane: imię, nazwisko, adres",true)]},
    pl_reklamacja_transakcji:{ic:"🧾",n:"Reklamacja nieautoryzowanej transakcji",cat:"pl_finanse",tier:"standard",q:[Pq("bank","Bank/wydawca karty: nazwa i adres",true),Pq("transakcja","Transakcja (data, kwota, odbiorca)",true),Pq("powod","Powód",true,["Nigdy nie autoryzowana","Błędna kwota","Podwójne obciążenie","Oszustwo/phishing"]),Pq("blokada","Karta już zastrzeżona?",false,["Tak","Nie"]),Pq("dane","Pana/Pani dane: imię, nazwisko, adres",true)]},
JS;
$o2 = "var CCODE=\"PL\", DOCWORD=\"dokumentów\";\n\n  var D={";
$n2 = "var CCODE=\"PL\", DOCWORD=\"dokumentów\";\n\n  var D={\n".$plDocs;
$c=0; $src=str_replace($o2,$n2,$src,$c);
echo ($c===1?"  ✓ [2] PL +38 belge\n":"  ✗ [2] PL D anchor ($c)\n"); if($c!==1)$fail[]=2;

/* ═══ [3] SE: kategoriler + X_ORDER ═══ */
$o3 = "    se_myndigheter:{n:\"Myndigheter\",ic:\"🏛️\"}\n  };\n  var X_ORDER=[\"se_uppsagningar\",\"se_boende\",\"se_arbete\",\"se_konsument\",\"se_avtal\",\"se_myndigheter\"];";
$n3 = "    se_myndigheter:{n:\"Myndigheter\",ic:\"🏛️\"},\n"
    . "    se_familj:{n:\"Familj & Framtid\",ic:\"👪\"},\n"
    . "    se_bil:{n:\"Bil & Trafik\",ic:\"🚗\"},\n"
    . "    se_halsa:{n:\"Hälsa & Ersättningar\",ic:\"🏥\"},\n"
    . "    se_pengar:{n:\"Bank & Pengar\",ic:\"💶\"}\n  };\n"
    . "  var X_ORDER=[\"se_uppsagningar\",\"se_boende\",\"se_arbete\",\"se_konsument\",\"se_avtal\",\"se_myndigheter\",\"se_familj\",\"se_bil\",\"se_halsa\",\"se_pengar\"]; /*CH_WIDECAT_PLSE*/";
$c=0; $src=str_replace($o3,$n3,$src,$c);
echo ($c===1?"  ✓ [3] SE +4 kategori\n":"  ✗ [3] SE XC anchor ($c)\n"); if($c!==1)$fail[]=3;

/* ═══ [4] SE: +38 belge ═══ */
$seDocs = <<<'JS'
    /* CH_WIDECAT_PLSE — bred katalog */
    se_el_uppsagning:{ic:"⚡",n:"Säga upp elavtal (byte av leverantör)",cat:"se_uppsagningar",tier:"einfach",q:[Pq("bolag","Elbolag: namn och adress",true),Pq("kundnr","Kundnummer / anläggnings-ID",true),Pq("datum","Önskat slutdatum",false,["Snarast möjligt","Visst datum"]),Pq("uppgifter","Dina uppgifter: namn och adress",true)]},
    se_tidning_uppsagning:{ic:"📰",n:"Säga upp prenumeration",cat:"se_uppsagningar",tier:"einfach",q:[Pq("bolag","Företag: namn och adress",true),Pq("prenr","Prenumerations-/kundnummer",true),Pq("datum","Uppsägningsdatum",true),Pq("uppgifter","Dina uppgifter: namn och adress",true)]},
    se_forening_uttrade:{ic:"🤝",n:"Utträde ur förening",cat:"se_uppsagningar",tier:"einfach",q:[Pq("forening","Förening: namn och adress",true),Pq("medlemsnr","Medlemsnummer (om det finns)",false),Pq("datum","Utträdesdatum (enligt stadgarna)",true),Pq("uppgifter","Dina uppgifter: namn och adress",true)]},
    se_autogiro_aterkallelse:{ic:"🏦",n:"Återkalla autogiromedgivande",cat:"se_uppsagningar",tier:"einfach",q:[Pq("mottagare","Betalningsmottagare: namn och adress",true),Pq("referens","Medgivandereferens / kundnummer",true),Pq("bank","Meddela även banken?",false,["Ja","Nej"]),Pq("uppgifter","Dina uppgifter: namn och adress",true)]},
    se_hyresreduktion:{ic:"📉",n:"Hyresnedsättning vid brister (12 kap. JB)",cat:"se_boende",tier:"standard",q:[Pq("hyresvard","Hyresvärd: namn och adress",true),Pq("bostad","Bostadens adress",true),Pq("brist","Brist (sedan när, omfattning)",true),Pq("anmald","Redan anmäld?",true,["Ja, skriftligt","Ja, muntligt","Nej"]),Pq("nedsattning","Begärd nedsättning (% eller kr)",false),Pq("uppgifter","Dina uppgifter: namn",true)]},
    se_felanmalan:{ic:"🔧",n:"Felanmälan till hyresvärden",cat:"se_boende",tier:"einfach",q:[Pq("hyresvard","Hyresvärd: namn och adress",true),Pq("bostad","Bostadens adress",true),Pq("fel","Fel och konsekvenser",true),Pq("frist","Tid för åtgärd (t.ex. 14 dagar)",true),Pq("uppgifter","Dina uppgifter: namn",true)]},
    se_deposition_ater:{ic:"💰",n:"Återbetalning av deposition",cat:"se_boende",tier:"einfach",q:[Pq("hyresvard","Hyresvärd: namn och adress",true),Pq("bostad","(F.d.) bostadens adress",true),Pq("utflytt","Utflyttnings-/avlämningsdatum",true),Pq("belopp","Depositionsbelopp (kr)",true),Pq("konto","Ditt konto (clearing + kontonummer)",true),Pq("uppgifter","Dina uppgifter: namn och ny adress",true)]},
    se_hyra_uppsagning:{ic:"🏠",n:"Uppsägning av hyresavtal (hyresgäst, 3 mån)",cat:"se_boende",tier:"einfach",q:[Pq("hyresvard","Hyresvärd: namn och adress",true),Pq("bostad","Bostadens adress",true),Pq("datum","Avflyttning (3 kalendermånader från månadsskifte)",true),Pq("uppgifter","Dina uppgifter: namn",true)]},
    se_besiktningsprotokoll:{ic:"📋",n:"Besiktningsprotokoll (in-/utflytt)",cat:"se_boende",tier:"einfach",q:[Pq("tillfalle","Tillfälle",true,["Inflytt","Utflytt"]),Pq("bostad","Bostadens adress",true),Pq("skick","Skick per rum / brister",true),Pq("nycklar","Överlämnade nycklar (antal)",false),Pq("parter","Båda parters namn",true)]},
    se_arbetsgivarintyg:{ic:"📜",n:"Begära arbetsgivarintyg",cat:"se_arbete",tier:"einfach",q:[Pq("arbetsgivare","Arbetsgivare: namn och adress",true),Pq("period","Anställd från – till",true),Pq("befattning","Befattning",true),Pq("andamal","Ändamål",false,["A-kassa","Nytt arbete","Annat"]),Pq("uppgifter","Dina uppgifter: namn och adress",true)]},
    se_egen_uppsagning:{ic:"📤",n:"Egen uppsägning (arbetstagare)",cat:"se_arbete",tier:"einfach",q:[Pq("arbetsgivare","Arbetsgivare: namn och adress",true),Pq("datum","Sista anställningsdag (uppsägningstid enl. LAS/avtal, oftast 1 mån)",true),Pq("intyg","Begära tjänstgöringsintyg samtidigt?",false,["Ja","Nej"]),Pq("uppgifter","Dina uppgifter: namn och adress",true)]},
    se_lonekrav:{ic:"💶",n:"Krav på obetald lön",cat:"se_arbete",tier:"standard",q:[Pq("arbetsgivare","Arbetsgivare: namn och adress",true),Pq("belopp","Utestående (månader, belopp)",true),Pq("frist","Betalningsfrist (t.ex. 10 dagar)",true),Pq("uppgifter","Dina uppgifter: namn och adress",true)]},
    se_foraldraledighet:{ic:"👶",n:"Anmälan om föräldraledighet (2 mån innan)",cat:"se_arbete",tier:"standard",q:[Pq("arbetsgivare","Arbetsgivare: namn och adress",true),Pq("barn","Barn: födelsedatum/beräknad födsel",true),Pq("period","Önskad period och omfattning",true),Pq("uppgifter","Dina uppgifter: namn",true)]},
    se_ogiltigforklaring:{ic:"⚖️",n:"Invändning mot uppsägning (LAS, 14 dagar)",cat:"se_arbete",tier:"komplex",q:[Pq("arbetsgivare","Arbetsgivare: namn och adress",true),Pq("uppsagning","Uppsägning mottagen den (ogiltigförklaring: 14 dagar!)",true),Pq("grund","Angiven grund",true),Pq("invandning","Varför saknas saklig grund (egna ord)",true),Pq("uppgifter","Dina uppgifter: namn och adress",true)]},
    se_reklamation_vara:{ic:"📦",n:"Reklamation av felaktig vara (konsumentköplagen)",cat:"se_konsument",tier:"standard",q:[Pq("saljare","Säljare: namn och adress",true),Pq("kop","Köpt den / kvittonummer",true),Pq("vara","Vara och pris",true),Pq("fel","Felet (reklamationsrätt 3 år)",true),Pq("krav","Ditt krav",true,["Avhjälpande (reparation)","Omleverans","Prisavdrag","Hävning (pengarna tillbaka)"]),Pq("uppgifter","Dina uppgifter: namn och adress",true)]},
    se_angerratt:{ic:"🛒",n:"Ångerrätt distansköp (14 dagar)",cat:"se_konsument",tier:"einfach",q:[Pq("saljare","Säljare: namn och adress/e-post",true),Pq("order","Ordernummer / datum",true),Pq("mottagen","Varan mottagen den",true),Pq("retur","Retur via",false,["Postas","Hämtning önskas"]),Pq("uppgifter","Dina uppgifter: namn och adress",true)]},
    se_flygersattning:{ic:"✈️",n:"Flygersättning (EU 261/2004)",cat:"se_konsument",tier:"standard",q:[Pq("bolag","Flygbolag",true),Pq("flyg","Flightnummer och datum",true),Pq("stracka","Sträcka (från – till)",true),Pq("problem","Vad hände?",true,["Försening 3+ timmar","Inställt flyg","Nekad ombordstigning"]),Pq("bokning","Bokningsnummer",true),Pq("uppgifter","Dina uppgifter: namn och adress",true)]},
    se_bestrida_faktura:{ic:"📮",n:"Bestrida faktura / inkassokrav",cat:"se_konsument",tier:"standard",q:[Pq("avsandare","Företag/inkassobolag: namn och adress",true),Pq("referens","Faktura-/ärendenummer",true),Pq("belopp","Krävt belopp och påstådd grund",true),Pq("invandning","Din invändning",true,["Kravet saknar grund","Redan betalt","För högt belopp/avgifter","Preskriberat"]),Pq("uppgifter","Dina uppgifter: namn och adress",true)]},
    se_kopeavtal_privat:{ic:"🛍️",n:"Köpeavtal mellan privatpersoner",cat:"se_avtal",tier:"einfach",q:[Pq("roll","Du är",true,["Säljare","Köpare"]),Pq("motpart","Motpart: namn och adress",true),Pq("vara","Såld egendom (noggrant)",true),Pq("pris","Pris (kr) och betalningssätt",true),Pq("leverans","Datum/plats för överlämning",true),Pq("befintligt","Säljs i befintligt skick?",false,["Ja","Nej"])]},
    se_skuldebrev:{ic:"💸",n:"Skuldebrev (privat lån)",cat:"se_avtal",tier:"standard",q:[Pq("roll","Du är",true,["Långivare","Låntagare"]),Pq("motpart","Motpart: namn och adress",true),Pq("belopp","Belopp (kr)",true),Pq("aterbetalning","Återbetalning (avbetalning/förfallodag)",true),Pq("ranta","Ränta",false,["Räntefritt","Med ränta (% per år)"])]},
    se_laneavtal_sak:{ic:"🤲",n:"Låneavtal (sak, vederlagsfritt)",cat:"se_avtal",tier:"einfach",q:[Pq("roll","Du är",true,["Utlånare","Låntagare"]),Pq("motpart","Motpart: namn och adress",true),Pq("sak","Utlånad sak (skick)",true),Pq("period","Period (från – till)",true),Pq("ersattning","Ersättning vid skada?",false,["Ja, dagsvärde","Nej"])]},
    se_hantverkaravtal:{ic:"🔨",n:"Avtal om hantverkstjänst",cat:"se_avtal",tier:"standard",q:[Pq("roll","Du är",true,["Beställare","Utförare"]),Pq("motpart","Motpart: namn och adress",true),Pq("arbete","Beskrivning av arbetet",true),Pq("pris","Pris (kr, fast eller löpande)",true),Pq("klart","Färdigdatum",true),Pq("material","Vem står för material?",false,["Utföraren","Beställaren"])]},
    se_overklagande:{ic:"⚖️",n:"Överklagande av myndighetsbeslut (3 veckor)",cat:"se_myndigheter",tier:"komplex",q:[Pq("myndighet","Myndighet: namn och adress",true),Pq("beslut","Beslut den (diarienummer)",true),Pq("mottaget","Del av beslutet den (frist: 3 veckor!)",true),Pq("innehall","Vad beslutades?",true),Pq("skal","Varför är beslutet fel (egna ord)",true),Pq("uppgifter","Dina uppgifter: namn och adress",true)]},
    se_handling_begaran:{ic:"🗂️",n:"Begäran om allmän handling (offentlighetsprincipen)",cat:"se_myndigheter",tier:"einfach",q:[Pq("myndighet","Myndighet: namn och adress",true),Pq("handlingar","Vilka handlingar (så exakt som möjligt)",true),Pq("form","Form",false,["E-post","Papperskopia","Ta del på plats"]),Pq("uppgifter","Dina uppgifter (frivilligt vid begäran)",false)]},
    se_anstand_skatt:{ic:"🧾",n:"Anstånd/avbetalning hos Skatteverket",cat:"se_myndigheter",tier:"standard",q:[Pq("skuld","Skatteslag och belopp (kr)",true),Pq("forslag","Föreslagen månadsbetalning (kr)",true),Pq("skal","Skäl (tillfälliga betalningssvårigheter)",true),Pq("uppgifter","Dina uppgifter: namn, adress, personnummer",true)]},
    se_fullmakt:{ic:"📝",n:"Fullmakt (allmän)",cat:"se_familj",tier:"einfach",q:[Pq("fullmaktig","Fullmäktig: namn, personnummer, adress",true),Pq("omfattning","Vad gäller fullmakten?",true,["Ett ärende","Myndighetskontakter","Bankärenden","Generell"]),Pq("detaljer","Närmare beskrivning",true),Pq("giltighet","Giltighetstid",false,["Tills vidare","Till datum"]),Pq("uppgifter","Dina uppgifter: namn, personnummer, adress",true)]},
    se_framtidsfullmakt:{ic:"🛡️",n:"Framtidsfullmakt (lag 2017:310, utkast)",cat:"se_familj",tier:"komplex",q:[Pq("fullmaktig","Fullmäktig: namn, personnummer, adress",true),Pq("omraden","Områden",true,["Ekonomi","Personliga angelägenheter","Båda"]),Pq("onskemal","Särskilda önskemål/gränser",false),Pq("uppgifter","Dina uppgifter: namn, personnummer, adress",true),Pq("obs","OBS: kräver skriftlig form och TVÅ vittnen",false)]},
    se_underhall_krav:{ic:"👨‍👧",n:"Krav på underhållsbidrag",cat:"se_familj",tier:"standard",q:[Pq("skyldig","Underhållsskyldig: namn och adress",true),Pq("grund","Grund (dom/avtal av den)",true),Pq("skuld","Utestående (månader, belopp)",true),Pq("frist","Betalningsfrist (t.ex. 14 dagar)",true),Pq("uppgifter","Dina uppgifter: namn och adress",true)]},
    se_testamente:{ic:"📜",n:"Testamente (utkast — två vittnen krävs)",cat:"se_familj",tier:"komplex",q:[Pq("mottagare","Arvingar/testamentstagare och andelar",true),Pq("legat","Särskilda legat (frivilligt)",false),Pq("uppgifter","Dina uppgifter: namn, personnummer",true),Pq("obs","OBS: giltigt endast med underskrift och TVÅ samtidigt närvarande vittnen; bröstarvingars laglott gäller",false)]},
    se_bilkop:{ic:"🚗",n:"Köpekontrakt bil (privat)",cat:"se_bil",tier:"standard",q:[Pq("roll","Du är",true,["Säljare","Köpare"]),Pq("motpart","Motpart: namn, personnummer, adress",true),Pq("fordon","Märke, modell, registreringsnummer, chassinummer",true),Pq("mil","Årsmodell och mätarställning",true),Pq("pris","Pris (kr) och betalning (ägarbyte anmäls till Transportstyrelsen)",true),Pq("besiktning","Besiktigad till",false),Pq("brister","Kända brister",false)]},
    se_parkeringsanmarkning:{ic:"🚦",n:"Bestrida parkeringsanmärkning/kontrollavgift",cat:"se_bil",tier:"standard",q:[Pq("utfardare","Utfärdare",true,["Polisen/kommunen (parkeringsanmärkning)","Privat bolag (kontrollavgift)"]),Pq("referens","Ärende-/OCR-nummer",true),Pq("datum","Anmärkning den, plats",true),Pq("skal","Varför felaktig (egna ord)",true),Pq("uppgifter","Dina uppgifter: namn och adress",true)]},
    se_skadeanmalan_bil:{ic:"💥",n:"Skadeanmälan till fordonsförsäkring",cat:"se_bil",tier:"einfach",q:[Pq("bolag","Försäkringsbolag: namn",true),Pq("forsakring","Försäkringsnummer",true),Pq("handelse","Händelse: datum, plats, förlopp",true),Pq("skada","Skador på fordonet",true),Pq("motpart","Motpart (namn, reg.nr, bolag)",false),Pq("uppgifter","Dina uppgifter: namn och adress",true)]},
    se_omprovning_fk:{ic:"🏥",n:"Begäran om omprövning — Försäkringskassan",cat:"se_halsa",tier:"komplex",q:[Pq("beslut","Beslut den (ärendenummer)",true),Pq("omrade","Område",true,["Sjukpenning","Sjukersättning","Bostadsbidrag","Föräldrapenning","Annat"]),Pq("skal","Varför är beslutet fel",true),Pq("uppgifter","Dina uppgifter: namn, adress, personnummer",true)]},
    se_vardersattning:{ic:"🩺",n:"Ersättning för vårdkostnader",cat:"se_halsa",tier:"einfach",q:[Pq("mottagare","Region/försäkring: namn och adress",true),Pq("vard","Vård: vårdgivare, datum, typ",true),Pq("belopp","Betalt belopp (kr, kvitto bifogas)",true),Pq("konto","Ditt konto",true),Pq("uppgifter","Dina uppgifter: namn, adress, personnummer",true)]},
    se_hemtjanst_ansokan:{ic:"🧓",n:"Ansökan om hemtjänst/bistånd (SoL)",cat:"se_halsa",tier:"standard",q:[Pq("kommun","Kommun",true),Pq("behov","Vilket stöd behövs?",true),Pq("situation","Din situation (hälsa, boende)",true),Pq("uppgifter","Dina uppgifter: namn, adress, personnummer",true)]},
    se_konto_avslut:{ic:"🏦",n:"Avsluta bankkonto",cat:"se_pengar",tier:"einfach",q:[Pq("bank","Bank: namn och adress",true),Pq("konto","Konto som ska avslutas",true),Pq("saldo","Restsaldo överförs till (konto)",true),Pq("datum","Tidpunkt",false,["Omgående","Per datum"]),Pq("uppgifter","Dina uppgifter: namn och adress",true)]},
    se_forskottsbetalning_lan:{ic:"💳",n:"Förtidsinlösen av lån/kredit",cat:"se_pengar",tier:"standard",q:[Pq("langivare","Långivare: namn och adress",true),Pq("avtal","Avtalsnummer av den",true),Pq("typ","Inlösen",true,["Hel","Delvis (belopp)"]),Pq("datum","Önskat datum",true),Pq("uppgifter","Dina uppgifter: namn och adress",true)]},
    se_obehorig_transaktion:{ic:"🧾",n:"Reklamera obehörig transaktion",cat:"se_pengar",tier:"standard",q:[Pq("bank","Bank/kortutgivare: namn",true),Pq("transaktion","Transaktion (datum, belopp, mottagare)",true),Pq("skal","Skäl",true,["Aldrig godkänd","Fel belopp","Dubbeldragning","Bedrägeri/phishing"]),Pq("sparr","Kortet redan spärrat?",false,["Ja","Nej"]),Pq("uppgifter","Dina uppgifter: namn och adress",true)]},
JS;
$o4 = "var CCODE=\"SE\", DOCWORD=\"dokument\";\n\n  var D={";
$n4 = "var CCODE=\"SE\", DOCWORD=\"dokument\";\n\n  var D={\n".$seDocs;
$c=0; $src=str_replace($o4,$n4,$src,$c);
echo ($c===1?"  ✓ [4] SE +38 belge\n":"  ✗ [4] SE D anchor ($c)\n"); if($c!==1)$fail[]=4;

if ($fail) { echo "\nHATA: adimlar eslesmedi: ".implode(', ',$fail)." — index.php DEGISTIRILMEDI.\n"; exit; }

$tmp = tempnam(sys_get_temp_dir(),'w3').'.php';
file_put_contents($tmp,$src);
$lo=[];$rc=0; exec('php -l '.escapeshellarg($tmp).' 2>&1',$lo,$rc); @unlink($tmp);
if ($rc!==0) { echo "\nLINT HATASI — index.php degistirilmedi:\n  ".implode("\n  ",$lo)."\n"; exit; }
file_put_contents($file.'.bak-widecat3-'.date('Ymd-His'), @file_get_contents($file));
file_put_contents($file,$src);
$nPL = preg_match_all('/\bpl_[a-z0-9_]+:\{ic:/', $src, $m);
$nSE = preg_match_all('/\bse_[a-z0-9_]+:\{ic:/', $src, $m);
echo "\n✓ CH_WIDECAT_PLSE uygulandi. Yeni toplam: PL=$nPL, SE=$nSE belge (+4'er kategori).\n";
