<?php
/**
 * ChatHelp — apply-widecat-nl-be (CH_WIDECAT_NLBE) — Genis katalog Batch 2
 *  NL: 38 -> ~76 belge (+38) · 4 yeni kategori (Familie/Auto/Gezondheid/Geld)
 *  BE: 36 -> ~74 belge (+38) · 4 yeni kategori (Famille/Auto/Sante/Finances)
 *  Hukuk: NL Burgerlijk Wetboek (7:206/207, 7:625, 7:656, 6:230o, Awb, Woo,
 *  Wahv, WAZO, Wet Van Dam) · BE ancien Code civil, loi 3.7.1978, CDE,
 *  CCT 109, loi 20.12.2002, Car-Pass — bolgesel kira kurallari genel ifadeyle.
 * KULLANIM: pull-updates.php?files=apply-widecat-nl-be.php
 */
header('Content-Type: text/plain; charset=UTF-8');
error_reporting(E_ERROR | E_PARSE);
echo "apply-widecat-nl-be BASLADI OK (PHP ".PHP_VERSION.")\n\n";

$file = __DIR__.'/index.php';
$src = @file_get_contents($file);
if ($src===false) exit("index.php okunamadi\n");
if (strpos($src,'CH_WIDECAT_NLBE')!==false) exit("Zaten ekli (CH_WIDECAT_NLBE).\n");

$fail=[];

/* ═══ [1] NL: kategoriler + X_ORDER ═══ */
$o1 = "    nl_overheid:{n:\"Overheid & Instanties\",ic:\"🏛️\"}\n  };\n  var X_ORDER=[\"nl_opzeggingen\",\"nl_wonen\",\"nl_werk\",\"nl_consument\",\"nl_contracten\",\"nl_overheid\"];";
$n1 = "    nl_overheid:{n:\"Overheid & Instanties\",ic:\"🏛️\"},\n"
    . "    nl_familie:{n:\"Familie & Zorg\",ic:\"👪\"},\n"
    . "    nl_auto:{n:\"Auto & Verkeer\",ic:\"🚗\"},\n"
    . "    nl_gezondheid:{n:\"Zorg & Uitkeringen\",ic:\"🏥\"},\n"
    . "    nl_geld:{n:\"Bank & Geld\",ic:\"💶\"}\n  };\n"
    . "  var X_ORDER=[\"nl_opzeggingen\",\"nl_wonen\",\"nl_werk\",\"nl_consument\",\"nl_contracten\",\"nl_overheid\",\"nl_familie\",\"nl_auto\",\"nl_gezondheid\",\"nl_geld\"]; /*CH_WIDECAT_NLBE*/";
$c=0; $src=str_replace($o1,$n1,$src,$c);
echo ($c===1?"  ✓ [1] NL +4 kategori\n":"  ✗ [1] NL XC anchor ($c)\n"); if($c!==1)$fail[]=1;

/* ═══ [2] NL: +38 belge ═══ */
$nlDocs = <<<'JS'
    /* CH_WIDECAT_NLBE — brede catalogus */
    nl_energie_opzeggen:{ic:"⚡",n:"Energiecontract opzeggen (overstap)",cat:"nl_opzeggingen",tier:"einfach",q:[Pq("leverancier","Leverancier: naam en adres",true),Pq("klantnr","Klantnummer",true),Pq("ean","EAN-code (op de jaarafrekening)",false),Pq("datum","Gewenste einddatum",false,["Eerst mogelijke datum","Specifieke datum"]),Pq("gegevens","Uw gegevens: naam en adres",true)]},
    nl_abonnement_opzeggen:{ic:"📰",n:"Abonnement opzeggen (Wet Van Dam)",cat:"nl_opzeggingen",tier:"einfach",q:[Pq("bedrijf","Bedrijf: naam en adres",true),Pq("abonnr","Abonnements-/klantnummer",true),Pq("datum","Opzegdatum (na 1e termijn: opzegtermijn max. 1 maand)",true),Pq("gegevens","Uw gegevens: naam en adres",true)]},
    nl_lidmaatschap_opzeggen:{ic:"🤝",n:"Lidmaatschap vereniging opzeggen",cat:"nl_opzeggingen",tier:"einfach",q:[Pq("vereniging","Vereniging: naam en adres",true),Pq("lidnr","Lidnummer (indien bekend)",false),Pq("datum","Opzegdatum (volgens statuten, vaak per jaareinde)",true),Pq("gegevens","Uw gegevens: naam en adres",true)]},
    nl_sepa_intrekken:{ic:"🏦",n:"SEPA-machtiging intrekken",cat:"nl_opzeggingen",tier:"einfach",q:[Pq("bedrijf","Incassant: naam en adres",true),Pq("kenmerk","Machtigingskenmerk / klantnummer",true),Pq("reden","Reden (optioneel)",false),Pq("gegevens","Uw gegevens: naam en adres",true)]},
    nl_huurverlaging:{ic:"📉",n:"Huurprijsvermindering bij gebreken (art. 7:207 BW)",cat:"nl_wonen",tier:"standard",q:[Pq("verhuurder","Verhuurder: naam en adres",true),Pq("adres","Adres van de woning",true),Pq("gebrek","Gebrek (sinds wanneer, omvang)",true),Pq("gemeld","Al eerder gemeld?",true,["Ja, schriftelijk","Ja, mondeling","Nee"]),Pq("vermindering","Gevraagde vermindering (% of €)",false),Pq("gegevens","Uw gegevens: naam",true)]},
    nl_gebreken_melden:{ic:"🔧",n:"Gebreken melden aan verhuurder (art. 7:206 BW)",cat:"nl_wonen",tier:"einfach",q:[Pq("verhuurder","Verhuurder: naam en adres",true),Pq("adres","Adres van de woning",true),Pq("gebrek","Gebrek en gevolgen",true),Pq("termijn","Termijn voor herstel (bijv. 2 weken)",true),Pq("gegevens","Uw gegevens: naam",true)]},
    nl_borg_terug:{ic:"💰",n:"Waarborgsom terugvorderen",cat:"nl_wonen",tier:"einfach",q:[Pq("verhuurder","Verhuurder: naam en adres",true),Pq("adres","Adres van de (voormalige) woning",true),Pq("einde","Einddatum huur / oplevering",true),Pq("borg","Waarborgsom (€)",true),Pq("iban","Uw IBAN",true),Pq("gegevens","Uw gegevens: naam en nieuw adres",true)]},
    nl_huur_opzeggen:{ic:"🏠",n:"Huur opzeggen (huurder, 1 maand)",cat:"nl_wonen",tier:"einfach",q:[Pq("verhuurder","Verhuurder: naam en adres",true),Pq("adres","Adres van de woning",true),Pq("datum","Einddatum (opzegtermijn = 1 betalingstermijn, meestal 1 maand)",true),Pq("gegevens","Uw gegevens: naam",true)]},
    nl_bezwaar_huurverhoging:{ic:"📈",n:"Bezwaar tegen huurverhoging (Huurcommissie)",cat:"nl_wonen",tier:"standard",q:[Pq("verhuurder","Verhuurder: naam en adres",true),Pq("adres","Adres van de woning",true),Pq("voorstel","Voorgestelde verhoging (van € naar €, per datum)",true),Pq("reden","Waarom bent u het oneens? (in eigen woorden)",true),Pq("gegevens","Uw gegevens: naam",true)]},
    nl_getuigschrift:{ic:"📜",n:"Getuigschrift opvragen (art. 7:656 BW)",cat:"nl_werk",tier:"einfach",q:[Pq("werkgever","Werkgever: naam en adres",true),Pq("periode","In dienst van – tot",true),Pq("functie","Functie",true),Pq("soort","Gewenst getuigschrift",true,["Eenvoudig (functie en duur)","Uitgebreid (met beoordeling)"]),Pq("gegevens","Uw gegevens: naam en adres",true)]},
    nl_ontslagbrief:{ic:"📤",n:"Ontslagbrief (werknemer zegt op)",cat:"nl_werk",tier:"einfach",q:[Pq("werkgever","Werkgever: naam en adres",true),Pq("datum","Einddatum (opzegtermijn meestal 1 maand)",true),Pq("getuigschrift","Getuigschrift meteen opvragen?",false,["Ja","Nee"]),Pq("gegevens","Uw gegevens: naam en adres",true)]},
    nl_loonvordering:{ic:"💶",n:"Achterstallig loon vorderen (art. 7:625 BW)",cat:"nl_werk",tier:"standard",q:[Pq("werkgever","Werkgever: naam en adres",true),Pq("bedrag","Openstaand loon (periode, bedrag)",true),Pq("termijn","Betaaltermijn (bijv. 14 dagen; wettelijke verhoging mogelijk)",true),Pq("gegevens","Uw gegevens: naam en adres",true)]},
    nl_ouderschapsverlof:{ic:"👶",n:"Ouderschapsverlof aanvragen (WAZO)",cat:"nl_werk",tier:"standard",q:[Pq("werkgever","Werkgever: naam en adres",true),Pq("kind","Kind: geboortedatum",true),Pq("periode","Gewenste periode en uren per week",true),Pq("aanvraag","Aanvraagdatum (minimaal 2 maanden vooraf)",false),Pq("gegevens","Uw gegevens: naam",true)]},
    nl_transitievergoeding:{ic:"🧾",n:"Transitievergoeding opeisen",cat:"nl_werk",tier:"standard",q:[Pq("werkgever","Werkgever: naam en adres",true),Pq("einde","Einde dienstverband (datum, wijze)",true),Pq("dienstjaren","In dienst sinds / bruto maandsalaris",true),Pq("termijn","Betaaltermijn (bijv. 14 dagen)",true),Pq("gegevens","Uw gegevens: naam en adres",true)]},
    nl_nonconform:{ic:"📦",n:"Ondeugdelijk product (art. 7:17 BW)",cat:"nl_consument",tier:"standard",q:[Pq("verkoper","Verkoper: naam en adres",true),Pq("aankoop","Gekocht op / bonnummer",true),Pq("product","Product en prijs",true),Pq("gebrek","Gebrek omschrijven",true),Pq("wens","Uw eis",true,["Reparatie","Vervanging","Prijsvermindering","Ontbinding (geld terug)"]),Pq("gegevens","Uw gegevens: naam en adres",true)]},
    nl_herroeping:{ic:"🛒",n:"Herroeping online aankoop (14 dagen)",cat:"nl_consument",tier:"einfach",q:[Pq("verkoper","Verkoper: naam en adres/e-mail",true),Pq("bestelling","Bestelnummer / datum",true),Pq("ontvangen","Ontvangen op",true),Pq("retour","Retour via",false,["Verzending","Ophalen gewenst"]),Pq("gegevens","Uw gegevens: naam en adres",true)]},
    nl_vlucht_claim:{ic:"✈️",n:"Vluchtcompensatie (EU 261/2004)",cat:"nl_consument",tier:"standard",q:[Pq("maatschappij","Luchtvaartmaatschappij",true),Pq("vlucht","Vluchtnummer en datum",true),Pq("route","Route (van – naar)",true),Pq("probleem","Wat gebeurde er?",true,["Vertraging 3+ uur","Annulering","Instapweigering (overboeking)"]),Pq("boeking","Boekingsnummer",true),Pq("gegevens","Uw gegevens: naam en adres",true)]},
    nl_incasso_betwisten:{ic:"📮",n:"Incasso betwisten (WIK)",cat:"nl_consument",tier:"standard",q:[Pq("incasso","Incassobureau: naam en adres",true),Pq("kenmerk","Dossiernummer",true),Pq("vordering","Gevorderd bedrag en gestelde grond",true),Pq("bezwaar","Uw bezwaar",true,["Vordering onterecht","Al betaald","Kosten te hoog (WIK-staffel)","Verjaard"]),Pq("gegevens","Uw gegevens: naam en adres",true)]},
    nl_koop_prive:{ic:"🛍️",n:"Koopovereenkomst tussen particulieren",cat:"nl_contracten",tier:"einfach",q:[Pq("rol","U bent",true,["Verkoper","Koper"]),Pq("partij","Andere partij: naam en adres",true),Pq("zaak","Verkochte zaak (nauwkeurig)",true),Pq("prijs","Prijs (€) en betaalwijze",true),Pq("levering","Leverdatum/-plaats",true),Pq("garantie","Uitsluiting garantie (particuliere verkoop)?",false,["Ja","Nee"])]},
    nl_geldlening_prive:{ic:"💸",n:"Geldlening tussen particulieren",cat:"nl_contracten",tier:"standard",q:[Pq("rol","U bent",true,["Uitlener","Lener"]),Pq("partij","Andere partij: naam en adres",true),Pq("bedrag","Bedrag (€)",true),Pq("terugbetaling","Terugbetaling (termijnen/datum)",true),Pq("rente","Rente",false,["Renteloos","Met rente (% per jaar)"])]},
    nl_bruikleen:{ic:"🤲",n:"Bruikleenovereenkomst",cat:"nl_contracten",tier:"einfach",q:[Pq("rol","U bent",true,["Uitlener","Bruiklener"]),Pq("partij","Andere partij: naam en adres",true),Pq("zaak","Uitgeleende zaak (staat)",true),Pq("duur","Duur (van – tot)",true),Pq("schade","Vergoeding bij schade afspreken?",false,["Ja, dagwaarde","Nee"])]},
    nl_klusovereenkomst:{ic:"🔨",n:"Overeenkomst van opdracht (klus)",cat:"nl_contracten",tier:"standard",q:[Pq("rol","U bent",true,["Opdrachtgever","Opdrachtnemer"]),Pq("partij","Andere partij: naam en adres",true),Pq("werk","Omschrijving van de werkzaamheden",true),Pq("prijs","Prijs (€, vast of per uur)",true),Pq("termijn","Opleverdatum",true),Pq("materiaal","Wie levert het materiaal?",false,["Opdrachtnemer","Opdrachtgever"])]},
    nl_bezwaarschrift:{ic:"⚖️",n:"Bezwaarschrift (Awb, 6 weken)",cat:"nl_overheid",tier:"komplex",q:[Pq("orgaan","Bestuursorgaan: naam en adres",true),Pq("besluit","Besluit van (datum, kenmerk)",true),Pq("ontvangen","Bekendgemaakt op (termijn: 6 weken!)",true),Pq("inhoud","Wat is besloten?",true),Pq("gronden","Waarom bent u het oneens? (eigen woorden)",true),Pq("gegevens","Uw gegevens: naam en adres",true)]},
    nl_woo_verzoek:{ic:"🗂️",n:"Woo-verzoek (Wet open overheid)",cat:"nl_overheid",tier:"standard",q:[Pq("orgaan","Bestuursorgaan: naam en adres",true),Pq("documenten","Welke documenten/informatie (zo precies mogelijk)",true),Pq("periode","Periode waarop het verzoek ziet",false),Pq("gegevens","Uw gegevens: naam en adres",true)]},
    nl_betalingsregeling_bd:{ic:"🧾",n:"Betalingsregeling Belastingdienst",cat:"nl_overheid",tier:"standard",q:[Pq("aanslag","Aanslagnummer / soort belasting",true),Pq("bedrag","Openstaand bedrag (€)",true),Pq("voorstel","Voorgestelde maandtermijn (€)",true),Pq("reden","Reden van betalingsproblemen (kort)",true),Pq("gegevens","Uw gegevens: naam, adres, BSN",true)]},
    nl_volmacht:{ic:"📝",n:"Volmacht (algemeen)",cat:"nl_familie",tier:"einfach",q:[Pq("gevolmachtigde","Gevolmachtigde: naam, geboortedatum, adres",true),Pq("omvang","Waarvoor geldt de volmacht?",true,["Eén zaak","Overheidszaken","Bankzaken","Algemeen"]),Pq("details","Nadere omschrijving",true),Pq("duur","Looptijd",false,["Onbepaald","Tot datum"]),Pq("gegevens","Uw gegevens: naam, geboortedatum, adres",true)]},
    nl_levenstestament:{ic:"🛡️",n:"Levenstestament (concept)",cat:"nl_familie",tier:"komplex",q:[Pq("vertrouwens","Vertrouwenspersoon: naam, geboortedatum, adres",true),Pq("bereik","Onderdelen",true,["Financiën","Medische zaken","Wonen/zorg","Alles"]),Pq("wensen","Bijzondere wensen/grenzen",false),Pq("gegevens","Uw gegevens: naam, geboortedatum, adres",true),Pq("let_op","Let op: voor volledige werking (banken) is een notariële akte gebruikelijk",false)]},
    nl_alimentatie_aanmaning:{ic:"👨‍👧",n:"Alimentatie aanmanen",cat:"nl_familie",tier:"standard",q:[Pq("plichtige","Alimentatieplichtige: naam en adres",true),Pq("titel","Titel (beschikking/convenant van)",true),Pq("achterstand","Achterstand (maanden, bedrag)",true),Pq("termijn","Betaaltermijn (bijv. 14 dagen; daarna LBIO)",true),Pq("gegevens","Uw gegevens: naam en adres",true)]},
    nl_auto_koop:{ic:"🚗",n:"Auto koopcontract (particulier)",cat:"nl_auto",tier:"standard",q:[Pq("rol","U bent",true,["Verkoper","Koper"]),Pq("partij","Andere partij: naam en adres",true),Pq("voertuig","Merk, model, kenteken, VIN",true),Pq("km","Bouwjaar en kilometerstand (NAP)",true),Pq("prijs","Prijs (€) en betaalwijze",true),Pq("apk","APK geldig tot",false),Pq("gebreken","Bekende gebreken",false)]},
    nl_verkeersboete_beroep:{ic:"🚦",n:"Beroep verkeersboete (Wahv, 6 weken)",cat:"nl_auto",tier:"standard",q:[Pq("cjib","CJIB-/beschikkingsnummer",true),Pq("datum","Beschikking van (termijn: 6 weken!)",true),Pq("feit","Verweten gedraging",true),Pq("gronden","Waarom onterecht? (eigen woorden)",true),Pq("gegevens","Uw gegevens: naam en adres",true)]},
    nl_schade_melden:{ic:"💥",n:"Schademelding autoverzekering",cat:"nl_auto",tier:"einfach",q:[Pq("verzekeraar","Verzekeraar: naam en adres",true),Pq("polis","Polisnummer",true),Pq("schade","Schade: datum, plaats, toedracht",true),Pq("omvang","Schade aan het voertuig",true),Pq("tegenpartij","Tegenpartij (naam, kenteken, verzekeraar)",false),Pq("gegevens","Uw gegevens: naam en adres",true)]},
    nl_aansprakelijkstelling:{ic:"🧾",n:"Aansprakelijkstelling (schadevergoeding)",cat:"nl_auto",tier:"standard",q:[Pq("aansprakelijke","Aansprakelijke partij: naam en adres",true),Pq("gebeurtenis","Gebeurtenis: datum, plaats, toedracht",true),Pq("schade","Geleden schade (onderbouwd, bedragen)",true),Pq("termijn","Reactietermijn (bijv. 4 weken)",true),Pq("gegevens","Uw gegevens: naam en adres",true)]},
    nl_bezwaar_uwv:{ic:"🏥",n:"Bezwaar tegen UWV-besluit (6 weken)",cat:"nl_gezondheid",tier:"komplex",q:[Pq("besluit","Besluit van (datum, kenmerk)",true),Pq("onderwerp","Onderwerp",true,["WW","WIA/WGA","Ziektewet","Wajong","Anders"]),Pq("gronden","Waarom bent u het oneens?",true),Pq("gegevens","Uw gegevens: naam, adres, BSN",true)]},
    nl_wmo_aanvraag:{ic:"🧓",n:"Wmo-aanvraag / melding bij gemeente",cat:"nl_gezondheid",tier:"standard",q:[Pq("gemeente","Gemeente",true),Pq("hulpvraag","Welke ondersteuning heeft u nodig?",true),Pq("situatie","Uw situatie (gezondheid, huishouden)",true),Pq("gegevens","Uw gegevens: naam, adres, BSN",true)]},
    nl_zorg_declaratie:{ic:"🩺",n:"Declaratie/klacht zorgverzekeraar",cat:"nl_gezondheid",tier:"einfach",q:[Pq("verzekeraar","Zorgverzekeraar: naam",true),Pq("behandeling","Behandeling: zorgverlener, datum",true),Pq("bedrag","Bedrag (€, nota bijvoegen)",true),Pq("iban","Uw IBAN",true),Pq("gegevens","Uw gegevens: naam, adres, polisnummer",true)]},
    nl_rekening_opzeggen:{ic:"🏦",n:"Bankrekening opzeggen (overstapservice)",cat:"nl_geld",tier:"einfach",q:[Pq("bank","Bank: naam en adres",true),Pq("iban","IBAN van de op te zeggen rekening",true),Pq("saldo","Restsaldo overmaken naar (IBAN)",true),Pq("overstap","Overstapservice gewenst?",false,["Ja","Nee"]),Pq("gegevens","Uw gegevens: naam en adres",true)]},
    nl_vervroegd_aflossen:{ic:"💳",n:"Vervroegd aflossen krediet",cat:"nl_geld",tier:"standard",q:[Pq("kredietgever","Kredietverstrekker: naam en adres",true),Pq("contract","Contractnummer van",true),Pq("wijze","Aflossing",true,["Volledig","Gedeeltelijk (bedrag)"]),Pq("datum","Gewenste datum",true),Pq("gegevens","Uw gegevens: naam en adres",true)]},
    nl_betwisting_afschrijving:{ic:"🧾",n:"Onterechte afschrijving betwisten",cat:"nl_geld",tier:"standard",q:[Pq("bank","Bank: naam",true),Pq("transactie","Transactie (datum, bedrag, begunstigde)",true),Pq("reden","Reden",true,["Nooit gemachtigd","Bedrag onjuist","Dubbel afgeschreven","Fraude/phishing"]),Pq("storno","Al gestorneerd (binnen 56 dagen mogelijk)?",false,["Ja","Nee"]),Pq("gegevens","Uw gegevens: naam en adres",true)]},
JS;
$o2 = "var CCODE=\"NL\", DOCWORD=\"documenten\";\n\n  var D={";
$n2 = "var CCODE=\"NL\", DOCWORD=\"documenten\";\n\n  var D={\n".$nlDocs;
$c=0; $src=str_replace($o2,$n2,$src,$c);
echo ($c===1?"  ✓ [2] NL +38 belge\n":"  ✗ [2] NL D anchor ($c)\n"); if($c!==1)$fail[]=2;

/* ═══ [3] BE: kategoriler + X_ORDER ═══ */
$o3 = "    be_admin:{n:\"Administrations\",ic:\"🏛️\"}\n  };\n  var X_ORDER=[\"be_resiliations\",\"be_logement\",\"be_travail\",\"be_conso\",\"be_contrats\",\"be_admin\"];";
$n3 = "    be_admin:{n:\"Administrations\",ic:\"🏛️\"},\n"
    . "    be_famille:{n:\"Famille & Protection\",ic:\"👪\"},\n"
    . "    be_auto:{n:\"Auto & Mobilité\",ic:\"🚗\"},\n"
    . "    be_sante:{n:\"Santé & Social\",ic:\"🏥\"},\n"
    . "    be_finances:{n:\"Banque & Finances\",ic:\"💶\"}\n  };\n"
    . "  var X_ORDER=[\"be_resiliations\",\"be_logement\",\"be_travail\",\"be_conso\",\"be_contrats\",\"be_admin\",\"be_famille\",\"be_auto\",\"be_sante\",\"be_finances\"]; /*CH_WIDECAT_NLBE*/";
$c=0; $src=str_replace($o3,$n3,$src,$c);
echo ($c===1?"  ✓ [3] BE +4 kategori\n":"  ✗ [3] BE XC anchor ($c)\n"); if($c!==1)$fail[]=3;

/* ═══ [4] BE: +38 belge ═══ */
$beDocs = <<<'JS'
    /* CH_WIDECAT_NLBE — catalogue large */
    be_energie_resiliation:{ic:"⚡",n:"Résiliation contrat énergie (changement)",cat:"be_resiliations",tier:"einfach",q:[Pq("fournisseur","Fournisseur : nom et adresse",true),Pq("client","Numéro de client",true),Pq("ean","Code EAN (sur la facture)",false),Pq("date","Date souhaitée",false,["Première date possible","Date précise"]),Pq("donnees","Vos données : nom et adresse",true)]},
    be_abonnement_resiliation:{ic:"📰",n:"Résiliation d'abonnement (presse/service)",cat:"be_resiliations",tier:"einfach",q:[Pq("societe","Société : nom et adresse",true),Pq("numero","Numéro d'abonnement/client",true),Pq("date","Date de résiliation",true),Pq("donnees","Vos données : nom et adresse",true)]},
    be_asbl_demission:{ic:"🤝",n:"Démission d'une ASBL / d'un club",cat:"be_resiliations",tier:"einfach",q:[Pq("asbl","ASBL/club : nom et adresse",true),Pq("membre","Numéro de membre (si connu)",false),Pq("date","Date d'effet (selon les statuts)",true),Pq("donnees","Vos données : nom et adresse",true)]},
    be_domiciliation_revocation:{ic:"🏦",n:"Révocation d'une domiciliation SEPA",cat:"be_resiliations",tier:"einfach",q:[Pq("beneficiaire","Bénéficiaire : nom et adresse",true),Pq("mandat","Référence du mandat / n° client",true),Pq("banque","Informer aussi la banque ?",false,["Oui","Non"]),Pq("donnees","Vos données : nom et adresse",true)]},
    be_reduction_loyer:{ic:"📉",n:"Réduction de loyer pour vices (art. 1721 anc. C.civ.)",cat:"be_logement",tier:"standard",q:[Pq("bailleur","Bailleur : nom et adresse",true),Pq("logement","Adresse du logement",true),Pq("vice","Vice/défaut (depuis quand, ampleur)",true),Pq("signale","Déjà signalé ?",true,["Oui, par écrit","Oui, oralement","Non"]),Pq("reduction","Réduction demandée (% ou €)",false),Pq("donnees","Vos données : nom",true)]},
    be_signalement_defauts:{ic:"🔧",n:"Signalement de défauts au bailleur",cat:"be_logement",tier:"einfach",q:[Pq("bailleur","Bailleur : nom et adresse",true),Pq("logement","Adresse du logement",true),Pq("defaut","Défaut et conséquences",true),Pq("delai","Délai de réparation (p. ex. 15 jours)",true),Pq("donnees","Vos données : nom",true)]},
    be_garantie_locative_restitution:{ic:"💰",n:"Restitution de la garantie locative",cat:"be_logement",tier:"einfach",q:[Pq("bailleur","Bailleur : nom et adresse",true),Pq("logement","Adresse du logement (ancien)",true),Pq("sortie","Date de sortie / remise des clés",true),Pq("garantie","Montant de la garantie (€)",true),Pq("iban","Votre IBAN",true),Pq("donnees","Vos données : nom et nouvelle adresse",true)]},
    be_renon_locataire:{ic:"🏠",n:"Renon du locataire (préavis 3 mois)",cat:"be_logement",tier:"einfach",q:[Pq("bailleur","Bailleur : nom et adresse",true),Pq("logement","Adresse du logement",true),Pq("date","Fin du préavis (3 mois, selon la réglementation régionale)",true),Pq("donnees","Vos données : nom",true)]},
    be_contestation_charges:{ic:"🧾",n:"Contestation du décompte de charges",cat:"be_logement",tier:"standard",q:[Pq("bailleur","Bailleur/syndic : nom et adresse",true),Pq("logement","Adresse du logement",true),Pq("periode","Période du décompte",true),Pq("postes","Postes contestés et motifs (justificatifs consultables)",true),Pq("donnees","Vos données : nom",true)]},
    be_demission:{ic:"📤",n:"Lettre de démission (loi 3.7.1978)",cat:"be_travail",tier:"einfach",q:[Pq("employeur","Employeur : nom et adresse",true),Pq("date","Fin du préavis (durée selon ancienneté)",true),Pq("attestation","Demander aussi les documents sociaux (C4, attestations) ?",false,["Oui","Non"]),Pq("donnees","Vos données : nom et adresse",true)]},
    be_attestation_occupation:{ic:"📜",n:"Demande d'attestation d'occupation",cat:"be_travail",tier:"einfach",q:[Pq("employeur","Employeur : nom et adresse",true),Pq("periode","Occupé du – au",true),Pq("fonction","Fonction",true),Pq("donnees","Vos données : nom et adresse",true)]},
    be_salaire_impaye:{ic:"💶",n:"Réclamation de salaire impayé",cat:"be_travail",tier:"standard",q:[Pq("employeur","Employeur : nom et adresse",true),Pq("montant","Sommes dues (mois, montants)",true),Pq("delai","Délai de paiement (p. ex. 15 jours)",true),Pq("donnees","Vos données : nom et adresse",true)]},
    be_conge_parental:{ic:"👶",n:"Demande de congé parental",cat:"be_travail",tier:"standard",q:[Pq("employeur","Employeur : nom et adresse",true),Pq("enfant","Enfant : date de naissance",true),Pq("forme","Forme souhaitée",true,["Temps plein (4 mois)","Mi-temps","1/5e","1/10e"]),Pq("periode","Période souhaitée",true),Pq("donnees","Vos données : nom",true)]},
    be_motivation_licenciement:{ic:"⚖️",n:"Demande des motifs du licenciement (CCT 109)",cat:"be_travail",tier:"standard",q:[Pq("employeur","Employeur : nom et adresse",true),Pq("licenciement","Licenciement notifié le (délai : 2 mois)",true),Pq("contexte","Contexte (bref)",true),Pq("donnees","Vos données : nom et adresse",true)]},
    be_garantie_legale:{ic:"📦",n:"Garantie légale (2 ans) : bien défectueux",cat:"be_conso",tier:"standard",q:[Pq("vendeur","Vendeur : nom et adresse",true),Pq("achat","Acheté le / n° de ticket",true),Pq("produit","Produit et prix",true),Pq("defaut","Défaut constaté",true),Pq("remede","Votre demande",true,["Réparation","Remplacement","Réduction du prix","Résolution (remboursement)"]),Pq("donnees","Vos données : nom et adresse",true)]},
    be_retractation_14j:{ic:"🛒",n:"Rétractation achat en ligne (14 jours, CDE)",cat:"be_conso",tier:"einfach",q:[Pq("vendeur","Vendeur : nom et adresse/e-mail",true),Pq("commande","Numéro de commande / date",true),Pq("recu","Reçu le",true),Pq("retour","Retour par",false,["Envoi","Enlèvement souhaité"]),Pq("donnees","Vos données : nom et adresse",true)]},
    be_vol_indemnisation:{ic:"✈️",n:"Indemnisation vol (Règl. CE 261/2004)",cat:"be_conso",tier:"standard",q:[Pq("compagnie","Compagnie aérienne",true),Pq("vol","Numéro de vol et date",true),Pq("trajet","Trajet (de – à)",true),Pq("probleme","Que s'est-il passé ?",true,["Retard de 3 h ou plus","Annulation","Refus d'embarquement (surbooking)"]),Pq("reservation","Référence de réservation",true),Pq("donnees","Vos données : nom et adresse",true)]},
    be_recouvrement_contestation:{ic:"📮",n:"Contestation recouvrement amiable (loi 20.12.2002)",cat:"be_conso",tier:"standard",q:[Pq("bureau","Bureau de recouvrement : nom et adresse",true),Pq("dossier","Référence du dossier",true),Pq("creance","Montant réclamé et origine alléguée",true),Pq("exception","Votre contestation",true,["Créance inexistante","Déjà payée","Frais excessifs","Prescrite"]),Pq("donnees","Vos données : nom et adresse",true)]},
    be_vente_particuliers:{ic:"🛍️",n:"Vente entre particuliers (bien mobilier)",cat:"be_contrats",tier:"einfach",q:[Pq("role","Vous êtes",true,["Vendeur","Acheteur"]),Pq("partie","Autre partie : nom et adresse",true),Pq("bien","Bien vendu (description précise)",true),Pq("prix","Prix (€) et mode de paiement",true),Pq("livraison","Date/lieu de remise",true),Pq("garantie","Exclusion de garantie (vente privée) ?",false,["Oui","Non"])]},
    be_pret_particuliers:{ic:"💸",n:"Prêt entre particuliers (reconnaissance de dette)",cat:"be_contrats",tier:"standard",q:[Pq("role","Vous êtes",true,["Prêteur","Emprunteur"]),Pq("partie","Autre partie : nom et adresse",true),Pq("montant","Montant (€)",true),Pq("remboursement","Remboursement (mensualités/échéance)",true),Pq("interets","Intérêts",false,["Sans intérêts","Avec intérêts (% par an)"])]},
    be_contrat_entreprise:{ic:"🔨",n:"Contrat d'entreprise (petits travaux)",cat:"be_contrats",tier:"standard",q:[Pq("role","Vous êtes",true,["Maître d'ouvrage","Entrepreneur"]),Pq("partie","Autre partie : nom et adresse",true),Pq("travaux","Description des travaux",true),Pq("prix","Prix (€, forfait ou en régie)",true),Pq("delai","Délai d'achèvement",true),Pq("materiaux","Qui fournit les matériaux ?",false,["Entrepreneur","Maître d'ouvrage"])]},
    be_bail_garage:{ic:"🅿️",n:"Bail de garage / emplacement",cat:"be_contrats",tier:"einfach",q:[Pq("role","Vous êtes",true,["Bailleur","Locataire"]),Pq("partie","Autre partie : nom et adresse",true),Pq("emplacement","Adresse du garage/emplacement",true),Pq("loyer","Loyer (€/mois)",true),Pq("debut","Début du bail",true),Pq("duree","Durée / préavis",false,["Indéterminée (préavis 1 mois)","Déterminée"])]},
    be_acces_documents:{ic:"🗂️",n:"Accès aux documents administratifs",cat:"be_admin",tier:"einfach",q:[Pq("autorite","Autorité : nom et adresse",true),Pq("documents","Documents demandés (le plus précis possible)",true),Pq("interet","Votre intérêt (si document à caractère personnel)",false),Pq("modalite","Modalité",false,["Consultation","Copie"]),Pq("donnees","Vos données : nom et adresse",true)]},
    be_plan_paiement_spf:{ic:"🧾",n:"Plan de paiement SPF Finances",cat:"be_admin",tier:"standard",q:[Pq("reference","Référence de l'avertissement-extrait de rôle / dette",true),Pq("montant","Montant dû (€)",true),Pq("mensualite","Mensualité proposée (€)",true),Pq("motif","Motif des difficultés (bref)",true),Pq("donnees","Vos données : nom, adresse, n° national",true)]},
    be_reclamation_fiscale:{ic:"⚖️",n:"Réclamation fiscale (impôt des personnes physiques)",cat:"be_admin",tier:"komplex",q:[Pq("bureau","Centre/bureau compétent (sur l'avertissement-extrait de rôle)",true),Pq("role","Article de rôle / exercice d'imposition",true),Pq("recu","Avertissement reçu le (délai légal de réclamation !)",true),Pq("griefs","Points contestés et motifs (vos mots)",true),Pq("donnees","Vos données : nom, adresse, n° national",true)]},
    be_procuration:{ic:"📝",n:"Procuration (générale)",cat:"be_famille",tier:"einfach",q:[Pq("mandataire","Mandataire : nom, date de naissance, adresse",true),Pq("objet","Pour quoi vaut la procuration ?",true,["Une affaire précise","Démarches administratives","Opérations bancaires","Générale"]),Pq("details","Description plus précise",true),Pq("duree","Durée",false,["Illimitée","Jusqu'au (date)"]),Pq("donnees","Vos données : nom, date de naissance, adresse",true)]},
    be_mandat_protection:{ic:"🛡️",n:"Mandat de protection extrajudiciaire (projet)",cat:"be_famille",tier:"komplex",q:[Pq("mandataire","Mandataire : nom, date de naissance, adresse",true),Pq("domaines","Domaines couverts",true,["Patrimoine","Personne (santé, résidence)","Les deux"]),Pq("souhaits","Souhaits/limites particuliers",false),Pq("donnees","Vos données : nom, date de naissance, adresse",true),Pq("note","Note : enregistrement (via notaire ou justice de paix) recommandé pour l'opposabilité",false)]},
    be_pension_alimentaire_md:{ic:"👨‍👧",n:"Mise en demeure : pension alimentaire",cat:"be_famille",tier:"standard",q:[Pq("debiteur","Débiteur : nom et adresse",true),Pq("titre","Titre (jugement/accord du)",true),Pq("arrieres","Arriérés (mois, montant)",true),Pq("delai","Délai de paiement (p. ex. 15 jours ; ensuite SECAL possible)",true),Pq("donnees","Vos données : nom et adresse",true)]},
    be_testament_olographe:{ic:"📜",n:"Testament olographe (projet)",cat:"be_famille",tier:"komplex",q:[Pq("beneficiaires","Héritiers/bénéficiaires et parts/biens",true),Pq("legs","Legs particuliers (facultatif)",false),Pq("executeur","Exécuteur testamentaire (facultatif)",false),Pq("donnees","Vos données : nom, date de naissance",true),Pq("note","Note : valable UNIQUEMENT si entièrement écrit à la main, daté et signé ; respecter la réserve héréditaire",false)]},
    be_vente_voiture:{ic:"🚗",n:"Vente de voiture entre particuliers (Car-Pass)",cat:"be_auto",tier:"standard",q:[Pq("role","Vous êtes",true,["Vendeur","Acheteur"]),Pq("partie","Autre partie : nom et adresse",true),Pq("vehicule","Marque, modèle, châssis (VIN), plaque",true),Pq("km","1re immatriculation et kilométrage",true),Pq("prix","Prix (€) et paiement",true),Pq("carpass","Car-Pass remis (obligatoire) ?",true,["Oui","À remettre à la vente"]),Pq("controle","Contrôle technique / défauts connus",false)]},
    be_contestation_amende:{ic:"🚦",n:"Contestation d'une amende routière",cat:"be_auto",tier:"standard",q:[Pq("reference","Référence de la perception immédiate / PV",true),Pq("date","Notifié le",true),Pq("infraction","Infraction reprochée",true),Pq("motifs","Motifs de contestation (vos mots)",true),Pq("donnees","Vos données : nom et adresse",true)]},
    be_sinistre_declaration:{ic:"💥",n:"Déclaration de sinistre à l'assurance",cat:"be_auto",tier:"einfach",q:[Pq("assureur","Assureur : nom et adresse",true),Pq("police","Numéro de police",true),Pq("sinistre","Sinistre : date, lieu, circonstances",true),Pq("degats","Dégâts constatés",true),Pq("tiers","Tiers impliqué (nom, plaque, assureur)",false),Pq("donnees","Vos données : nom et adresse",true)]},
    be_mise_demeure_dommages:{ic:"🧾",n:"Mise en demeure : réparation d'un dommage",cat:"be_auto",tier:"standard",q:[Pq("responsable","Responsable : nom et adresse",true),Pq("fait","Fait dommageable : date, lieu, circonstances",true),Pq("dommage","Dommage subi (justifié, montants)",true),Pq("delai","Délai de réponse (p. ex. 30 jours)",true),Pq("donnees","Vos données : nom et adresse",true)]},
    be_contestation_mutuelle:{ic:"🏥",n:"Contestation d'une décision de la mutuelle",cat:"be_sante",tier:"komplex",q:[Pq("mutuelle","Mutuelle : nom et adresse",true),Pq("decision","Décision du (référence)",true),Pq("objet","Objet (indemnités, remboursement, reconnaissance)",true),Pq("motifs","Pourquoi la décision est-elle erronée ?",true),Pq("donnees","Vos données : nom, adresse, NISS",true)]},
    be_allocation_handicap:{ic:"🧓",n:"Allocation aux personnes handicapées : courrier",cat:"be_sante",tier:"standard",q:[Pq("objet","Votre demande",true,["Première demande (My Handicap)","Révision","Question sur un dossier"]),Pq("personne","Personne concernée : nom, date de naissance, NISS",true),Pq("situation","Situation de santé/besoin d'aide (bref)",true),Pq("donnees","Demandeur : nom et adresse",true)]},
    be_remboursement_soins:{ic:"🩺",n:"Demande de remboursement de soins",cat:"be_sante",tier:"einfach",q:[Pq("organisme","Mutuelle/assurance : nom et adresse",true),Pq("soins","Soins : prestataire, date, nature",true),Pq("montant","Montant payé (€, attestation jointe)",true),Pq("iban","Votre IBAN",true),Pq("donnees","Vos données : nom, adresse, NISS",true)]},
    be_cloture_compte:{ic:"🏦",n:"Clôture de compte bancaire",cat:"be_finances",tier:"einfach",q:[Pq("banque","Banque : nom et adresse",true),Pq("iban","IBAN du compte à clôturer",true),Pq("solde","Solde à virer sur (IBAN)",true),Pq("date","Prise d'effet",false,["Immédiate","À la date"]),Pq("donnees","Vos données : nom et adresse",true)]},
    be_remboursement_anticipe:{ic:"💳",n:"Remboursement anticipé d'un crédit (CDE)",cat:"be_finances",tier:"standard",q:[Pq("preteur","Prêteur : nom et adresse",true),Pq("contrat","Contrat n° du",true),Pq("type","Remboursement",true,["Total","Partiel (montant)"]),Pq("date","Date souhaitée",true),Pq("donnees","Vos données : nom et adresse",true)]},
    be_debit_conteste:{ic:"🧾",n:"Contestation d'un débit non autorisé",cat:"be_finances",tier:"standard",q:[Pq("banque","Banque/émetteur : nom et adresse",true),Pq("operation","Opération contestée (date, montant, bénéficiaire)",true),Pq("motif","Motif",true,["Jamais autorisée","Montant erroné","Double débit","Fraude/phishing"]),Pq("blocage","Carte déjà bloquée (Card Stop) ?",false,["Oui","Non"]),Pq("donnees","Vos données : nom et adresse",true)]},
JS;
$o4 = "var CCODE=\"BE\", DOCWORD=\"documents\";\n\n  var D={";
$n4 = "var CCODE=\"BE\", DOCWORD=\"documents\";\n\n  var D={\n".$beDocs;
$c=0; $src=str_replace($o4,$n4,$src,$c);
echo ($c===1?"  ✓ [4] BE +38 belge\n":"  ✗ [4] BE D anchor ($c)\n"); if($c!==1)$fail[]=4;

if ($fail) { echo "\nHATA: adimlar eslesmedi: ".implode(', ',$fail)." — index.php DEGISTIRILMEDI.\n"; exit; }

$tmp = tempnam(sys_get_temp_dir(),'w2').'.php';
file_put_contents($tmp,$src);
$lo=[];$rc=0; exec('php -l '.escapeshellarg($tmp).' 2>&1',$lo,$rc); @unlink($tmp);
if ($rc!==0) { echo "\nLINT HATASI — index.php degistirilmedi:\n  ".implode("\n  ",$lo)."\n"; exit; }
file_put_contents($file.'.bak-widecat2-'.date('Ymd-His'), @file_get_contents($file));
file_put_contents($file,$src);
$nNL = preg_match_all('/\bnl_[a-z0-9_]+:\{ic:/', $src, $m);
$nBE = preg_match_all('/\bbe_[a-z0-9_]+:\{ic:/', $src, $m);
echo "\n✓ CH_WIDECAT_NLBE uygulandi. Yeni toplam: NL=$nNL, BE=$nBE belge (+4'er kategori).\n";
