<?php
/**
 * FAQ içeriği
 * -----------
 * Sözlükte değil ayrı dosyada: uzun metinler i18n sözlüğünü okunmaz hale
 * getiriyor, ayrıca FAQ metni ürün/hukuk değişince tek yerden güncellenmeli.
 * Almanca ve İngilizce yazılı; diğer diller İngilizceye düşer.
 *
 * {} içindeki yer tutucular vr_faq_groups() içinde gerçek yapılandırmadan
 * dolduruluyor — kargo bedelini iki yerde güncellemek zorunda kalmayalım.
 */

declare(strict_types=1);

function vr_faq_groups(): array
{
    $lang  = vr_lang();
    $brand = (string)vr_config('brand');
    $days  = (int)vr_config('return_days', 30);
    $wd    = (int)vr_config('withdrawal_days', 14);
    $ship  = (array)vr_config('shipping');
    $vat   = (int)vr_config('vat_rate_bps', 1900) / 100;
    $steps = (int)vr_config('vault_steps', 6);
    $hours = (int)vr_config('vault_step_hours', 24);
    $email = (string)(vr_config('company')['email'] ?? '');
    $feeB  = (int)vr_config('fee_bps_business', 1200) / 100;
    $feeP  = (int)vr_config('fee_bps_private', 900) / 100;
    $welc  = (int)vr_config('welcome_discount_bps', 500) / 100;
    $wdays = (int)vr_config('welcome_valid_days', 90);
    $langs = count((array)vr_config('languages', ['en']));

    $deDe = vr_money((int)($ship['de']['cents'] ?? 0));
    $frDe = vr_money((int)($ship['de']['free_over'] ?? 0));
    $eu   = vr_money((int)($ship['eu']['cents'] ?? 0));

    $de = [
        'faq_cat_order' => [
            ['Brauche ich ein Konto, um zu kaufen?',
             "Nein. Sie bestellen als Gast; wir fragen nur, was für Lieferung und Rechnung nötig ist. Ein Konto brauchen nur Verkäufer."],
            ['Welche Zahlungsarten gibt es?',
             "Kartenzahlung (Visa, Mastercard, Amex), Apple Pay, Google Pay, Klarna und SEPA-Lastschrift — abgewickelt über Stripe. Ihre Kartendaten erreichen unsere Server nie, die Eingabe passiert auf der Seite von Stripe."],
            ['Sind die Preise inklusive Mehrwertsteuer?',
             "Ja. Alle angezeigten Preise sind Endpreise inkl. {$vat}% MwSt. Versandkosten werden vor dem Bezahlen separat ausgewiesen."],
            ['Wann wird abgebucht?',
             "Direkt bei Bestellabschluss. Klarna und SEPA können ein paar Tage brauchen — Ihre Bestellung ist trotzdem verbindlich reserviert, wir versenden nach Zahlungseingang."],
            ['Bekomme ich eine Rechnung?',
             "Ja, mit der Ware bzw. per E-Mail. Bei Artikeln von Händlern stellt der jeweilige Händler die Rechnung, bei eigener Ware {$brand}. Privatverkäufer stellen keine Rechnung mit MwSt."],
            ['Was ist die Merkliste — reserviert sie etwas?',
             "Nein. Die Merkliste ist eine Erinnerungshilfe und liegt als Cookie auf Ihrem Gerät, nicht auf unserem Server. Die meisten Stücke gibt es genau einmal; gemerkt heißt nicht reserviert. Wer zuerst bestellt, bekommt es."],
            ['Meine Zahlung wurde abgelehnt — was nun?',
             "Meist liegt es an der 3-D-Secure-Bestätigung Ihrer Bank. Versuchen Sie es erneut oder wählen Sie eine andere Zahlungsart. Es wurde nichts abgebucht, und Ihr Warenkorb bleibt erhalten."],
        ],
        'faq_cat_ship' => [
            ['Was kostet der Versand?',
             "Deutschland {$deDe}, versandfrei ab {$frDe}. EU ab {$eu}. Schweiz, UK, Norwegen und internationale Ziele werden im Warenkorb berechnet, sobald Sie das Land wählen."],
            ['Wie lange dauert die Lieferung?',
             "Deutschland {$ship['de']['days']} Werktage, EU {$ship['eu']['days']}, international {$ship['world']['days']}. Versand erfolgt versichert und mit Sendungsverfolgung."],
            ['Ich habe bei mehreren Verkäufern gekauft — kommt alles zusammen?',
             "Nein. Jeder Verkäufer versendet selbst, Sie erhalten also mehrere Pakete und mehrere Sendungslinks. Bezahlt wird trotzdem nur einmal, und Versandkosten fallen nur einmal an."],
            ['Liefern Sie an Packstationen?',
             "Innerhalb Deutschlands ja, wenn Sie eine DHL-Packstation als Lieferadresse angeben. Bei internationalen Sendungen ist eine Straßenadresse nötig."],
            ['Zoll und Einfuhrabgaben?',
             "Innerhalb der EU fallen keine an. Bei Lieferungen in die Schweiz, UK oder außerhalb Europas können Einfuhrabgaben anfallen, die der Empfänger trägt."],
        ],
        'faq_cat_return' => [
            ['Wie lange habe ich Rückgaberecht?',
             "Gesetzlich {$wd} Tage Widerruf. Bei eigener {$brand}-Ware und bei Händlern gewähren wir freiwillig {$days} Tage. Ausnahme: Käufe von Privatverkäufern — dort gibt es kein gesetzliches Widerrufsrecht."],
            ['Wie sende ich zurück?',
             "Schreiben Sie an {$email} mit Ihrer Bestellnummer. Sie erhalten ein Rücksendelabel und die Adresse des jeweiligen Verkäufers. Ware bitte ungetragen und mit Originaletikett zurückschicken."],
            ['Wer zahlt die Rücksendung?',
             "Bei Widerruf innerhalb der gesetzlichen Frist tragen wir die Kosten für Rücksendungen aus Deutschland. Für internationale Rücksendungen und für die freiwillige Verlängerung über {$wd} Tage hinaus tragen Sie die Kosten."],
            ['Wann bekomme ich mein Geld zurück?',
             "Nach Eingang und Prüfung der Ware, spätestens 14 Tage danach — auf dasselbe Zahlungsmittel. Bei Klarna erfolgt die Erstattung über Ihr Klarna-Konto."],
            ['Warum gilt bei Privatverkäufern kein Widerruf?',
             "Das Widerrufsrecht gilt nur zwischen Verbraucher und Unternehmer. Verkauft eine Privatperson, greift es nicht — deshalb kennzeichnen wir jedes Angebot deutlich und zeigen die Folge vor dem Bezahlen an."],
            ['Der Artikel ist beschädigt angekommen.',
             "Melden Sie das innerhalb von 14 Tagen mit Fotos an {$email}. Transportschäden regeln wir unabhängig vom Widerrufsrecht — auch bei Privatverkäufern."],
        ],
        'faq_cat_vault' => [
            ['Was ist der Vault?',
             "Unser Premium Outlet. Jedes Stück startet zu einem Eröffnungspreis und fällt in {$steps} festen Stufen — alle {$hours} Stunden eine Stufe — bis zum Mindestpreis. Wer zuerst zugreift, bekommt es."],
            ['Kann der Preis auch steigen?',
             "Nein. Der Plan wird beim Öffnen eines Loses festgeschrieben und danach nicht mehr geändert. Er kann nur fallen und endet am veröffentlichten Mindestpreis."],
            ['Wird der Preis für mich persönlich berechnet?',
             "Nein. Der Preis kommt aus dem Plan und wird auf unserem Server berechnet — identisch für alle Besucher, unabhängig von Gerät, Standort oder Verlauf."],
            ['Was heißt „niedrigster Preis der letzten 30 Tage“?',
             "Eine Pflichtangabe bei Preissenkungen (§11 PAngV). Weil Vault-Preise nur fallen, ist das genau der Preis, der vor der aktuellen Stufe galt. In der ersten Stufe gibt es noch keine Senkung — dann zeigen wir auch keine an."],
            ['Ich warte auf die nächste Stufe — riskant?',
             "Ja, bewusst. Jedes Los existiert nur einmal. Wer wartet, zahlt weniger — falls es nicht vorher jemand nimmt."],
            ['Was bringt die Mitgliedschaft?',
             "Mitglieder sehen neue Lose " . (int)vr_config('vault_member_head_start_hours', 12) . " Stunden vor allen anderen und bekommen den Senkungsplan per E-Mail. Kostenlos, jederzeit abmeldbar."],
            ['Gilt im Vault dasselbe Rückgaberecht?',
             "Ja. Ein reduzierter Preis ändert nichts an Ihren Rechten. Nur bei Privatverkäufern gilt die oben beschriebene Ausnahme."],
            ['Kann ich mich benachrichtigen lassen, wenn der Preis fällt?',
             "Ja. Auf jeder Los-Seite können Sie Ihren Wunschpreis eintragen. Sobald das Los ihn erreicht, bekommen Sie GENAU EINE E-Mail — keine Erinnerungen, keine Werbung. Danach ist der Alarm verbraucht und der Datensatz wird gelöscht. Ein Alarm reserviert das Stück nicht: wer zuerst kauft, bekommt es."],
            ['Warum kann ich keinen Alarm unter dem Mindestpreis setzen?',
             "Weil er nie auslösen würde. Der Preis endet am veröffentlichten Mindestpreis, deshalb nehmen wir nur Wunschpreise zwischen aktuellem Preis und Mindestpreis an."],
        ],
        'faq_cat_auth' => [
            ['Wie stellen Sie Echtheit sicher?',
             "Wir kaufen aus EU-Bestand mit dokumentierter Einkaufshistorie und verlangen von Verkäufern Belege. Auf jeder Produktseite steht, woher das Teil kommt. Bei Unklarheiten wird ein Angebot nicht freigeschaltet."],
            ['Was passiert, wenn ein Teil doch nicht original ist?',
             "Volle Rückerstattung inklusive Versand, und der Verkäufer wird von der Plattform entfernt. Melden Sie den Fall mit Fotos an {$email}."],
            ['Verkaufen Sie Second Hand?',
             "Sowohl neu (mit Originaletikett) als auch vorbesitzt. Der Zustand steht auf jeder Produktseite; bei vorbesitzten Teilen gehört die Beschreibung der Gebrauchsspuren zur Pflicht des Verkäufers."],
        ],
        'faq_cat_account' => [
            ['Lohnt sich ein Konto, wenn ich auch als Gast bestellen kann?',
             "Es ist reine Bequemlichkeit: Bestellhistorie an einem Ort, gespeicherte Lieferadresse, Rücksendung mit zwei Klicks statt per E-Mail. Der Kaufvorgang selbst ist identisch, und ein Konto verschafft weder bessere Preise noch früheren Zugang."],
            ['Wie lege ich ein Konto an?',
             "Unter „Konto → Registrieren“ mit E-Mail-Adresse und Passwort. Danach kommt eine Bestätigungsmail; der Link darin ist einmal verwendbar und läuft nach 48 Stunden ab."],
            ['Warum sehe ich meine Bestellungen erst nach der Bestätigung?',
             "Weil Bestellungen an der E-Mail-Adresse hängen. Könnte man sich mit einer fremden Adresse anmelden, ohne sie zu bestätigen, ließen sich fremde Bestellungen, Adressen und Käufe einsehen. Erst die bestätigte Adresse schaltet die Historie frei — vorher bleibt die Liste leer."],
            ['Ich habe keine Bestätigungsmail bekommen.',
             "Sehen Sie im Spam-Ordner nach; danach können Sie die Mail im Konto erneut anfordern. Kommt weiterhin nichts an, schreiben Sie an {$email} — meist ist eine Ziffer in der Adresse vertauscht."],
            ['Passwort vergessen?',
             "„Passwort vergessen“ auf der Anmeldeseite schickt einen Link, der eine Stunde gilt und danach verfällt. Aus Sicherheitsgründen bekommen Sie dieselbe Antwort, egal ob die Adresse bei uns existiert oder nicht — sonst könnte man testen, wer hier ein Konto hat."],
            ['Finde ich Bestellungen wieder, die ich als Gast aufgegeben habe?',
             "Ja, sobald das Konto dieselbe E-Mail-Adresse bestätigt hat, mit der bestellt wurde: die Zuordnung läuft über die Adresse, nicht über den Zeitpunkt der Registrierung. Ohne Konto rufen Sie jede Bestellung jederzeit über „Bestellstatus“ mit Bestellnummer und E-Mail-Adresse ab."],
            ['Ist meine Merkliste im Konto gespeichert?',
             "Nein, sie liegt als Cookie auf dem Gerät. Deshalb ist sie auf dem Telefon eine andere als auf dem Rechner und verschwindet, wenn Sie Cookies löschen. Sie verlässt Ihr Gerät nicht — das ist der Preis dafür und gleichzeitig der Vorteil."],
            ['Wie lösche ich mein Konto?',
             "Unter „Konto → Sicherheit“, sofort und ohne Rückfrage. Der Kontodatensatz wird gelöscht. Bestehende Bestellungen und Rechnungen bleiben erhalten: dafür gelten gesetzliche Aufbewahrungsfristen (§ 147 AO, § 257 HGB), was Art. 17 Abs. 3 lit. b DSGVO ausdrücklich vorsieht. Nach Ablauf dieser Fristen werden auch sie gelöscht."],
            ['Sind Konto und Newsletter dasselbe?',
             "Nein, das sind zwei getrennte Dinge. Ein Konto verschickt nur, was zu Ihren Bestellungen gehört. Der Newsletter und die Vault-Mitgliedschaft werden getrennt bestellt und getrennt abbestellt."],
        ],
        'faq_cat_voucher' => [
            ['Wie löse ich einen Gutscheincode ein?',
             "In der Tasche gibt es das Feld „Gutscheincode“. Nach dem Einlösen steht der Abzug sofort in der Summe, danach in der Kasse, in der Bestätigungsmail und auf der Bestellseite — Sie sehen bis zum Schluss, was er wert war."],
            ['Was ist der Willkommensgutschein?',
             "Nach dem Bestätigen Ihrer E-Mail-Adresse erzeugen wir automatisch einen persönlichen Code über {$welc} % und schicken ihn Ihnen zu. Er gilt {$wdays} Tage, ist an Ihre Adresse gebunden und nur für die erste bezahlte Bestellung einlösbar."],
            ['Warum wird mein Willkommenscode nicht angenommen?',
             "Drei häufige Gründe: die Bestellung läuft über eine andere E-Mail-Adresse als die, für die der Code ausgestellt wurde; es gibt bereits eine bezahlte Bestellung unter dieser Adresse; oder die {$wdays} Tage sind vorbei. Der Hinweis unter dem Feld nennt jeweils den konkreten Grund."],
            ['Kann ich mehrere Codes kombinieren?',
             "Nein, pro Bestellung wird ein Code angerechnet. Wenn Sie einen anderen einlösen, ersetzt er den vorherigen — verloren geht dabei nichts, der ersetzte Code bleibt gültig."],
            ['Gilt der Rabatt auch auf Versandkosten?',
             "Nein. Der Abzug wird auf den Warenwert gerechnet; Versandkosten bleiben unverändert. So steht es auch in Ziffer 14.2 der AGB."],
            ['Gilt der Gutschein im Premium Outlet?',
             "Ja, sofern beim Code nichts anderes steht. Vault-Preise sind bereits reduziert, der Gutschein rechnet auf den dann geltenden Stufenpreis."],
            ['Was passiert bei einem Widerruf mit dem eingelösten Gutschein?',
             "Erstattet wird, was tatsächlich gezahlt wurde. Ein Aktionsgutschein lebt danach nicht wieder auf, und ein Anspruch auf einen Ersatzcode besteht nicht (AGB 14.5). Bei Teilrücksendungen verteilen wir den Abzug anteilig auf die Artikel."],
            ['Kann ich einen Gutschein verschenken oder verkaufen?',
             "Aktionsgutscheine sind persönlich und nicht übertragbar; eine Barauszahlung gibt es nicht. Wer denselben Erstbestellungsrabatt über mehrere Konten mehrfach nutzt, muss damit rechnen, dass wir die Codes sperren (AGB 14.6)."],
            ['Zahlt der Verkäufer meinen Rabatt?',
             "Nein. Der Abzug geht zulasten der Plattform und wird von unserer Provision getragen, nie vom Auszahlungsbetrag des Verkäufers. Deshalb ist ein Gutschein technisch auf die Höhe unserer Provision begrenzt."],
        ],
        'faq_cat_service' => [
            ['Wie erreiche ich Sie?',
             "Per E-Mail an {$email} oder über das Kontaktformular. Wir antworten in der Regel innerhalb eines Werktags; es gibt bewusst keine Telefon-Hotline, weil schriftlich beides dokumentiert ist — Ihre Frage und unsere Zusage."],
            ['In welchen Sprachen gibt es die Seite?',
             "In {$langs} Sprachen. Die Sprache erkennen wir an Ihrer Browsereinstellung und am Land Ihres Zugangs und lassen sie sich jederzeit unten auf der Seite umstellen; die Wahl bleibt gespeichert. Die Rechtstexte bleiben deutsch — sie sind die verbindliche Fassung, und eine halb übersetzte AGB nützt niemandem."],
            ['Wird meine IP-Adresse gespeichert?',
             "Nein. Für die Sprachwahl wird lediglich das Länderkürzel ausgewertet, das unser Netzbetreiber der Anfrage beilegt; die IP-Adresse selbst wird dabei weder gespeichert noch an einen Geo-Dienst weitergegeben."],
            ['Kann ich die Seite ohne JavaScript benutzen?',
             "Ja. Suche, Filter, Tasche, Kasse und Konto funktionieren vollständig ohne JavaScript. Skripte machen nur einzelne Stellen bequemer, etwa die Suchvorschläge."],
            ['Was tun Sie für Barrierefreiheit?',
             "Wir orientieren uns an WCAG 2.1 Stufe AA und am Barrierefreiheitsstärkungsgesetz, das seit Juni 2025 auch für Onlinehandel gilt. Der aktuelle Stand samt bekannter Lücken steht in der Erklärung zur Barrierefreiheit — inklusive der Punkte, die noch nicht erfüllt sind."],
            ['Welche Größe passt mir?',
             "Die Größenberatung enthält Maßtabellen je Kategorie und die Umrechnung zwischen italienischen, französischen, britischen und deutschen Größen. Auf jeder Produktseite steht zusätzlich, ob das Haus eher großzügig oder knapp ausfällt."],
            ['Bekomme ich ein Angebot wieder, das ausverkauft ist?',
             "Meist nicht — die Stücke sind Einzelteile oder einzelne Größensätze. Schreiben Sie uns trotzdem: Manchmal liegt dieselbe Größe bei einem anderen Verkäufer, und wir sagen ehrlich, wenn kein Nachschub zu erwarten ist."],
            ['Verschicken Sie Werbung, wenn ich nur bestellt habe?',
             "Nein. Wer bestellt, bekommt Bestellmails — sonst nichts. Newsletter und Vault-Mitgliedschaft muss man ausdrücklich anfordern, und jede dieser Mails enthält einen Abmeldelink, der ohne Anmeldung funktioniert."],
        ],
        'faq_cat_sell' => [
            ['Wer darf bei ' . $brand . ' verkaufen?',
             "Händler (angemeldetes Gewerbe) und Privatpersonen. Beide melden sich unter „Verkaufen“ an, absolvieren die Stripe-Verifizierung und stellen danach Angebote ein."],
            ['Was kostet es?',
             "Keine Einstell- und keine Monatsgebühr. Provision: {$feeB}% für Händler, {$feeP}% für Privatverkäufer, jeweils plus " . vr_money((int)vr_config('fee_fixed_cents', 35)) . " pro verkauftem Teil. Vault-Platzierung " . ((int)vr_config('fee_bps_outlet', 1500) / 100) . "%."],
            ['Wann und wie werde ich bezahlt?',
             "Über Stripe Connect. Der Käuferbetrag minus Provision landet in Ihrem Stripe-Guthaben und wird nach dem Stripe-Auszahlungsrhythmus auf Ihr Bankkonto überwiesen. Ihr Geld liegt nie bei uns."],
            ['Warum muss ich mich bei Stripe verifizieren?',
             "Gesetzliche Pflicht für Zahlungsdienstleister (Geldwäscheprävention, KYC). Ohne abgeschlossene Verifizierung kann Stripe keine Auszahlung an Sie vornehmen — solange bleiben Ihre Angebote offline."],
            ['Muss ich ein Gewerbe anmelden?',
             "Wer regelmäßig und mit Gewinnabsicht verkauft, handelt gewerblich und muss ein Gewerbe anmelden. Gelegentlicher Verkauf aus dem eigenen Kleiderschrank ist privat. Die Einordnung liegt bei Ihnen; wir prüfen Auffälligkeiten und melden uns."],
            ['Wie lange dauert die Prüfung eines Angebots?',
             "In der Regel ein Werktag. Wir prüfen Bilder, Modellcode und Plausibilität des Preises; bei Rückfragen melden wir uns per E-Mail."],
        ],
    ];

    $en = [
        'faq_cat_order' => [
            ['Do I need an account to buy?',
             "No. You order as a guest and we ask only what delivery and invoicing require. Accounts are for sellers."],
            ['Which payment methods do you accept?',
             "Cards (Visa, Mastercard, Amex), Apple Pay, Google Pay, Klarna and SEPA direct debit, all handled by Stripe. Card details never reach our servers — you enter them on Stripe's page."],
            ['Do prices include VAT?',
             "Yes. Every price shown is a final price including {$vat}% VAT. Shipping is shown separately before you pay."],
            ['When am I charged?',
             "At checkout. Klarna and SEPA can take a few days to settle; your order is reserved and ships once payment clears."],
            ['Will I get an invoice?',
             "Yes, with the parcel or by email. Trader items are invoiced by that trader, our own stock by {$brand}. Private sellers do not issue VAT invoices."],
            ['What is the saved list — does it reserve anything?',
             "No. It is a reminder, stored in a cookie on your device rather than on our server. Most pieces exist exactly once; saved does not mean reserved. Whoever orders first gets it."],
            ['My payment was declined.',
             "Usually the 3-D Secure step with your bank. Try again or pick another method — nothing was charged and your bag is still there."],
        ],
        'faq_cat_ship' => [
            ['What does shipping cost?',
             "Germany {$deDe}, free over {$frDe}. EU from {$eu}. Switzerland, UK, Norway and the rest of the world are calculated in the bag once you pick a country."],
            ['How long does delivery take?',
             "Germany {$ship['de']['days']} working days, EU {$ship['eu']['days']}, international {$ship['world']['days']}. Everything ships insured and tracked."],
            ['I bought from several sellers — one parcel?',
             "No. Each seller ships their own items, so you get several parcels and several tracking links. You still pay once, and shipping is charged once."],
            ['Do you deliver to parcel lockers?',
             "Within Germany, yes — enter a DHL Packstation as the delivery address. International orders need a street address."],
            ['Customs and import duties?',
             "None inside the EU. Deliveries to Switzerland, the UK or outside Europe may incur import charges payable by the recipient."],
        ],
        'faq_cat_return' => [
            ['How long can I return?',
             "{$wd} days statutory withdrawal. For our own stock and trader items we voluntarily extend it to {$days} days. Exception: purchases from private sellers carry no statutory right of withdrawal."],
            ['How do I send something back?',
             "Email {$email} with your order number. You get a return label and the seller's address. Items must be unworn with original tags."],
            ['Who pays for the return?',
             "For statutory withdrawals we cover returns from Germany. International returns and returns during the voluntary extension beyond {$wd} days are at your cost."],
            ['When do I get my money back?',
             "After the item arrives and is checked, at the latest 14 days later, to the same payment method. Klarna refunds run through your Klarna account."],
            ['Why is there no withdrawal right with private sellers?',
             "The right of withdrawal exists between a consumer and a business. When a private individual sells, it does not apply — so we label every listing and show the consequence before you pay."],
            ['My item arrived damaged.',
             "Report it within 14 days with photos to {$email}. Transport damage is handled regardless of withdrawal rights, private sellers included."],
        ],
        'faq_cat_vault' => [
            ['What is the Vault?',
             "Our Premium Outlet. Every piece opens at a starting price and steps down {$steps} times — one step every {$hours} hours — until it reaches the floor price. First buyer takes it."],
            ['Can the price go up?',
             "No. The schedule is fixed when a lot opens and never changes afterwards. It only falls, and it stops at the published floor."],
            ['Is the price personalised for me?',
             "No. It comes from the schedule and is computed on our server — identical for every visitor, regardless of device, location or history."],
            ['What does "lowest price in the last 30 days" mean?',
             "A mandatory disclosure for price reductions under German price-indication law. Because Vault prices only fall, it is exactly the price that applied before the current step. On the first step there is no reduction yet, so we claim none."],
            ['Waiting for the next step — risky?',
             "Yes, by design. Each lot exists once. Wait and you pay less, unless someone takes it first."],
            ['What does membership give me?',
             "Members see new lots " . (int)vr_config('vault_member_head_start_hours', 12) . " hours before everyone else and get the schedule by email. Free, unsubscribe any time."],
            ['Same return rights in the Vault?',
             "Yes. A reduced price does not change your rights. Only the private-seller exception above applies."],
            ['Can I be told when the price drops?',
             "Yes. On every lot page you can name your price. When the lot reaches it you get EXACTLY ONE email — no reminders, no marketing. The alert is then spent and the record deleted. An alert does not reserve the piece: whoever buys first gets it."],
            ['Why can I not set an alert below the floor price?',
             "Because it would never fire. The price stops at the published floor, so we only accept target prices between the current price and that floor."],
        ],
        'faq_cat_auth' => [
            ['How do you verify authenticity?',
             "We buy from EU stock with documented purchase history and require sellers to hold proof. Every product page states where the piece comes from. If anything is unclear, the listing does not go live."],
            ['What if an item turns out not to be original?',
             "Full refund including shipping, and the seller is removed from the platform. Report it with photos to {$email}."],
            ['Do you sell pre-owned?',
             "Both new with tags and pre-owned. Condition is stated on every product page; describing wear is part of the seller's duty."],
        ],
        'faq_cat_account' => [
            ['Is an account worth it if I can check out as a guest?',
             "It is convenience only: order history in one place, a saved delivery address, returns in two clicks instead of an email. Checkout itself is identical, and an account buys you neither better prices nor earlier access."],
            ['How do I create an account?',
             "Under \"Account → Register\", with an email address and a password. A confirmation email follows; the link inside works once and expires after 48 hours."],
            ['Why can I only see my orders after confirming?',
             "Because orders are tied to the email address. If you could sign in with someone else's address without confirming it, you would see their orders, their address and what they bought. Only a confirmed address unlocks the history — until then the list stays empty."],
            ['I did not receive the confirmation email.',
             "Check the spam folder, then request it again from your account. If nothing arrives, write to {$email} — usually two digits in the address are swapped."],
            ['Forgotten password?',
             "\"Forgot password\" on the sign-in page sends a link that is valid for one hour. For security you get the same answer whether or not the address exists here — otherwise the form could be used to find out who holds an account."],
            ['Will I find orders I placed as a guest?',
             "Yes, as soon as the account confirms the same email address the order was placed with: the match runs on the address, not on when you registered. Without an account you can always open any order under \"Order status\" with the order number and email address."],
            ['Is my saved list stored in my account?',
             "No, it lives in a cookie on the device. That is why the list on your phone differs from the one on your computer and disappears when you clear cookies. It never leaves your device — that is the cost and equally the point."],
            ['How do I delete my account?',
             "Under \"Account → Security\", immediately and without a follow-up question. The account record is deleted. Existing orders and invoices remain: statutory retention periods apply to them (German tax and commercial law), a case Art. 17(3)(b) GDPR expressly provides for. They are deleted once those periods end."],
            ['Are account and newsletter the same thing?',
             "No, they are two separate things. An account only sends what belongs to your orders. The newsletter and Vault membership are subscribed and cancelled separately."],
        ],
        'faq_cat_voucher' => [
            ['How do I redeem a voucher code?',
             "The bag has a \"Voucher code\" field. Once redeemed, the deduction appears in the total straight away, then at checkout, in the confirmation email and on the order page — you can see what it was worth right to the end."],
            ['What is the welcome voucher?',
             "After you confirm your email address we automatically issue a personal code worth {$welc}% and send it to you. It runs for {$wdays} days, is tied to your address and applies to the first paid order only."],
            ['Why is my welcome code refused?',
             "Three common reasons: the order uses a different email address than the one the code was issued for; there is already a paid order under that address; or the {$wdays} days have passed. The note under the field names the actual reason."],
            ['Can I combine several codes?',
             "No, one code counts per order. Redeeming another replaces the previous one — nothing is lost, the replaced code stays valid."],
            ['Does the discount apply to shipping?',
             "No. The deduction is calculated on the goods value; shipping stays as it is. Clause 14.2 of the terms says the same."],
            ['Do vouchers work in the Premium Outlet?',
             "Yes, unless the code says otherwise. Vault prices are already reduced and the voucher applies to whatever step price is current."],
            ['What happens to a redeemed voucher if I withdraw?',
             "We refund what was actually paid. A promotional voucher does not come back to life afterwards and there is no claim to a replacement code (terms 14.5). For partial returns we spread the deduction across the items pro rata."],
            ['Can I give away or sell a voucher?',
             "Promotional vouchers are personal and non-transferable, and there is no cash payout. Using the same first-order discount across several accounts is grounds for us to block the codes (terms 14.6)."],
            ['Does the seller pay for my discount?',
             "No. The deduction is borne by the platform out of our commission, never out of the seller's payout. That is why a voucher is technically capped at the level of our commission."],
        ],
        'faq_cat_service' => [
            ['How do I reach you?',
             "By email to {$email} or through the contact form. We normally answer within one working day. There is deliberately no phone hotline: in writing both sides are on record — your question and our commitment."],
            ['Which languages is the site available in?',
             "{$langs} languages. We detect the language from your browser setting and the country your request comes from, and you can change it at the bottom of any page; the choice is remembered. The legal texts stay German — they are the binding version, and a half-translated set of terms helps nobody."],
            ['Do you store my IP address?',
             "No. For the language choice we only read the country code our network provider attaches to the request; the IP address itself is neither stored nor passed to a geolocation service."],
            ['Can I use the site without JavaScript?',
             "Yes. Search, filters, bag, checkout and account work fully without it. Scripts only make individual moments smoother, such as search suggestions."],
            ['What do you do about accessibility?',
             "We follow WCAG 2.1 level AA and the German accessibility act that has covered online retail since June 2025. The accessibility statement gives the current state including the known gaps — the points not yet met included."],
            ['Which size will fit me?',
             "The size guide holds measurement tables per category and the conversion between Italian, French, British and German sizing. Each product page also states whether the house runs generous or small."],
            ['Will a sold-out piece come back?',
             "Usually not — these are single items or single size runs. Write to us anyway: sometimes another seller holds the same size, and we will say plainly when no restock is expected."],
            ['Will you send me marketing if I only place an order?',
             "No. Ordering gets you order emails and nothing else. The newsletter and Vault membership have to be requested explicitly, and every one of those emails carries an unsubscribe link that works without signing in."],
        ],
        'faq_cat_sell' => [
            ['Who can sell on ' . $brand . '?',
             "Traders (registered businesses) and private individuals. Both register under \"Sell\", complete Stripe verification, then list."],
            ['What does it cost?',
             "No listing fee, no monthly fee. Commission: {$feeB}% for traders, {$feeP}% for private sellers, plus " . vr_money((int)vr_config('fee_fixed_cents', 35)) . " per item sold. Vault placement " . ((int)vr_config('fee_bps_outlet', 1500) / 100) . "%."],
            ['When and how am I paid?',
             "Through Stripe Connect. The buyer's payment minus commission lands in your Stripe balance and is paid to your bank on Stripe's normal schedule. We never hold your money."],
            ['Why must I verify with Stripe?',
             "Legal obligation for payment providers (anti-money-laundering, KYC). Without completed verification Stripe cannot pay you — until then your listings stay offline."],
            ['Do I need to register a business?',
             "Selling regularly with intent to profit is commercial activity and needs a business registration. Occasional selling from your own wardrobe is private. The classification is yours; we review outliers and get in touch."],
            ['How long does listing review take?',
             "Usually one working day. We check images, model code and price plausibility, and email you if something needs clarifying."],
        ],
    ];

    return $lang === 'de' ? $de : $en;
}
